
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-20T13:14:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6b3cee6f84061bac5eb94988cd4483be1708cbc",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
