
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-17T10:49:00-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "df06fa185435a74dc3cb5dba56fd0faf732e468e",
 "version": "5.4.95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
