# (generated with --quick)

import importlib.machinery
import os
import sys
import types
from typing import Any, Optional

def cached_import(module_path, class_name) -> Any: ...
def import_module(name: str, package: Optional[str] = ...) -> types.ModuleType: ...
def import_string(dotted_path) -> Any: ...
def importlib_find(name: str, package: Optional[str] = ...) -> Optional[importlib.machinery.ModuleSpec]: ...
def module_dir(module) -> Any: ...
def module_has_submodule(package, module_name) -> bool: ...
