# (generated with --quick)

from typing import Any

__all__: list[str]

def get_user(request) -> Any: ...
def get_user_model() -> Any: ...
def login(request, user) -> None: ...
def logout(request) -> None: ...
