# (generated with --quick)

from typing import Any, Generator

ImproperlyConfigured: Any
USER_HASH_SESSION_KEY: str
USER_ID_SESSION_KEY: str
constant_time_compare: Any
plain_packages: Any
rotate_token: Any
salted_hmac: Any
settings: Any
user_logged_in: Any
user_logged_out: Any

def _get_session_auth_hash(user, secret = ...) -> Any: ...
def _get_user_id_from_session(request) -> Any: ...
def get_session_auth_fallback_hash(user) -> Generator[Any, Any, None]: ...
def get_session_auth_hash(user) -> Any: ...
def get_user(request) -> Any: ...
def get_user_model() -> Any: ...
def login(request, user) -> None: ...
def logout(request) -> None: ...
