# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dima_sdk.models.list_onboarding_tracker200_response_data_inner_app_experience import ListOnboardingTracker200ResponseDataInnerAppExperience
from dima_sdk.models.list_onboarding_tracker200_response_data_inner_contract import ListOnboardingTracker200ResponseDataInnerContract
from dima_sdk.models.list_onboarding_tracker200_response_data_inner_hris_profile import ListOnboardingTracker200ResponseDataInnerHrisProfile
from dima_sdk.models.list_onboarding_tracker200_response_data_inner_progress import ListOnboardingTracker200ResponseDataInnerProgress
from typing import Optional, Set
from typing_extensions import Self

class ListOnboardingTracker200ResponseDataInner(BaseModel):
    """
    ListOnboardingTracker200ResponseDataInner
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The name associated with the onboarding")
    contract: Optional[ListOnboardingTracker200ResponseDataInnerContract] = None
    progress: Optional[ListOnboardingTracker200ResponseDataInnerProgress] = None
    unique_id: Optional[StrictStr] = Field(default=None, description="A unique identifier for the tracker")
    hiring_type: Optional[StrictStr] = Field(default=None, description="The type of hiring (e.g., contractor)")
    hris_profile: Optional[ListOnboardingTracker200ResponseDataInnerHrisProfile] = None
    app_experience: Optional[ListOnboardingTracker200ResponseDataInnerAppExperience] = None
    __properties: ClassVar[List[str]] = ["name", "contract", "progress", "unique_id", "hiring_type", "hris_profile", "app_experience"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListOnboardingTracker200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of contract
        if self.contract:
            _dict['contract'] = self.contract.to_dict()
        # override the default output from pydantic by calling `to_dict()` of progress
        if self.progress:
            _dict['progress'] = self.progress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hris_profile
        if self.hris_profile:
            _dict['hris_profile'] = self.hris_profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of app_experience
        if self.app_experience:
            _dict['app_experience'] = self.app_experience.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListOnboardingTracker200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "contract": ListOnboardingTracker200ResponseDataInnerContract.from_dict(obj["contract"]) if obj.get("contract") is not None else None,
            "progress": ListOnboardingTracker200ResponseDataInnerProgress.from_dict(obj["progress"]) if obj.get("progress") is not None else None,
            "unique_id": obj.get("unique_id"),
            "hiring_type": obj.get("hiring_type"),
            "hris_profile": ListOnboardingTracker200ResponseDataInnerHrisProfile.from_dict(obj["hris_profile"]) if obj.get("hris_profile") is not None else None,
            "app_experience": ListOnboardingTracker200ResponseDataInnerAppExperience.from_dict(obj["app_experience"]) if obj.get("app_experience") is not None else None
        })
        return _obj


