# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SalaryFrequencyScaleEnum(str, Enum):
    """
    Scale of the salary frequency.
    """

    """
    allowed enum values
    """
    MONTHLY = 'monthly'
    QUARTERLY = 'quarterly'
    ANNUALLY = 'annually'
    SPECIFIC_MONTH = 'specific_month'
    SPECIFIC_DATE = 'specific_date'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SalaryFrequencyScaleEnum from a JSON string"""
        return cls(json.loads(json_str))


