# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_software.api.snif_assist_service_api import SnifAssistServiceApi


class TestSnifAssistServiceApi(unittest.TestCase):
    """SnifAssistServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnifAssistServiceApi()

    def tearDown(self) -> None:
        pass

    def test_snif_assist_service_test_regex(self) -> None:
        """Test case for snif_assist_service_test_regex

        Summary: Test regex Description: Match a text string with a regular expression using the same sniffer  code used in production to match a regex.
        """
        pass


if __name__ == '__main__':
    unittest.main()
