# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime_factor_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from . import data_type_pb2 as data__type__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='realtime_factor_data.proto',
  package='cgs',
  syntax='proto3',
  serialized_options=b'\n2com.chinastock.gid.wsfront.marketdata.proto.factorB\013FactorProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1arealtime_factor_data.proto\x12\x03\x63gs\"h\n\x08RTFactor\x12\x13\n\x0bmarket_type\x18\x01 \x01(\t\x12\x15\n\rsecurity_code\x18\x02 \x01(\t\x12\x13\n\x0b\x66\x61\x63tor_name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x0c\n\x04time\x18\x05 \x01(\tBC\n2com.chinastock.gid.wsfront.marketdata.proto.factorB\x0b\x46\x61\x63torProtoP\x01\x62\x06proto3'
)




_RTFACTOR = _descriptor.Descriptor(
  name='RTFactor',
  full_name='cgs.RTFactor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='market_type', full_name='cgs.RTFactor.market_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='security_code', full_name='cgs.RTFactor.security_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='factor_name', full_name='cgs.RTFactor.factor_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='cgs.RTFactor.value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='cgs.RTFactor.time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['RTFactor'] = _RTFACTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RTFactor = _reflection.GeneratedProtocolMessageType('RTFactor', (_message.Message,), {
  'DESCRIPTOR' : _RTFACTOR,
  '__module__' : 'realtime_factor_data_pb2'
  # @@protoc_insertion_point(class_scope:cgs.RTFactor)
  })
_sym_db.RegisterMessage(RTFactor)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
