# coding: utf-8

"""
    Lead Scraping Service API

    Vector Lead Scraping Service API - Manages Lead Scraping Jobs

    The version of the OpenAPI document: 1.0
    Contact: yoanyomba@vector.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_backend_client_sdk.models.pricing_model import PricingModel

class TestPricingModel(unittest.TestCase):
    """PricingModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPricingModel(self):
        """Test PricingModel"""
        # inst = PricingModel()

if __name__ == '__main__':
    unittest.main()
