from typing import Any

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType

class Stream(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def maxpoints(self) -> int: ...
    @maxpoints.setter
    def maxpoints(self, val: int) -> None: ...
    @property
    def token(self) -> str: ...
    @token.setter
    def token(self, val: str) -> None: ...
    def __init__(
        self,
        arg: dict[str, int | str] | Stream = ...,
        maxpoints: int = ...,
        token: str = ...,
        **kwargs: Any,
    ) -> None: ...
