header_list = ["Official name", "Postal address", "Town", "NUTS code", "Postal code", "Country", "Contact person", "E-mail", "Telephone", "Internet address(es)", "Type of the contracting authority", "Main activity", "Email", "Legal type of the buyer", "Activity of the contracting authority", "Fax", "Internet address", "The contractor is an SME"]

proc_fields = ["1.  Description", "1.1.  Type of procedure", "1.3.  Information about a framework agreement or a dynamic purchasing system", "1.8.  Information about the Government Procurement Agreement (GPA)", "2.  Administrative information", "2.1.  Previous publication concerning this procedure", "2.8.  Information about termination of dynamic purchasing system", "2.9.  Information about termination of call for competition"]
non_roman_proc_f = ["The procedure is accelerated", "Purpose", "Main nature of the contract", "Main classification \xa0 ( cpv )", "General information", "Legal basis", "Place of performance", "Country", "Procedure identifier", "Title", "Internal identifier", "Value", "Previous notice", "Additional classification \xa0 ( cpv )"]
proc_fields_unnumbered = [" ".join(i.split()[1:]) for i in proc_fields] + non_roman_proc_f


lot_field_list_unnumbered = ['Scope of the procurement', 'Title', 'Main CPV code', 'Type of contract', 'Short description', 'Information about lots', 'Total value of the procurement', 'Description', 'Title', 'Additional CPV code(s)', 'Place of performance', 'Description of the procurement', 'Award criteria', 'Information about options', 'Information about European Union funds', 'Additional information', 'Type of contract and place of performance or delivery', 'Information about a framework agreement', 'Information about framework agreement', 'CPV code(s)', 'Information about the Government Procurement Agreement (GPA)', 'Information about the dynamic purchasing system', 'Electronic auction', 'Further information, mediation and review', 'Date of the conclusion of the contract', 'Review organisation', 'TED eSender', 'Maximum renewals', 'Value', 'Estimated value excluding VAT', 'Organisation whose budget is used to pay for the contract', 'Organisation executing the payment', 'General information', 'The procurement is covered by the Government Procurement Agreement (GPA)', 'Terms of procurement', 'Information about review deadlines', 'Options', 'Renewal', 'Strategic procurement', 'Estimated duration', 'Information about previous notices', 'Identifier of the previous notice', 'Identifier of the part of the previous notice', 'The buyer reserves the right for additional purchases from the contractor, as described here', 'Total value of the contract/lot']
more_lot_fields= ["Internal identifier", "Purpose", "Main nature of the contract", "Main classification \xa0 ( cpv )", "Additional classification \xa0 ( cpv )", "Main classification ( cpv )", "Main classification( cpv )", "Main classification (cpv)", "Award Criteria", "Techniques", "Framework Agreement","Framework agreement", "Additional classification ( cpv )"]
lot_fields = lot_field_list_unnumbered + more_lot_fields + ["II.1.  Scope of the procurement", "Title", "Description", "of the contract II.1.  Description", "Main CPV code","CPV code(s)","Additional CPV code(s)", "Type of contract", "Short description", "Information about lots","This contract is divided into lots", "Place of performance", "Description of the procurement", "Award criteria", "Information about options", "Information about European Union funds", "The procurement is related to a project and/or programme financed by European Union funds", "Additional information", "Main site or place of performance", "Total value of the procurement", "Total value of the contract/lot", "Reference number", "II.1.  Scope of the procurement", "Information about the Government Procurement Agreement (GPA)", "Information about a framework agreement or a dynamic purchasing system (DPS)"]

pre_section_titles = ["A contract/lot is awarded", "Contract No", "Title"]
subheaders = ["Contract No", "Title :", "Lot No : 1 Title :", "Lot title", "Award of contract", "V.1.  Award and contract value", "A contract/lot is awarded", "V.1.  Date of conclusion of the contract", "Date of conclusion of the contract", "Information about tenders", "Name and address of the contractor", "Information on value of the contract/lot", "Information about subcontracting", "Price paid for bargain purchases", "Number of tenders received", "The contract has been awarded to a group of economic operators"]       
buyer_fields = header_list
sec6_headers = ["Additional information", "Information about European Union funds", "Procedures for review", "Review body", "Review procedure", "Service from which information about the review procedure may be obtained", "Date of dispatch of this notice", "Body responsible for mediation procedures"]

res_field_names = ["Value of all contracts awarded in this notice", "Result lot ldentifier", "Winner selection status"]
key_sections612 = ["Information about winners", "Tender", "Contract information"]
winner_fields = ["Official name"]
tender_fields = ["Rank in the list of winners","The tender was ranked", "Value of the result", "Identifier of lot or group of lots", "Tender identifier", "Concession value", "The tender is a variant"]
contract_info_fields = ["The contract is awarded within a framework agreement", "Date of the conclusion of the contract", "Date on which the winner was chosen", "Identifier of the contract", "Title"]
all_fields = res_field_names + key_sections612 + winner_fields + tender_fields + contract_info_fields + sec6_headers

other_fields = ["Notice information", "Notice identifier/version", "Form type", "Notice type", "Notice subtype", "Notice dispatch date","Publication information", "Notice publication number", "OJ S issue number", "Publication date"]