# (generated with --quick)

import os
import platform
import requests
import subprocess
import sys
import tomlkit
from typing import Annotated, Any

DEFAULT_CSS: str
settings: Any

class Tailwind:
    config_path: Annotated[str, 'property']
    dist_css_path: Annotated[str, 'property']
    src_css_path: Annotated[str, 'property']
    standalone_path: Annotated[str, 'property']
    target_directory: Annotated[str, 'property']
    version_lockfile_path: Annotated[str, 'property']
    def config_exists(self) -> bool: ...
    def create_config(self) -> None: ...
    def create_src_css(self) -> None: ...
    @staticmethod
    def detect_platform_slug() -> str: ...
    def download(self, version = ...) -> str: ...
    def get_version_from_config(self) -> str: ...
    def install(self, version = ...) -> str: ...
    def invoke(self, *args, cwd = ...) -> None: ...
    def is_installed(self) -> bool: ...
    def needs_update(self) -> bool: ...
    def set_version_in_config(self, version) -> None: ...
    def src_css_exists(self) -> bool: ...
