# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.update_time_off_request_data import UpdateTimeOffRequestData

class TestUpdateTimeOffRequestData(unittest.TestCase):
    """UpdateTimeOffRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTimeOffRequestData:
        """Test UpdateTimeOffRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTimeOffRequestData`
        """
        model = UpdateTimeOffRequestData()
        if include_optional:
            return UpdateTimeOffRequestData(
                id = '',
                dates = [
                    dima_sdk.models.update_time_off_request_data_dates_inner.updateTimeOff_request_data_dates_inner(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        hours = 1.337, 
                        amount = 1.337, 
                        day_type = 'HALF_DAY', )
                    ],
                reason = '',
                is_paid = True,
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                attachments = [
                    dima_sdk.models.update_time_off_request_data_attachments_inner.updateTimeOff_request_data_attachments_inner(
                        id = '', 
                        key = '', 
                        filename = '0', 
                        upload_id = '', )
                    ],
                description = '',
                contract_oid = '',
                deduction_amount = 1,
                time_off_type_id = '',
                time_off_percentage = 0,
                recipient_profile_id = '',
                other_type_description = ''
            )
        else:
            return UpdateTimeOffRequestData(
        )
        """

    def testUpdateTimeOffRequestData(self):
        """Test UpdateTimeOffRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
