# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_invoice_adjustment_request import CreateInvoiceAdjustmentRequest

class TestCreateInvoiceAdjustmentRequest(unittest.TestCase):
    """CreateInvoiceAdjustmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInvoiceAdjustmentRequest:
        """Test CreateInvoiceAdjustmentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInvoiceAdjustmentRequest`
        """
        model = CreateInvoiceAdjustmentRequest()
        if include_optional:
            return CreateInvoiceAdjustmentRequest(
                type = 'bonus',
                amount = 100,
                contract_id = 'string',
                description = 'string',
                date_submitted = 'Sat Dec 31 01:00:00 CET 2022',
                payment_cycle_id = 1
            )
        else:
            return CreateInvoiceAdjustmentRequest(
                type = 'bonus',
                amount = 100,
                contract_id = 'string',
                description = 'string',
                date_submitted = 'Sat Dec 31 01:00:00 CET 2022',
        )
        """

    def testCreateInvoiceAdjustmentRequest(self):
        """Test CreateInvoiceAdjustmentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
