# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.hris_direct_employee_to_create_container_data_employment import HrisDirectEmployeeToCreateContainerDataEmployment

class TestHrisDirectEmployeeToCreateContainerDataEmployment(unittest.TestCase):
    """HrisDirectEmployeeToCreateContainerDataEmployment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HrisDirectEmployeeToCreateContainerDataEmployment:
        """Test HrisDirectEmployeeToCreateContainerDataEmployment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HrisDirectEmployeeToCreateContainerDataEmployment`
        """
        model = HrisDirectEmployeeToCreateContainerDataEmployment()
        if include_optional:
            return HrisDirectEmployeeToCreateContainerDataEmployment(
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                type = 'Part-time',
                part_time_percentage = 1
            )
        else:
            return HrisDirectEmployeeToCreateContainerDataEmployment(
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                type = 'Part-time',
                part_time_percentage = 1,
        )
        """

    def testHrisDirectEmployeeToCreateContainerDataEmployment(self):
        """Test HrisDirectEmployeeToCreateContainerDataEmployment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
