# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.upsert_custom_field_value_from_contracts_request_data_any_of3 import UpsertCustomFieldValueFromContractsRequestDataAnyOf3

class TestUpsertCustomFieldValueFromContractsRequestDataAnyOf3(unittest.TestCase):
    """UpsertCustomFieldValueFromContractsRequestDataAnyOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertCustomFieldValueFromContractsRequestDataAnyOf3:
        """Test UpsertCustomFieldValueFromContractsRequestDataAnyOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertCustomFieldValueFromContractsRequestDataAnyOf3`
        """
        model = UpsertCustomFieldValueFromContractsRequestDataAnyOf3()
        if include_optional:
            return UpsertCustomFieldValueFromContractsRequestDataAnyOf3(
                option = 'option'
            )
        else:
            return UpsertCustomFieldValueFromContractsRequestDataAnyOf3(
        )
        """

    def testUpsertCustomFieldValueFromContractsRequestDataAnyOf3(self):
        """Test UpsertCustomFieldValueFromContractsRequestDataAnyOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
