# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.edit_legal_entity403_response import EditLegalEntity403Response

class TestEditLegalEntity403Response(unittest.TestCase):
    """EditLegalEntity403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditLegalEntity403Response:
        """Test EditLegalEntity403Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditLegalEntity403Response`
        """
        model = EditLegalEntity403Response()
        if include_optional:
            return EditLegalEntity403Response(
                error = 'User must be a manager of the organization to update an entity.'
            )
        else:
            return EditLegalEntity403Response(
        )
        """

    def testEditLegalEntity403Response(self):
        """Test EditLegalEntity403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
