# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_consent_token400_response import CreateConsentToken400Response

class TestCreateConsentToken400Response(unittest.TestCase):
    """CreateConsentToken400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateConsentToken400Response:
        """Test CreateConsentToken400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateConsentToken400Response`
        """
        model = CreateConsentToken400Response()
        if include_optional:
            return CreateConsentToken400Response(
                error = ''
            )
        else:
            return CreateConsentToken400Response(
        )
        """

    def testCreateConsentToken400Response(self):
        """Test CreateConsentToken400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
