# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.list_onboarding_tracker200_response_data_inner_progress import ListOnboardingTracker200ResponseDataInnerProgress

class TestListOnboardingTracker200ResponseDataInnerProgress(unittest.TestCase):
    """ListOnboardingTracker200ResponseDataInnerProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOnboardingTracker200ResponseDataInnerProgress:
        """Test ListOnboardingTracker200ResponseDataInnerProgress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOnboardingTracker200ResponseDataInnerProgress`
        """
        model = ListOnboardingTracker200ResponseDataInnerProgress()
        if include_optional:
            return ListOnboardingTracker200ResponseDataInnerProgress(
                status = 'ONBOARDING_OVERDUE',
                reference_date = '2021-07-14T22:00Z',
                people_list_status = 'onboarding_overdue',
                subject_to_overdue = True,
                onboarding_due_date = '2021-07-14T22:00Z',
                reference_date_type = 'EFFECTIVE_DATE',
                reference_date_timezone = 'Europe/Brussels',
                is_action_required_from_client = False
            )
        else:
            return ListOnboardingTracker200ResponseDataInnerProgress(
        )
        """

    def testListOnboardingTracker200ResponseDataInnerProgress(self):
        """Test ListOnboardingTracker200ResponseDataInnerProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
