# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.get_contract_by_id200_response_data_invitations import GetContractById200ResponseDataInvitations

class TestGetContractById200ResponseDataInvitations(unittest.TestCase):
    """GetContractById200ResponseDataInvitations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetContractById200ResponseDataInvitations:
        """Test GetContractById200ResponseDataInvitations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetContractById200ResponseDataInvitations`
        """
        model = GetContractById200ResponseDataInvitations()
        if include_optional:
            return GetContractById200ResponseDataInvitations(
                client_email = 'client@example.com',
                worker_email = 'worker@example.com'
            )
        else:
            return GetContractById200ResponseDataInvitations(
        )
        """

    def testGetContractById200ResponseDataInvitations(self):
        """Test GetContractById200ResponseDataInvitations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
