# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_bank_transfer_method201_response_data import CreateBankTransferMethod201ResponseData

class TestCreateBankTransferMethod201ResponseData(unittest.TestCase):
    """CreateBankTransferMethod201ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBankTransferMethod201ResponseData:
        """Test CreateBankTransferMethod201ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBankTransferMethod201ResponseData`
        """
        model = CreateBankTransferMethod201ResponseData()
        if include_optional:
            return CreateBankTransferMethod201ResponseData(
                id = '123e4567-e89b-12d3-a456-426614174000',
                status = 'approved'
            )
        else:
            return CreateBankTransferMethod201ResponseData(
        )
        """

    def testCreateBankTransferMethod201ResponseData(self):
        """Test CreateBankTransferMethod201ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
