# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.timeoff_to_review_internal_container import TimeoffToReviewInternalContainer

class TestTimeoffToReviewInternalContainer(unittest.TestCase):
    """TimeoffToReviewInternalContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeoffToReviewInternalContainer:
        """Test TimeoffToReviewInternalContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeoffToReviewInternalContainer`
        """
        model = TimeoffToReviewInternalContainer()
        if include_optional:
            return TimeoffToReviewInternalContainer(
                data = dima_sdk.models.timeoff_review_internal.TimeoffReviewInternal(
                    status = 'APPROVED', 
                    reason = 'Approved because there are no conflicts.', )
            )
        else:
            return TimeoffToReviewInternalContainer(
                data = dima_sdk.models.timeoff_review_internal.TimeoffReviewInternal(
                    status = 'APPROVED', 
                    reason = 'Approved because there are no conflicts.', ),
        )
        """

    def testTimeoffToReviewInternalContainer(self):
        """Test TimeoffToReviewInternalContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
