# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.upsert_child_worker_relations_external_id_request_data_child_hris_profile_ids_inner_one_of import UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf

class TestUpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf(unittest.TestCase):
    """UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf:
        """Test UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf`
        """
        model = UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf()
        if include_optional:
            return UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf(
                relation_external_id = '',
                external_hris_profile_id = ''
            )
        else:
            return UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf(
                relation_external_id = '',
                external_hris_profile_id = '',
        )
        """

    def testUpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf(self):
        """Test UpsertChildWorkerRelationsExternalIdRequestDataChildHrisProfileIdsInnerOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
