# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.milestone_reviews_to_create import MilestoneReviewsToCreate

class TestMilestoneReviewsToCreate(unittest.TestCase):
    """MilestoneReviewsToCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MilestoneReviewsToCreate:
        """Test MilestoneReviewsToCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MilestoneReviewsToCreate`
        """
        model = MilestoneReviewsToCreate()
        if include_optional:
            return MilestoneReviewsToCreate(
                status = 'approved',
                reason = '',
                ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ]
            )
        else:
            return MilestoneReviewsToCreate(
                status = 'approved',
                ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ],
        )
        """

    def testMilestoneReviewsToCreate(self):
        """Test MilestoneReviewsToCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
