# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.payments_detailed_report_container import PaymentsDetailedReportContainer

class TestPaymentsDetailedReportContainer(unittest.TestCase):
    """PaymentsDetailedReportContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentsDetailedReportContainer:
        """Test PaymentsDetailedReportContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentsDetailedReportContainer`
        """
        model = PaymentsDetailedReportContainer()
        if include_optional:
            return PaymentsDetailedReportContainer(
                data = [
                    dima_sdk.models.payments_detailed_report_container_data_inner.PaymentsDetailedReportContainer_data_inner(
                        invoice = dima_sdk.models.payments_detailed_report_container_data_inner_invoice.PaymentsDetailedReportContainer_data_inner_invoice(
                            document = 'INV-2023-4', 
                            issued_at = '2022-05-24T09:38:46.235Z', 
                            id = 'rhCTiRd9Mad41RwjsFWw-', ), 
                        line_item = dima_sdk.models.payments_detailed_report_container_data_inner_line_item.PaymentsDetailedReportContainer_data_inner_line_item(
                            description = 'One off payment', 
                            category = 'Offcycle', 
                            amount = '1000', 
                            currency = 'USD', ), 
                        payment = dima_sdk.models.payments_detailed_report_container_data_inner_payment.PaymentsDetailedReportContainer_data_inner_payment(
                            paid_at = '2022-05-24T09:38:46.235Z', 
                            currency = 'USD', 
                            amount = '1000', 
                            document = 'REC-2024-3', ), 
                        contract = dima_sdk.models.payments_detailed_report_container_data_inner_contract.PaymentsDetailedReportContainer_data_inner_contract(
                            id = '37nex2x', 
                            name = 'John Doe', 
                            legal_entity = 'Wayne Enterprise Global', ), )
                    ],
                page = dima_sdk.models.page_info_without_cursor_new.PageInfoWithoutCursorNew(
                    total_rows = 1.337, 
                    items_per_page = 1, 
                    offset = 0, )
            )
        else:
            return PaymentsDetailedReportContainer(
                data = [
                    dima_sdk.models.payments_detailed_report_container_data_inner.PaymentsDetailedReportContainer_data_inner(
                        invoice = dima_sdk.models.payments_detailed_report_container_data_inner_invoice.PaymentsDetailedReportContainer_data_inner_invoice(
                            document = 'INV-2023-4', 
                            issued_at = '2022-05-24T09:38:46.235Z', 
                            id = 'rhCTiRd9Mad41RwjsFWw-', ), 
                        line_item = dima_sdk.models.payments_detailed_report_container_data_inner_line_item.PaymentsDetailedReportContainer_data_inner_line_item(
                            description = 'One off payment', 
                            category = 'Offcycle', 
                            amount = '1000', 
                            currency = 'USD', ), 
                        payment = dima_sdk.models.payments_detailed_report_container_data_inner_payment.PaymentsDetailedReportContainer_data_inner_payment(
                            paid_at = '2022-05-24T09:38:46.235Z', 
                            currency = 'USD', 
                            amount = '1000', 
                            document = 'REC-2024-3', ), 
                        contract = dima_sdk.models.payments_detailed_report_container_data_inner_contract.PaymentsDetailedReportContainer_data_inner_contract(
                            id = '37nex2x', 
                            name = 'John Doe', 
                            legal_entity = 'Wayne Enterprise Global', ), )
                    ],
                page = dima_sdk.models.page_info_without_cursor_new.PageInfoWithoutCursorNew(
                    total_rows = 1.337, 
                    items_per_page = 1, 
                    offset = 0, ),
        )
        """

    def testPaymentsDetailedReportContainer(self):
        """Test PaymentsDetailedReportContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
