# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_admin_user_response_container import CreateAdminUserResponseContainer

class TestCreateAdminUserResponseContainer(unittest.TestCase):
    """CreateAdminUserResponseContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAdminUserResponseContainer:
        """Test CreateAdminUserResponseContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAdminUserResponseContainer`
        """
        model = CreateAdminUserResponseContainer()
        if include_optional:
            return CreateAdminUserResponseContainer(
                data = dima_sdk.models.admin_user.AdminUser(
                    id = '00000000-0000-0000-0000-000000000000', 
                    first_name = '', 
                    last_name = '', 
                    email = '', )
            )
        else:
            return CreateAdminUserResponseContainer(
                data = dima_sdk.models.admin_user.AdminUser(
                    id = '00000000-0000-0000-0000-000000000000', 
                    first_name = '', 
                    last_name = '', 
                    email = '', ),
        )
        """

    def testCreateAdminUserResponseContainer(self):
        """Test CreateAdminUserResponseContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
