# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_timeoff import CreateTimeoff

class TestCreateTimeoff(unittest.TestCase):
    """CreateTimeoff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTimeoff:
        """Test CreateTimeoff
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTimeoff`
        """
        model = CreateTimeoff()
        if include_optional:
            return CreateTimeoff(
                type = 'VACATION',
                start_date = '2022-09-03T00:00:00.000Z',
                end_date = '2022-09-05T00:00:00.000Z',
                with_multiple_dates = True,
                reason = 'Holiday',
                is_start_date_half_day = False,
                is_end_date_half_day = False,
                other_timeoff_name = 'Birthday'
            )
        else:
            return CreateTimeoff(
                type = 'VACATION',
                with_multiple_dates = True,
        )
        """

    def testCreateTimeoff(self):
        """Test CreateTimeoff"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
