# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_shifts201_response_data_inner import CreateShifts201ResponseDataInner

class TestCreateShifts201ResponseDataInner(unittest.TestCase):
    """CreateShifts201ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShifts201ResponseDataInner:
        """Test CreateShifts201ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateShifts201ResponseDataInner`
        """
        model = CreateShifts201ResponseDataInner()
        if include_optional:
            return CreateShifts201ResponseDataInner(
                meta = dima_sdk.models.create_shifts_201_response_data_inner_meta.createShifts_201_response_data_inner_meta(
                    end = dima_sdk.models.create_shifts_201_response_data_inner_meta_end.createShifts_201_response_data_inner_meta_end(
                        date = '2023-10-01', 
                        time = '08:00', 
                        is_rest_day = False, 
                        is_public_holiday = False, ), 
                    start = dima_sdk.models.create_shifts_201_response_data_inner_meta_start.createShifts_201_response_data_inner_meta_start(
                        date = '2023-10-01', 
                        time = '08:00', 
                        is_rest_day = False, 
                        is_public_holiday = False, ), 
                    breaks = [
                        dima_sdk.models.create_shifts_201_response_data_inner_meta_breaks_inner.createShifts_201_response_data_inner_meta_breaks_inner(
                            is_paid = False, )
                        ], 
                    approval_date = '2023-10-02', ),
                summary = dima_sdk.models.create_shifts_201_response_data_inner_summary.createShifts_201_response_data_inner_summary(
                    total_break_hours = 2, 
                    payable_break_hours = 2, 
                    total_payable_hours = 2, 
                    shift_duration_hours = 2, 
                    shift_rate_external_id = 'abcd', ),
                created_at = '2024-10-08T12:08:29.695Z',
                updated_at = '2024-10-08T12:08:29.695Z',
                contract_id = '1234',
                description = 'This is a sample shift description.',
                external_id = 'shift_123456r',
                date_of_work = '2023-10-01'
            )
        else:
            return CreateShifts201ResponseDataInner(
                summary = dima_sdk.models.create_shifts_201_response_data_inner_summary.createShifts_201_response_data_inner_summary(
                    total_break_hours = 2, 
                    payable_break_hours = 2, 
                    total_payable_hours = 2, 
                    shift_duration_hours = 2, 
                    shift_rate_external_id = 'abcd', ),
                contract_id = '1234',
                external_id = 'shift_123456r',
                date_of_work = '2023-10-01',
        )
        """

    def testCreateShifts201ResponseDataInner(self):
        """Test CreateShifts201ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
