# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.get_milestones_by_contract_and_id200_response import GetMilestonesByContractAndId200Response

class TestGetMilestonesByContractAndId200Response(unittest.TestCase):
    """GetMilestonesByContractAndId200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMilestonesByContractAndId200Response:
        """Test GetMilestonesByContractAndId200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMilestonesByContractAndId200Response`
        """
        model = GetMilestonesByContractAndId200Response()
        if include_optional:
            return GetMilestonesByContractAndId200Response(
                data = dima_sdk.models.get_milestones_by_contract_and_id_200_response_data.getMilestonesByContractAndId_200_response_data(
                    id = null, 
                    title = '', 
                    amount = '', 
                    status = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '', 
                    reported_by = dima_sdk.models.get_milestones_by_contract_and_id_200_response_data_reported_by.getMilestonesByContractAndId_200_response_data_reported_by(
                        id = null, 
                        full_name = '', ), 
                    reviewed_by = dima_sdk.models.get_milestones_by_contract_and_id_200_response_data_reviewed_by.getMilestonesByContractAndId_200_response_data_reviewed_by(
                        id = , 
                        full_name = '', ), 
                    approval_requested = True, )
            )
        else:
            return GetMilestonesByContractAndId200Response(
                data = dima_sdk.models.get_milestones_by_contract_and_id_200_response_data.getMilestonesByContractAndId_200_response_data(
                    id = null, 
                    title = '', 
                    amount = '', 
                    status = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '', 
                    reported_by = dima_sdk.models.get_milestones_by_contract_and_id_200_response_data_reported_by.getMilestonesByContractAndId_200_response_data_reported_by(
                        id = null, 
                        full_name = '', ), 
                    reviewed_by = dima_sdk.models.get_milestones_by_contract_and_id_200_response_data_reviewed_by.getMilestonesByContractAndId_200_response_data_reviewed_by(
                        id = , 
                        full_name = '', ), 
                    approval_requested = True, ),
        )
        """

    def testGetMilestonesByContractAndId200Response(self):
        """Test GetMilestonesByContractAndId200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
