# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.get_timesheet_by_id200_response_data_all_of_approvers_inner import GetTimesheetById200ResponseDataAllOfApproversInner

class TestGetTimesheetById200ResponseDataAllOfApproversInner(unittest.TestCase):
    """GetTimesheetById200ResponseDataAllOfApproversInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTimesheetById200ResponseDataAllOfApproversInner:
        """Test GetTimesheetById200ResponseDataAllOfApproversInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTimesheetById200ResponseDataAllOfApproversInner`
        """
        model = GetTimesheetById200ResponseDataAllOfApproversInner()
        if include_optional:
            return GetTimesheetById200ResponseDataAllOfApproversInner(
                email = '',
                approved = True,
                full_name = ''
            )
        else:
            return GetTimesheetById200ResponseDataAllOfApproversInner(
                email = '',
                approved = True,
                full_name = '',
        )
        """

    def testGetTimesheetById200ResponseDataAllOfApproversInner(self):
        """Test GetTimesheetById200ResponseDataAllOfApproversInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
