# (generated with --quick)

from typing import Any

def check_password(password, encoded, setter = ..., preferred = ...) -> Any: ...
def check_user_password(user, password) -> Any: ...
def hash_password(password, salt = ..., hasher = ...) -> Any: ...
