# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PeoplePersonalContainerDataOoo(BaseModel):
    """
    PeoplePersonalContainerDataOoo
    """ # noqa: E501
    leave_type: Optional[StrictStr] = Field(default=None, description="The type of leave.")
    start_date: Optional[date] = Field(default=None, description="The start date of the leave.")
    end_date: Optional[date] = Field(default=None, description="The end date of the leave.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the leave.")
    __properties: ClassVar[List[str]] = ["leave_type", "start_date", "end_date", "name"]

    @field_validator('leave_type')
    def leave_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['LONG_TERM_LEAVE', 'SHORT_TERM_LEAVE']):
            raise ValueError("must be one of enum values ('LONG_TERM_LEAVE', 'SHORT_TERM_LEAVE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PeoplePersonalContainerDataOoo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PeoplePersonalContainerDataOoo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "leave_type": obj.get("leave_type"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "name": obj.get("name")
        })
        return _obj


