class Data:
    assess__download_task__create = {
        'ascending': True,
        'elementType': 1,
        'orderBy': '',
        'queryField': [
            'threeMinReplyRate',
            'sessionThreeMinReplyRate',
            'noReplySessionRate',
            'askBuyerNumManual',
            'askBuyerCntManual',
            'manualSessionCnt',
            'avgReplyDurManual',
            'goodEvaluateRate',
            'sessionGoodEvaluateRate',
            'badEvaluateRate',
            'sessionBadEvaluateRate',
            'normalEvaluateRate',
            'sessionNormalEvaluateRate',
            'imBadEvaluateRate',
            'sessionTransferPlatformRate',
            'inviteEvaluateCnt',
            'evaluateCnt',
            'goodEvaluateCnt',
            'normalEvaluateCnt',
            'badEvaluateCnt',
            'inviteEvaluateSessionCnt',
            'evaluateSessionCnt',
            'inviteEvaluateRate',
            'evaluateRate',
            'askOrderBuyerCnt',
            'createOrderBuyerCnt',
            'askOrderPayOrderBuyerCnt',
            'askOrderPayOrderRate',
            'askOrderSingleBuyerValue',
            'askOrderPayOrderAmtView',
            'createTaskCntSum',
            'crt7dayIntimeEndTaskDealDuration',
            'crt7dayOvertimeEndTaskCntSumRate',
            'crt7dayPendingTaskSum',
            'crt7dayDealingTaskSum',
            'crt7dayOvertimeEndTaskSum',
        ],
        'timeRange': 'CUSTOMIZED_RANGE',
    }


class RequestData:
    data = Data()
