data = [
    {
        "label": "Afghanistan",
        "iso_en_shortname": "Afghanistan",
        "iso_fr_shortname": "Afghanistan (l')",
        "iso_alpha2": "AF",
        "iso_alpha3": "AFG",
        "iso_numeric": 4,
    },
    {
        "label": "Albania",
        "iso_en_shortname": "Albania",
        "iso_fr_shortname": "Albanie (l')",
        "iso_alpha2": "AL",
        "iso_alpha3": "ALB",
        "iso_numeric": 8,
    },
    {
        "label": "Algeria",
        "iso_en_shortname": "Algeria",
        "iso_fr_shortname": "Algérie (l')",
        "iso_alpha2": "DZ",
        "iso_alpha3": "DZA",
        "iso_numeric": 12,
    },
    {
        "label": "American Samoa",
        "iso_en_shortname": "American Samoa",
        "iso_fr_shortname": "Samoa américaines (les)",
        "iso_alpha2": "AS",
        "iso_alpha3": "ASM",
        "iso_numeric": 16,
    },
    {
        "label": "Andorra",
        "iso_en_shortname": "Andorra",
        "iso_fr_shortname": "Andorre (l')",
        "iso_alpha2": "AD",
        "iso_alpha3": "AND",
        "iso_numeric": 20,
    },
    {
        "label": "Angola",
        "iso_en_shortname": "Angola",
        "iso_fr_shortname": "Angola (l')",
        "iso_alpha2": "AO",
        "iso_alpha3": "AGO",
        "iso_numeric": 24,
    },
    {
        "label": "Anguilla",
        "iso_en_shortname": "Anguilla",
        "iso_fr_shortname": "Anguilla",
        "iso_alpha2": "AI",
        "iso_alpha3": "AIA",
        "iso_numeric": 660,
    },
    {
        "label": "Antarctica",
        "iso_en_shortname": "Antarctica",
        "iso_fr_shortname": "Antarctique (l')",
        "iso_alpha2": "AQ",
        "iso_alpha3": "ATA",
        "iso_numeric": 10,
    },
    {
        "label": "Antigua and Barbuda",
        "iso_en_shortname": "Antigua and Barbuda",
        "iso_fr_shortname": "Antigua-et-Barbuda",
        "iso_alpha2": "AG",
        "iso_alpha3": "ATG",
        "iso_numeric": 28,
    },
    {
        "label": "Argentina",
        "iso_en_shortname": "Argentina",
        "iso_fr_shortname": "Argentine (l')",
        "iso_alpha2": "AR",
        "iso_alpha3": "ARG",
        "iso_numeric": 32,
    },
    {
        "label": "Armenia",
        "iso_en_shortname": "Armenia",
        "iso_fr_shortname": "Arménie (l')",
        "iso_alpha2": "AM",
        "iso_alpha3": "ARM",
        "iso_numeric": 51,
    },
    {
        "label": "Aruba",
        "iso_en_shortname": "Aruba",
        "iso_fr_shortname": "Aruba",
        "iso_alpha2": "AW",
        "iso_alpha3": "ABW",
        "iso_numeric": 533,
    },
    {
        "label": "Australia",
        "iso_en_shortname": "Australia",
        "iso_fr_shortname": "Australie (l')",
        "iso_alpha2": "AU",
        "iso_alpha3": "AUS",
        "iso_numeric": 36,
    },
    {
        "label": "Austria",
        "iso_en_shortname": "Austria",
        "iso_fr_shortname": "Autriche (l')",
        "iso_alpha2": "AT",
        "iso_alpha3": "AUT",
        "iso_numeric": 40,
    },
    {
        "label": "Azerbaijan",
        "iso_en_shortname": "Azerbaijan",
        "iso_fr_shortname": "Azerbaïdjan (l')",
        "iso_alpha2": "AZ",
        "iso_alpha3": "AZE",
        "iso_numeric": 31,
    },
    {
        "label": "Bahamas",
        "iso_en_shortname": "Bahamas (the)",
        "iso_fr_shortname": "Bahamas (les)",
        "iso_alpha2": "BS",
        "iso_alpha3": "BHS",
        "iso_numeric": 44,
    },
    {
        "label": "Bahrain",
        "iso_en_shortname": "Bahrain",
        "iso_fr_shortname": "Bahreïn",
        "iso_alpha2": "BH",
        "iso_alpha3": "BHR",
        "iso_numeric": 48,
    },
    {
        "label": "Bangladesh",
        "iso_en_shortname": "Bangladesh",
        "iso_fr_shortname": "Bangladesh (le)",
        "iso_alpha2": "BD",
        "iso_alpha3": "BGD",
        "iso_numeric": 50,
    },
    {
        "label": "Barbados",
        "iso_en_shortname": "Barbados",
        "iso_fr_shortname": "Barbade (la)",
        "iso_alpha2": "BB",
        "iso_alpha3": "BRB",
        "iso_numeric": 52,
    },
    {
        "label": "Belarus",
        "iso_en_shortname": "Belarus",
        "iso_fr_shortname": "Bélarus (le)",
        "iso_alpha2": "BY",
        "iso_alpha3": "BLR",
        "iso_numeric": 112,
    },
    {
        "label": "Belgium",
        "iso_en_shortname": "Belgium",
        "iso_fr_shortname": "Belgique (la)",
        "iso_alpha2": "BE",
        "iso_alpha3": "BEL",
        "iso_numeric": 56,
    },
    {
        "label": "Belize",
        "iso_en_shortname": "Belize",
        "iso_fr_shortname": "Belize (le)",
        "iso_alpha2": "BZ",
        "iso_alpha3": "BLZ",
        "iso_numeric": 84,
    },
    {
        "label": "Benin",
        "iso_en_shortname": "Benin",
        "iso_fr_shortname": "Bénin (le)",
        "iso_alpha2": "BJ",
        "iso_alpha3": "BEN",
        "iso_numeric": 204,
    },
    {
        "label": "Bermuda",
        "iso_en_shortname": "Bermuda",
        "iso_fr_shortname": "Bermudes (les)",
        "iso_alpha2": "BM",
        "iso_alpha3": "BMU",
        "iso_numeric": 60,
    },
    {
        "label": "Bhutan",
        "iso_en_shortname": "Bhutan",
        "iso_fr_shortname": "Bhoutan (le)",
        "iso_alpha2": "BT",
        "iso_alpha3": "BTN",
        "iso_numeric": 64,
    },
    {
        "label": "Bolivia",
        "iso_en_shortname": "Bolivia (Plurinational State of)",
        "iso_fr_shortname": "Bolivie (l'État plurinational de)",
        "iso_alpha2": "BO",
        "iso_alpha3": "BOL",
        "iso_numeric": 68,
    },
    {
        "label": "Bonaire",
        "iso_en_shortname": "Bonaire, Sint Eustatius and Saba",
        "iso_fr_shortname": "Bonaire, Saint-Eustache et Saba",
        "iso_alpha2": "BQ",
        "iso_alpha3": "BES",
        "iso_numeric": 535,
    },
    {
        "label": "Bosnia and Herzegovina",
        "iso_en_shortname": "Bosnia and Herzegovina",
        "iso_fr_shortname": "Bosnie-Herzégovine (la)",
        "iso_alpha2": "BA",
        "iso_alpha3": "BIH",
        "iso_numeric": 70,
    },
    {
        "label": "Botswana",
        "iso_en_shortname": "Botswana",
        "iso_fr_shortname": "Botswana (le)",
        "iso_alpha2": "BW",
        "iso_alpha3": "BWA",
        "iso_numeric": 72,
    },
    {
        "label": "Bouvet Island",
        "iso_en_shortname": "Bouvet Island",
        "iso_fr_shortname": "Bouvet (l'île)",
        "iso_alpha2": "BV",
        "iso_alpha3": "BVT",
        "iso_numeric": 74,
    },
    {
        "label": "Brazil",
        "iso_en_shortname": "Brazil",
        "iso_fr_shortname": "Brésil (le)",
        "iso_alpha2": "BR",
        "iso_alpha3": "BRA",
        "iso_numeric": 76,
    },
    {
        "label": "British Indian Ocean Territory",
        "iso_en_shortname": "British Indian Ocean Territory (the)",
        "iso_fr_shortname": "Indien (le Territoire britannique de l'océan)",
        "iso_alpha2": "IO",
        "iso_alpha3": "IOT",
        "iso_numeric": 86,
    },
    {
        "label": "Brunei",
        "iso_en_shortname": "Brunei Darussalam",
        "iso_fr_shortname": "Brunéi Darussalam (le)",
        "iso_alpha2": "BN",
        "iso_alpha3": "BRN",
        "iso_numeric": 96,
    },
    {
        "label": "Bulgaria",
        "iso_en_shortname": "Bulgaria",
        "iso_fr_shortname": "Bulgarie (la)",
        "iso_alpha2": "BG",
        "iso_alpha3": "BGR",
        "iso_numeric": 100,
    },
    {
        "label": "Burkina Faso",
        "iso_en_shortname": "Burkina Faso",
        "iso_fr_shortname": "Burkina Faso (le)",
        "iso_alpha2": "BF",
        "iso_alpha3": "BFA",
        "iso_numeric": 854,
    },
    {
        "label": "Burundi",
        "iso_en_shortname": "Burundi",
        "iso_fr_shortname": "Burundi (le)",
        "iso_alpha2": "BI",
        "iso_alpha3": "BDI",
        "iso_numeric": 108,
    },
    {
        "label": "Cabo Verde",
        "iso_en_shortname": "Cabo Verde",
        "iso_fr_shortname": "Cabo Verde",
        "iso_alpha2": "CV",
        "iso_alpha3": "CPV",
        "iso_numeric": 132,
    },
    {
        "label": "Cambodia",
        "iso_en_shortname": "Cambodia",
        "iso_fr_shortname": "Cambodge (le)",
        "iso_alpha2": "KH",
        "iso_alpha3": "KHM",
        "iso_numeric": 116,
    },
    {
        "label": "Cameroon",
        "iso_en_shortname": "Cameroon",
        "iso_fr_shortname": "Cameroun (le)",
        "iso_alpha2": "CM",
        "iso_alpha3": "CMR",
        "iso_numeric": 120,
    },
    {
        "label": "Canada",
        "iso_en_shortname": "Canada",
        "iso_fr_shortname": "Canada (le)",
        "iso_alpha2": "CA",
        "iso_alpha3": "CAN",
        "iso_numeric": 124,
    },
    {
        "label": "Cayman Islands",
        "iso_en_shortname": "Cayman Islands (the)",
        "iso_fr_shortname": "Caïmans (les Îles)",
        "iso_alpha2": "KY",
        "iso_alpha3": "CYM",
        "iso_numeric": 136,
    },
    {
        "label": "Central African Republic",
        "iso_en_shortname": "Central African Republic (the)",
        "iso_fr_shortname": "République centrafricaine (la)",
        "iso_alpha2": "CF",
        "iso_alpha3": "CAF",
        "iso_numeric": 140,
    },
    {
        "label": "Chad",
        "iso_en_shortname": "Chad",
        "iso_fr_shortname": "Tchad (le)",
        "iso_alpha2": "TD",
        "iso_alpha3": "TCD",
        "iso_numeric": 148,
    },
    {
        "label": "Chile",
        "iso_en_shortname": "Chile",
        "iso_fr_shortname": "Chili (le)",
        "iso_alpha2": "CL",
        "iso_alpha3": "CHL",
        "iso_numeric": 152,
    },
    {
        "label": "China",
        "iso_en_shortname": "China",
        "iso_fr_shortname": "Chine (la)",
        "iso_alpha2": "CN",
        "iso_alpha3": "CHN",
        "iso_numeric": 156,
    },
    {
        "label": "Christmas Island",
        "iso_en_shortname": "Christmas Island",
        "iso_fr_shortname": "Christmas (l'Île)",
        "iso_alpha2": "CX",
        "iso_alpha3": "CXR",
        "iso_numeric": 162,
    },
    {
        "label": "Cocos (Keeling) Islands",
        "iso_en_shortname": "Cocos (Keeling) Islands (the)",
        "iso_fr_shortname": "Cocos (les Îles)/ Keeling (les Îles)",
        "iso_alpha2": "CC",
        "iso_alpha3": "CCK",
        "iso_numeric": 166,
    },
    {
        "label": "Colombia",
        "iso_en_shortname": "Colombia",
        "iso_fr_shortname": "Colombie (la)",
        "iso_alpha2": "CO",
        "iso_alpha3": "COL",
        "iso_numeric": 170,
    },
    {
        "label": "Comoros",
        "iso_en_shortname": "Comoros (the)",
        "iso_fr_shortname": "Comores (les)",
        "iso_alpha2": "KM",
        "iso_alpha3": "COM",
        "iso_numeric": 174,
    },
    {
        "label": "Democratic Republic of the Congo",
        "iso_en_shortname": "Congo (the Democratic Republic of the)",
        "iso_fr_shortname": "Congo (la République démocratique du)",
        "iso_alpha2": "CD",
        "iso_alpha3": "COD",
        "iso_numeric": 180,
    },
    {
        "label": "Republic of the Congo",
        "iso_en_shortname": "Congo (the)",
        "iso_fr_shortname": "Congo (le)",
        "iso_alpha2": "CG",
        "iso_alpha3": "COG",
        "iso_numeric": 178,
    },
    {
        "label": "Cook Islands",
        "iso_en_shortname": "Cook Islands (the)",
        "iso_fr_shortname": "Cook (les Îles)",
        "iso_alpha2": "CK",
        "iso_alpha3": "COK",
        "iso_numeric": 184,
    },
    {
        "label": "Costa Rica",
        "iso_en_shortname": "Costa Rica",
        "iso_fr_shortname": "Costa Rica (le)",
        "iso_alpha2": "CR",
        "iso_alpha3": "CRI",
        "iso_numeric": 188,
    },
    {
        "label": "Croatia",
        "iso_en_shortname": "Croatia",
        "iso_fr_shortname": "Croatie (la)",
        "iso_alpha2": "HR",
        "iso_alpha3": "HRV",
        "iso_numeric": 191,
    },
    {
        "label": "Cuba",
        "iso_en_shortname": "Cuba",
        "iso_fr_shortname": "Cuba",
        "iso_alpha2": "CU",
        "iso_alpha3": "CUB",
        "iso_numeric": 192,
    },
    {
        "label": "Curaçao",
        "iso_en_shortname": "Curaçao",
        "iso_fr_shortname": "Curaçao",
        "iso_alpha2": "CW",
        "iso_alpha3": "CUW",
        "iso_numeric": 531,
    },
    {
        "label": "Cyprus",
        "iso_en_shortname": "Cyprus",
        "iso_fr_shortname": "Chypre",
        "iso_alpha2": "CY",
        "iso_alpha3": "CYP",
        "iso_numeric": 196,
    },
    {
        "label": "Czechia",
        "iso_en_shortname": "Czechia",
        "iso_fr_shortname": "Tchéquie (la)",
        "iso_alpha2": "CZ",
        "iso_alpha3": "CZE",
        "iso_numeric": 203,
    },
    {
        "label": "Côte d'Ivoire",
        "iso_en_shortname": "Côte d'Ivoire",
        "iso_fr_shortname": "Côte d'Ivoire (la)",
        "iso_alpha2": "CI",
        "iso_alpha3": "CIV",
        "iso_numeric": 384,
    },
    {
        "label": "Denmark",
        "iso_en_shortname": "Denmark",
        "iso_fr_shortname": "Danemark (le)",
        "iso_alpha2": "DK",
        "iso_alpha3": "DNK",
        "iso_numeric": 208,
    },
    {
        "label": "Djibouti",
        "iso_en_shortname": "Djibouti",
        "iso_fr_shortname": "Djibouti",
        "iso_alpha2": "DJ",
        "iso_alpha3": "DJI",
        "iso_numeric": 262,
    },
    {
        "label": "Dominica",
        "iso_en_shortname": "Dominica",
        "iso_fr_shortname": "Dominique (la)",
        "iso_alpha2": "DM",
        "iso_alpha3": "DMA",
        "iso_numeric": 212,
    },
    {
        "label": "Dominican Republic",
        "iso_en_shortname": "Dominican Republic (the)",
        "iso_fr_shortname": "dominicaine (la République)",
        "iso_alpha2": "DO",
        "iso_alpha3": "DOM",
        "iso_numeric": 214,
    },
    {
        "label": "Ecuador",
        "iso_en_shortname": "Ecuador",
        "iso_fr_shortname": "Équateur (l')",
        "iso_alpha2": "EC",
        "iso_alpha3": "ECU",
        "iso_numeric": 218,
    },
    {
        "label": "Egypt",
        "iso_en_shortname": "Egypt",
        "iso_fr_shortname": "Égypte (l')",
        "iso_alpha2": "EG",
        "iso_alpha3": "EGY",
        "iso_numeric": 818,
    },
    {
        "label": "El Salvador",
        "iso_en_shortname": "El Salvador",
        "iso_fr_shortname": "El Salvador",
        "iso_alpha2": "SV",
        "iso_alpha3": "SLV",
        "iso_numeric": 222,
    },
    {
        "label": "Equatorial Guinea",
        "iso_en_shortname": "Equatorial Guinea",
        "iso_fr_shortname": "Guinée équatoriale (la)",
        "iso_alpha2": "GQ",
        "iso_alpha3": "GNQ",
        "iso_numeric": 226,
    },
    {
        "label": "Eritrea",
        "iso_en_shortname": "Eritrea",
        "iso_fr_shortname": "Érythrée (l')",
        "iso_alpha2": "ER",
        "iso_alpha3": "ERI",
        "iso_numeric": 232,
    },
    {
        "label": "Estonia",
        "iso_en_shortname": "Estonia",
        "iso_fr_shortname": "Estonie (l')",
        "iso_alpha2": "EE",
        "iso_alpha3": "EST",
        "iso_numeric": 233,
    },
    {
        "label": "Eswatini",
        "iso_en_shortname": "Eswatini",
        "iso_fr_shortname": "Eswatini (l')",
        "iso_alpha2": "SZ",
        "iso_alpha3": "SWZ",
        "iso_numeric": 748,
    },
    {
        "label": "Ethiopia",
        "iso_en_shortname": "Ethiopia",
        "iso_fr_shortname": "Éthiopie (l')",
        "iso_alpha2": "ET",
        "iso_alpha3": "ETH",
        "iso_numeric": 231,
    },
    {
        "label": "Falkland Islands",
        "iso_en_shortname": "Falkland Islands (the) [Malvinas]",
        "iso_fr_shortname": "Falkland (les Îles)/Malouines (les Îles)",
        "iso_alpha2": "FK",
        "iso_alpha3": "FLK",
        "iso_numeric": 238,
    },
    {
        "label": "Faroe Islands",
        "iso_en_shortname": "Faroe Islands (the)",
        "iso_fr_shortname": "Féroé (les Îles)",
        "iso_alpha2": "FO",
        "iso_alpha3": "FRO",
        "iso_numeric": 234,
    },
    {
        "label": "Fiji",
        "iso_en_shortname": "Fiji",
        "iso_fr_shortname": "Fidji (les)",
        "iso_alpha2": "FJ",
        "iso_alpha3": "FJI",
        "iso_numeric": 242,
    },
    {
        "label": "Finland",
        "iso_en_shortname": "Finland",
        "iso_fr_shortname": "Finlande (la)",
        "iso_alpha2": "FI",
        "iso_alpha3": "FIN",
        "iso_numeric": 246,
    },
    {
        "label": "France",
        "iso_en_shortname": "France",
        "iso_fr_shortname": "France (la)",
        "iso_alpha2": "FR",
        "iso_alpha3": "FRA",
        "iso_numeric": 250,
    },
    {
        "label": "French Guiana",
        "iso_en_shortname": "French Guiana",
        "iso_fr_shortname": "Guyane française (la)",
        "iso_alpha2": "GF",
        "iso_alpha3": "GUF",
        "iso_numeric": 254,
    },
    {
        "label": "French Polynesia",
        "iso_en_shortname": "French Polynesia",
        "iso_fr_shortname": "Polynésie française (la)",
        "iso_alpha2": "PF",
        "iso_alpha3": "PYF",
        "iso_numeric": 258,
    },
    {
        "label": "French Southern and Antarctic Lands",
        "iso_en_shortname": "French Southern Territories (the)",
        "iso_fr_shortname": "Terres australes françaises (les)",
        "iso_alpha2": "TF",
        "iso_alpha3": "ATF",
        "iso_numeric": 260,
    },
    {
        "label": "Gabon",
        "iso_en_shortname": "Gabon",
        "iso_fr_shortname": "Gabon (le)",
        "iso_alpha2": "GA",
        "iso_alpha3": "GAB",
        "iso_numeric": 266,
    },
    {
        "label": "The Gambia",
        "iso_en_shortname": "Gambia (the)",
        "iso_fr_shortname": "Gambie (la)",
        "iso_alpha2": "GM",
        "iso_alpha3": "GMB",
        "iso_numeric": 270,
    },
    {
        "label": "Georgia",
        "iso_en_shortname": "Georgia",
        "iso_fr_shortname": "Géorgie (la)",
        "iso_alpha2": "GE",
        "iso_alpha3": "GEO",
        "iso_numeric": 268,
    },
    {
        "label": "Germany",
        "iso_en_shortname": "Germany",
        "iso_fr_shortname": "Allemagne (l')",
        "iso_alpha2": "DE",
        "iso_alpha3": "DEU",
        "iso_numeric": 276,
    },
    {
        "label": "Ghana",
        "iso_en_shortname": "Ghana",
        "iso_fr_shortname": "Ghana (le)",
        "iso_alpha2": "GH",
        "iso_alpha3": "GHA",
        "iso_numeric": 288,
    },
    {
        "label": "Gibraltar",
        "iso_en_shortname": "Gibraltar",
        "iso_fr_shortname": "Gibraltar",
        "iso_alpha2": "GI",
        "iso_alpha3": "GIB",
        "iso_numeric": 292,
    },
    {
        "label": "Greece",
        "iso_en_shortname": "Greece",
        "iso_fr_shortname": "Grèce (la)",
        "iso_alpha2": "GR",
        "iso_alpha3": "GRC",
        "iso_numeric": 300,
    },
    {
        "label": "Greenland",
        "iso_en_shortname": "Greenland",
        "iso_fr_shortname": "Groenland (le)",
        "iso_alpha2": "GL",
        "iso_alpha3": "GRL",
        "iso_numeric": 304,
    },
    {
        "label": "Grenada",
        "iso_en_shortname": "Grenada",
        "iso_fr_shortname": "Grenade (la)",
        "iso_alpha2": "GD",
        "iso_alpha3": "GRD",
        "iso_numeric": 308,
    },
    {
        "label": "Guadeloupe",
        "iso_en_shortname": "Guadeloupe",
        "iso_fr_shortname": "Guadeloupe (la)",
        "iso_alpha2": "GP",
        "iso_alpha3": "GLP",
        "iso_numeric": 312,
    },
    {
        "label": "Guam",
        "iso_en_shortname": "Guam",
        "iso_fr_shortname": "Guam",
        "iso_alpha2": "GU",
        "iso_alpha3": "GUM",
        "iso_numeric": 316,
    },
    {
        "label": "Guatemala",
        "iso_en_shortname": "Guatemala",
        "iso_fr_shortname": "Guatemala (le)",
        "iso_alpha2": "GT",
        "iso_alpha3": "GTM",
        "iso_numeric": 320,
    },
    {
        "label": "Guernsey",
        "iso_en_shortname": "Guernsey",
        "iso_fr_shortname": "Guernesey",
        "iso_alpha2": "GG",
        "iso_alpha3": "GGY",
        "iso_numeric": 831,
    },
    {
        "label": "Guinea",
        "iso_en_shortname": "Guinea",
        "iso_fr_shortname": "Guinée (la)",
        "iso_alpha2": "GN",
        "iso_alpha3": "GIN",
        "iso_numeric": 324,
    },
    {
        "label": "Guinea-Bissau",
        "iso_en_shortname": "Guinea-Bissau",
        "iso_fr_shortname": "Guinée-Bissau (la)",
        "iso_alpha2": "GW",
        "iso_alpha3": "GNB",
        "iso_numeric": 624,
    },
    {
        "label": "Guyana",
        "iso_en_shortname": "Guyana",
        "iso_fr_shortname": "Guyana (le)",
        "iso_alpha2": "GY",
        "iso_alpha3": "GUY",
        "iso_numeric": 328,
    },
    {
        "label": "Haiti",
        "iso_en_shortname": "Haiti",
        "iso_fr_shortname": "Haïti",
        "iso_alpha2": "HT",
        "iso_alpha3": "HTI",
        "iso_numeric": 332,
    },
    {
        "label": "Heard Island and McDonald Islands",
        "iso_en_shortname": "Heard Island and McDonald Islands",
        "iso_fr_shortname": "Heard-et-MacDonald (l'Île)",
        "iso_alpha2": "HM",
        "iso_alpha3": "HMD",
        "iso_numeric": 334,
    },
    {
        "label": "Holy See",
        "iso_en_shortname": "Holy See (the)",
        "iso_fr_shortname": "Saint-Siège (le)",
        "iso_alpha2": "VA",
        "iso_alpha3": "VAT",
        "iso_numeric": 336,
    },
    {
        "label": "Honduras",
        "iso_en_shortname": "Honduras",
        "iso_fr_shortname": "Honduras (le)",
        "iso_alpha2": "HN",
        "iso_alpha3": "HND",
        "iso_numeric": 340,
    },
    {
        "label": "Hong Kong",
        "iso_en_shortname": "Hong Kong",
        "iso_fr_shortname": "Hong Kong",
        "iso_alpha2": "HK",
        "iso_alpha3": "HKG",
        "iso_numeric": 344,
    },
    {
        "label": "Hungary",
        "iso_en_shortname": "Hungary",
        "iso_fr_shortname": "Hongrie (la)",
        "iso_alpha2": "HU",
        "iso_alpha3": "HUN",
        "iso_numeric": 348,
    },
    {
        "label": "Iceland",
        "iso_en_shortname": "Iceland",
        "iso_fr_shortname": "Islande (l')",
        "iso_alpha2": "IS",
        "iso_alpha3": "ISL",
        "iso_numeric": 352,
    },
    {
        "label": "India",
        "iso_en_shortname": "India",
        "iso_fr_shortname": "Inde (l')",
        "iso_alpha2": "IN",
        "iso_alpha3": "IND",
        "iso_numeric": 356,
    },
    {
        "label": "Indonesia",
        "iso_en_shortname": "Indonesia",
        "iso_fr_shortname": "Indonésie (l')",
        "iso_alpha2": "ID",
        "iso_alpha3": "IDN",
        "iso_numeric": 360,
    },
    {
        "label": "Iran",
        "iso_en_shortname": "Iran (Islamic Republic of)",
        "iso_fr_shortname": "Iran (République Islamique d')",
        "iso_alpha2": "IR",
        "iso_alpha3": "IRN",
        "iso_numeric": 364,
    },
    {
        "label": "Iraq",
        "iso_en_shortname": "Iraq",
        "iso_fr_shortname": "Iraq (l')",
        "iso_alpha2": "IQ",
        "iso_alpha3": "IRQ",
        "iso_numeric": 368,
    },
    {
        "label": "Ireland",
        "iso_en_shortname": "Ireland",
        "iso_fr_shortname": "Irlande (l')",
        "iso_alpha2": "IE",
        "iso_alpha3": "IRL",
        "iso_numeric": 372,
    },
    {
        "label": "Isle of Man",
        "iso_en_shortname": "Isle of Man",
        "iso_fr_shortname": "Île de Man",
        "iso_alpha2": "IM",
        "iso_alpha3": "IMN",
        "iso_numeric": 833,
    },
    {
        "label": "Israel",
        "iso_en_shortname": "Israel",
        "iso_fr_shortname": "Israël",
        "iso_alpha2": "IL",
        "iso_alpha3": "ISR",
        "iso_numeric": 376,
    },
    {
        "label": "Italy",
        "iso_en_shortname": "Italy",
        "iso_fr_shortname": "Italie (l')",
        "iso_alpha2": "IT",
        "iso_alpha3": "ITA",
        "iso_numeric": 380,
    },
    {
        "label": "Jamaica",
        "iso_en_shortname": "Jamaica",
        "iso_fr_shortname": "Jamaïque (la)",
        "iso_alpha2": "JM",
        "iso_alpha3": "JAM",
        "iso_numeric": 388,
    },
    {
        "label": "Japan",
        "iso_en_shortname": "Japan",
        "iso_fr_shortname": "Japon (le)",
        "iso_alpha2": "JP",
        "iso_alpha3": "JPN",
        "iso_numeric": 392,
    },
    {
        "label": "Jersey",
        "iso_en_shortname": "Jersey",
        "iso_fr_shortname": "Jersey",
        "iso_alpha2": "JE",
        "iso_alpha3": "JEY",
        "iso_numeric": 832,
    },
    {
        "label": "Jordan",
        "iso_en_shortname": "Jordan",
        "iso_fr_shortname": "Jordanie (la)",
        "iso_alpha2": "JO",
        "iso_alpha3": "JOR",
        "iso_numeric": 400,
    },
    {
        "label": "Kazakhstan",
        "iso_en_shortname": "Kazakhstan",
        "iso_fr_shortname": "Kazakhstan (le)",
        "iso_alpha2": "KZ",
        "iso_alpha3": "KAZ",
        "iso_numeric": 398,
    },
    {
        "label": "Kenya",
        "iso_en_shortname": "Kenya",
        "iso_fr_shortname": "Kenya (le)",
        "iso_alpha2": "KE",
        "iso_alpha3": "KEN",
        "iso_numeric": 404,
    },
    {
        "label": "Kiribati",
        "iso_en_shortname": "Kiribati",
        "iso_fr_shortname": "Kiribati",
        "iso_alpha2": "KI",
        "iso_alpha3": "KIR",
        "iso_numeric": 296,
    },
    {
        "label": "North Korea",
        "iso_en_shortname": "Korea (the Democratic People's Republic of)",
        "iso_fr_shortname": "Corée (la République populaire démocratique de)",
        "iso_alpha2": "KP",
        "iso_alpha3": "PRK",
        "iso_numeric": 408,
    },
    {
        "label": "South Korea",
        "iso_en_shortname": "Korea (the Republic of)",
        "iso_fr_shortname": "Corée (la République de)",
        "iso_alpha2": "KR",
        "iso_alpha3": "KOR",
        "iso_numeric": 410,
    },
    {
        "label": "Kuwait",
        "iso_en_shortname": "Kuwait",
        "iso_fr_shortname": "Koweït (le)",
        "iso_alpha2": "KW",
        "iso_alpha3": "KWT",
        "iso_numeric": 414,
    },
    {
        "label": "Kyrgyzstan",
        "iso_en_shortname": "Kyrgyzstan",
        "iso_fr_shortname": "Kirghizistan (le)",
        "iso_alpha2": "KG",
        "iso_alpha3": "KGZ",
        "iso_numeric": 417,
    },
    {
        "label": "Laos",
        "iso_en_shortname": "Lao People's Democratic Republic (the)",
        "iso_fr_shortname": "Lao (la République démocratique populaire)",
        "iso_alpha2": "LA",
        "iso_alpha3": "LAO",
        "iso_numeric": 418,
    },
    {
        "label": "Latvia",
        "iso_en_shortname": "Latvia",
        "iso_fr_shortname": "Lettonie (la)",
        "iso_alpha2": "LV",
        "iso_alpha3": "LVA",
        "iso_numeric": 428,
    },
    {
        "label": "Lebanon",
        "iso_en_shortname": "Lebanon",
        "iso_fr_shortname": "Liban (le)",
        "iso_alpha2": "LB",
        "iso_alpha3": "LBN",
        "iso_numeric": 422,
    },
    {
        "label": "Lesotho",
        "iso_en_shortname": "Lesotho",
        "iso_fr_shortname": "Lesotho (le)",
        "iso_alpha2": "LS",
        "iso_alpha3": "LSO",
        "iso_numeric": 426,
    },
    {
        "label": "Liberia",
        "iso_en_shortname": "Liberia",
        "iso_fr_shortname": "Libéria (le)",
        "iso_alpha2": "LR",
        "iso_alpha3": "LBR",
        "iso_numeric": 430,
    },
    {
        "label": "Libya",
        "iso_en_shortname": "Libya",
        "iso_fr_shortname": "Libye (la)",
        "iso_alpha2": "LY",
        "iso_alpha3": "LBY",
        "iso_numeric": 434,
    },
    {
        "label": "Liechtenstein",
        "iso_en_shortname": "Liechtenstein",
        "iso_fr_shortname": "Liechtenstein (le)",
        "iso_alpha2": "LI",
        "iso_alpha3": "LIE",
        "iso_numeric": 438,
    },
    {
        "label": "Lithuania",
        "iso_en_shortname": "Lithuania",
        "iso_fr_shortname": "Lituanie (la)",
        "iso_alpha2": "LT",
        "iso_alpha3": "LTU",
        "iso_numeric": 440,
    },
    {
        "label": "Luxembourg",
        "iso_en_shortname": "Luxembourg",
        "iso_fr_shortname": "Luxembourg (le)",
        "iso_alpha2": "LU",
        "iso_alpha3": "LUX",
        "iso_numeric": 442,
    },
    {
        "label": "Macao",
        "iso_en_shortname": "Macao",
        "iso_fr_shortname": "Macao",
        "iso_alpha2": "MO",
        "iso_alpha3": "MAC",
        "iso_numeric": 446,
    },
    {
        "label": "Madagascar",
        "iso_en_shortname": "Madagascar",
        "iso_fr_shortname": "Madagascar",
        "iso_alpha2": "MG",
        "iso_alpha3": "MDG",
        "iso_numeric": 450,
    },
    {
        "label": "Malawi",
        "iso_en_shortname": "Malawi",
        "iso_fr_shortname": "Malawi (le)",
        "iso_alpha2": "MW",
        "iso_alpha3": "MWI",
        "iso_numeric": 454,
    },
    {
        "label": "Malaysia",
        "iso_en_shortname": "Malaysia",
        "iso_fr_shortname": "Malaisie (la)",
        "iso_alpha2": "MY",
        "iso_alpha3": "MYS",
        "iso_numeric": 458,
    },
    {
        "label": "Maldives",
        "iso_en_shortname": "Maldives",
        "iso_fr_shortname": "Maldives (les)",
        "iso_alpha2": "MV",
        "iso_alpha3": "MDV",
        "iso_numeric": 462,
    },
    {
        "label": "Mali",
        "iso_en_shortname": "Mali",
        "iso_fr_shortname": "Mali (le)",
        "iso_alpha2": "ML",
        "iso_alpha3": "MLI",
        "iso_numeric": 466,
    },
    {
        "label": "Malta",
        "iso_en_shortname": "Malta",
        "iso_fr_shortname": "Malte",
        "iso_alpha2": "MT",
        "iso_alpha3": "MLT",
        "iso_numeric": 470,
    },
    {
        "label": "Marshall Islands",
        "iso_en_shortname": "Marshall Islands (the)",
        "iso_fr_shortname": "Marshall (les Îles)",
        "iso_alpha2": "MH",
        "iso_alpha3": "MHL",
        "iso_numeric": 584,
    },
    {
        "label": "Martinique",
        "iso_en_shortname": "Martinique",
        "iso_fr_shortname": "Martinique (la)",
        "iso_alpha2": "MQ",
        "iso_alpha3": "MTQ",
        "iso_numeric": 474,
    },
    {
        "label": "Mauritania",
        "iso_en_shortname": "Mauritania",
        "iso_fr_shortname": "Mauritanie (la)",
        "iso_alpha2": "MR",
        "iso_alpha3": "MRT",
        "iso_numeric": 478,
    },
    {
        "label": "Mauritius",
        "iso_en_shortname": "Mauritius",
        "iso_fr_shortname": "Maurice",
        "iso_alpha2": "MU",
        "iso_alpha3": "MUS",
        "iso_numeric": 480,
    },
    {
        "label": "Mayotte",
        "iso_en_shortname": "Mayotte",
        "iso_fr_shortname": "Mayotte",
        "iso_alpha2": "YT",
        "iso_alpha3": "MYT",
        "iso_numeric": 175,
    },
    {
        "label": "Mexico",
        "iso_en_shortname": "Mexico",
        "iso_fr_shortname": "Mexique (le)",
        "iso_alpha2": "MX",
        "iso_alpha3": "MEX",
        "iso_numeric": 484,
    },
    {
        "label": "Micronesia",
        "iso_en_shortname": "Micronesia (Federated States of)",
        "iso_fr_shortname": "Micronésie (États fédérés de)",
        "iso_alpha2": "FM",
        "iso_alpha3": "FSM",
        "iso_numeric": 583,
    },
    {
        "label": "Moldova",
        "iso_en_shortname": "Moldova (the Republic of)",
        "iso_fr_shortname": "Moldova (la République de)",
        "iso_alpha2": "MD",
        "iso_alpha3": "MDA",
        "iso_numeric": 498,
    },
    {
        "label": "Monaco",
        "iso_en_shortname": "Monaco",
        "iso_fr_shortname": "Monaco",
        "iso_alpha2": "MC",
        "iso_alpha3": "MCO",
        "iso_numeric": 492,
    },
    {
        "label": "Mongolia",
        "iso_en_shortname": "Mongolia",
        "iso_fr_shortname": "Mongolie (la)",
        "iso_alpha2": "MN",
        "iso_alpha3": "MNG",
        "iso_numeric": 496,
    },
    {
        "label": "Montenegro",
        "iso_en_shortname": "Montenegro",
        "iso_fr_shortname": "Monténégro (le)",
        "iso_alpha2": "ME",
        "iso_alpha3": "MNE",
        "iso_numeric": 499,
    },
    {
        "label": "Montserrat",
        "iso_en_shortname": "Montserrat",
        "iso_fr_shortname": "Montserrat",
        "iso_alpha2": "MS",
        "iso_alpha3": "MSR",
        "iso_numeric": 500,
    },
    {
        "label": "Morocco",
        "iso_en_shortname": "Morocco",
        "iso_fr_shortname": "Maroc (le)",
        "iso_alpha2": "MA",
        "iso_alpha3": "MAR",
        "iso_numeric": 504,
    },
    {
        "label": "Mozambique",
        "iso_en_shortname": "Mozambique",
        "iso_fr_shortname": "Mozambique (le)",
        "iso_alpha2": "MZ",
        "iso_alpha3": "MOZ",
        "iso_numeric": 508,
    },
    {
        "label": "Myanmar",
        "iso_en_shortname": "Myanmar",
        "iso_fr_shortname": "Myanmar (le)",
        "iso_alpha2": "MM",
        "iso_alpha3": "MMR",
        "iso_numeric": 104,
    },
    {
        "label": "Namibia",
        "iso_en_shortname": "Namibia",
        "iso_fr_shortname": "Namibie (la)",
        "iso_alpha2": "NA",
        "iso_alpha3": "NAM",
        "iso_numeric": 516,
    },
    {
        "label": "Nauru",
        "iso_en_shortname": "Nauru",
        "iso_fr_shortname": "Nauru",
        "iso_alpha2": "NR",
        "iso_alpha3": "NRU",
        "iso_numeric": 520,
    },
    {
        "label": "Nepal",
        "iso_en_shortname": "Nepal",
        "iso_fr_shortname": "Népal (le)",
        "iso_alpha2": "NP",
        "iso_alpha3": "NPL",
        "iso_numeric": 524,
    },
    {
        "label": "Netherlands",
        "iso_en_shortname": "Netherlands (Kingdom of the)",
        "iso_fr_shortname": "Pays-Bas (Royaume des)",
        "iso_alpha2": "NL",
        "iso_alpha3": "NLD",
        "iso_numeric": 528,
    },
    {
        "label": "New Caledonia",
        "iso_en_shortname": "New Caledonia",
        "iso_fr_shortname": "Nouvelle-Calédonie (la)",
        "iso_alpha2": "NC",
        "iso_alpha3": "NCL",
        "iso_numeric": 540,
    },
    {
        "label": "New Zealand",
        "iso_en_shortname": "New Zealand",
        "iso_fr_shortname": "Nouvelle-Zélande (la)",
        "iso_alpha2": "NZ",
        "iso_alpha3": "NZL",
        "iso_numeric": 554,
    },
    {
        "label": "Nicaragua",
        "iso_en_shortname": "Nicaragua",
        "iso_fr_shortname": "Nicaragua (le)",
        "iso_alpha2": "NI",
        "iso_alpha3": "NIC",
        "iso_numeric": 558,
    },
    {
        "label": "Niger",
        "iso_en_shortname": "Niger (the)",
        "iso_fr_shortname": "Niger (le)",
        "iso_alpha2": "NE",
        "iso_alpha3": "NER",
        "iso_numeric": 562,
    },
    {
        "label": "Nigeria",
        "iso_en_shortname": "Nigeria",
        "iso_fr_shortname": "Nigéria (le)",
        "iso_alpha2": "NG",
        "iso_alpha3": "NGA",
        "iso_numeric": 566,
    },
    {
        "label": "Niue",
        "iso_en_shortname": "Niue",
        "iso_fr_shortname": "Niue",
        "iso_alpha2": "NU",
        "iso_alpha3": "NIU",
        "iso_numeric": 570,
    },
    {
        "label": "Norfolk Island",
        "iso_en_shortname": "Norfolk Island",
        "iso_fr_shortname": "Norfolk (l'Île)",
        "iso_alpha2": "NF",
        "iso_alpha3": "NFK",
        "iso_numeric": 574,
    },
    {
        "label": "North Macedonia",
        "iso_en_shortname": "North Macedonia",
        "iso_fr_shortname": "Macédoine du Nord (la)",
        "iso_alpha2": "MK",
        "iso_alpha3": "MKD",
        "iso_numeric": 807,
    },
    {
        "label": "Northern Mariana Islands",
        "iso_en_shortname": "Northern Mariana Islands (the)",
        "iso_fr_shortname": "Mariannes du Nord (les Îles)",
        "iso_alpha2": "MP",
        "iso_alpha3": "MNP",
        "iso_numeric": 580,
    },
    {
        "label": "Norway",
        "iso_en_shortname": "Norway",
        "iso_fr_shortname": "Norvège (la)",
        "iso_alpha2": "NO",
        "iso_alpha3": "NOR",
        "iso_numeric": 578,
    },
    {
        "label": "Oman",
        "iso_en_shortname": "Oman",
        "iso_fr_shortname": "Oman",
        "iso_alpha2": "OM",
        "iso_alpha3": "OMN",
        "iso_numeric": 512,
    },
    {
        "label": "Pakistan",
        "iso_en_shortname": "Pakistan",
        "iso_fr_shortname": "Pakistan (le)",
        "iso_alpha2": "PK",
        "iso_alpha3": "PAK",
        "iso_numeric": 586,
    },
    {
        "label": "Palau",
        "iso_en_shortname": "Palau",
        "iso_fr_shortname": "Palaos (les)",
        "iso_alpha2": "PW",
        "iso_alpha3": "PLW",
        "iso_numeric": 585,
    },
    {
        "label": "Palestine",
        "iso_en_shortname": "Palestine, State of",
        "iso_fr_shortname": "Palestine, État de",
        "iso_alpha2": "PS",
        "iso_alpha3": "PSE",
        "iso_numeric": 275,
    },
    {
        "label": "Panama",
        "iso_en_shortname": "Panama",
        "iso_fr_shortname": "Panama (le)",
        "iso_alpha2": "PA",
        "iso_alpha3": "PAN",
        "iso_numeric": 591,
    },
    {
        "label": "Papua New Guinea",
        "iso_en_shortname": "Papua New Guinea",
        "iso_fr_shortname": "Papouasie-Nouvelle-Guinée (la)",
        "iso_alpha2": "PG",
        "iso_alpha3": "PNG",
        "iso_numeric": 598,
    },
    {
        "label": "Paraguay",
        "iso_en_shortname": "Paraguay",
        "iso_fr_shortname": "Paraguay (le)",
        "iso_alpha2": "PY",
        "iso_alpha3": "PRY",
        "iso_numeric": 600,
    },
    {
        "label": "Peru",
        "iso_en_shortname": "Peru",
        "iso_fr_shortname": "Pérou (le)",
        "iso_alpha2": "PE",
        "iso_alpha3": "PER",
        "iso_numeric": 604,
    },
    {
        "label": "Philippines",
        "iso_en_shortname": "Philippines (the)",
        "iso_fr_shortname": "Philippines (les)",
        "iso_alpha2": "PH",
        "iso_alpha3": "PHL",
        "iso_numeric": 608,
    },
    {
        "label": "Pitcairn",
        "iso_en_shortname": "Pitcairn",
        "iso_fr_shortname": "Pitcairn",
        "iso_alpha2": "PN",
        "iso_alpha3": "PCN",
        "iso_numeric": 612,
    },
    {
        "label": "Poland",
        "iso_en_shortname": "Poland",
        "iso_fr_shortname": "Pologne (la)",
        "iso_alpha2": "PL",
        "iso_alpha3": "POL",
        "iso_numeric": 616,
    },
    {
        "label": "Portugal",
        "iso_en_shortname": "Portugal",
        "iso_fr_shortname": "Portugal (le)",
        "iso_alpha2": "PT",
        "iso_alpha3": "PRT",
        "iso_numeric": 620,
    },
    {
        "label": "Puerto Rico",
        "iso_en_shortname": "Puerto Rico",
        "iso_fr_shortname": "Porto Rico",
        "iso_alpha2": "PR",
        "iso_alpha3": "PRI",
        "iso_numeric": 630,
    },
    {
        "label": "Qatar",
        "iso_en_shortname": "Qatar",
        "iso_fr_shortname": "Qatar (le)",
        "iso_alpha2": "QA",
        "iso_alpha3": "QAT",
        "iso_numeric": 634,
    },
    {
        "label": "Romania",
        "iso_en_shortname": "Romania",
        "iso_fr_shortname": "Roumanie (la)",
        "iso_alpha2": "RO",
        "iso_alpha3": "ROU",
        "iso_numeric": 642,
    },
    {
        "label": "Russian Federation",
        "iso_en_shortname": "Russian Federation (the)",
        "iso_fr_shortname": "Russie (la Fédération de)",
        "iso_alpha2": "RU",
        "iso_alpha3": "RUS",
        "iso_numeric": 643,
    },
    {
        "label": "Rwanda",
        "iso_en_shortname": "Rwanda",
        "iso_fr_shortname": "Rwanda (le)",
        "iso_alpha2": "RW",
        "iso_alpha3": "RWA",
        "iso_numeric": 646,
    },
    {
        "label": "Réunion",
        "iso_en_shortname": "Réunion",
        "iso_fr_shortname": "Réunion (La)",
        "iso_alpha2": "RE",
        "iso_alpha3": "REU",
        "iso_numeric": 638,
    },
    {
        "label": "Saint Barthélemy",
        "iso_en_shortname": "Saint Barthélemy",
        "iso_fr_shortname": "Saint-Barthélemy",
        "iso_alpha2": "BL",
        "iso_alpha3": "BLM",
        "iso_numeric": 652,
    },
    {
        "label": "Saint Helena, Ascension and Tristan da Cunha",
        "iso_en_shortname": "Saint Helena, Ascension and Tristan da Cunha",
        "iso_fr_shortname": "Sainte-Hélène, Ascension et Tristan da Cunha",
        "iso_alpha2": "SH",
        "iso_alpha3": "SHN",
        "iso_numeric": 654,
    },
    {
        "label": "Saint Kitts and Nevis",
        "iso_en_shortname": "Saint Kitts and Nevis",
        "iso_fr_shortname": "Saint-Kitts-et-Nevis",
        "iso_alpha2": "KN",
        "iso_alpha3": "KNA",
        "iso_numeric": 659,
    },
    {
        "label": "Saint Lucia",
        "iso_en_shortname": "Saint Lucia",
        "iso_fr_shortname": "Sainte-Lucie",
        "iso_alpha2": "LC",
        "iso_alpha3": "LCA",
        "iso_numeric": 662,
    },
    {
        "label": "Saint Martin",
        "iso_en_shortname": "Saint Martin (French part)",
        "iso_fr_shortname": "Saint-Martin (partie française)",
        "iso_alpha2": "MF",
        "iso_alpha3": "MAF",
        "iso_numeric": 663,
    },
    {
        "label": "Saint Pierre and Miquelon",
        "iso_en_shortname": "Saint Pierre and Miquelon",
        "iso_fr_shortname": "Saint-Pierre-et-Miquelon",
        "iso_alpha2": "PM",
        "iso_alpha3": "SPM",
        "iso_numeric": 666,
    },
    {
        "label": "Saint Vincent and the Grenadines",
        "iso_en_shortname": "Saint Vincent and the Grenadines",
        "iso_fr_shortname": "Saint-Vincent-et-les Grenadines",
        "iso_alpha2": "VC",
        "iso_alpha3": "VCT",
        "iso_numeric": 670,
    },
    {
        "label": "Samoa",
        "iso_en_shortname": "Samoa",
        "iso_fr_shortname": "Samoa (le)",
        "iso_alpha2": "WS",
        "iso_alpha3": "WSM",
        "iso_numeric": 882,
    },
    {
        "label": "San Marino",
        "iso_en_shortname": "San Marino",
        "iso_fr_shortname": "Saint-Marin",
        "iso_alpha2": "SM",
        "iso_alpha3": "SMR",
        "iso_numeric": 674,
    },
    {
        "label": "São Tomé and Príncipe",
        "iso_en_shortname": "Sao Tome and Principe",
        "iso_fr_shortname": "Sao Tomé-et-Principe",
        "iso_alpha2": "ST",
        "iso_alpha3": "STP",
        "iso_numeric": 678,
    },
    {
        "label": "Saudi Arabia",
        "iso_en_shortname": "Saudi Arabia",
        "iso_fr_shortname": "Arabie saoudite (l')",
        "iso_alpha2": "SA",
        "iso_alpha3": "SAU",
        "iso_numeric": 682,
    },
    {
        "label": "Senegal",
        "iso_en_shortname": "Senegal",
        "iso_fr_shortname": "Sénégal (le)",
        "iso_alpha2": "SN",
        "iso_alpha3": "SEN",
        "iso_numeric": 686,
    },
    {
        "label": "Serbia",
        "iso_en_shortname": "Serbia",
        "iso_fr_shortname": "Serbie (la)",
        "iso_alpha2": "RS",
        "iso_alpha3": "SRB",
        "iso_numeric": 688,
    },
    {
        "label": "Seychelles",
        "iso_en_shortname": "Seychelles",
        "iso_fr_shortname": "Seychelles (les)",
        "iso_alpha2": "SC",
        "iso_alpha3": "SYC",
        "iso_numeric": 690,
    },
    {
        "label": "Sierra Leone",
        "iso_en_shortname": "Sierra Leone",
        "iso_fr_shortname": "Sierra Leone (la)",
        "iso_alpha2": "SL",
        "iso_alpha3": "SLE",
        "iso_numeric": 694,
    },
    {
        "label": "Singapore",
        "iso_en_shortname": "Singapore",
        "iso_fr_shortname": "Singapour",
        "iso_alpha2": "SG",
        "iso_alpha3": "SGP",
        "iso_numeric": 702,
    },
    {
        "label": "Sint Maarten",
        "iso_en_shortname": "Sint Maarten (Dutch part)",
        "iso_fr_shortname": "Saint-Martin (partie néerlandaise)",
        "iso_alpha2": "SX",
        "iso_alpha3": "SXM",
        "iso_numeric": 534,
    },
    {
        "label": "Slovakia",
        "iso_en_shortname": "Slovakia",
        "iso_fr_shortname": "Slovaquie (la)",
        "iso_alpha2": "SK",
        "iso_alpha3": "SVK",
        "iso_numeric": 703,
    },
    {
        "label": "Slovenia",
        "iso_en_shortname": "Slovenia",
        "iso_fr_shortname": "Slovénie (la)",
        "iso_alpha2": "SI",
        "iso_alpha3": "SVN",
        "iso_numeric": 705,
    },
    {
        "label": "Solomon Islands",
        "iso_en_shortname": "Solomon Islands",
        "iso_fr_shortname": "Salomon (les Îles)",
        "iso_alpha2": "SB",
        "iso_alpha3": "SLB",
        "iso_numeric": 90,
    },
    {
        "label": "Somalia",
        "iso_en_shortname": "Somalia",
        "iso_fr_shortname": "Somalie (la)",
        "iso_alpha2": "SO",
        "iso_alpha3": "SOM",
        "iso_numeric": 706,
    },
    {
        "label": "South Africa",
        "iso_en_shortname": "South Africa",
        "iso_fr_shortname": "Afrique du Sud (l')",
        "iso_alpha2": "ZA",
        "iso_alpha3": "ZAF",
        "iso_numeric": 710,
    },
    {
        "label": "South Georgia and the South Sandwich Islands",
        "iso_en_shortname": "South Georgia and the South Sandwich Islands",
        "iso_fr_shortname": "Géorgie du Sud-et-les Îles Sandwich du Sud (la)",
        "iso_alpha2": "GS",
        "iso_alpha3": "SGS",
        "iso_numeric": 239,
    },
    {
        "label": "South Sudan",
        "iso_en_shortname": "South Sudan",
        "iso_fr_shortname": "Soudan du Sud (le)",
        "iso_alpha2": "SS",
        "iso_alpha3": "SSD",
        "iso_numeric": 728,
    },
    {
        "label": "Spain",
        "iso_en_shortname": "Spain",
        "iso_fr_shortname": "Espagne (l')",
        "iso_alpha2": "ES",
        "iso_alpha3": "ESP",
        "iso_numeric": 724,
    },
    {
        "label": "Sri Lanka",
        "iso_en_shortname": "Sri Lanka",
        "iso_fr_shortname": "Sri Lanka",
        "iso_alpha2": "LK",
        "iso_alpha3": "LKA",
        "iso_numeric": 144,
    },
    {
        "label": "Sudan",
        "iso_en_shortname": "Sudan (the)",
        "iso_fr_shortname": "Soudan (le)",
        "iso_alpha2": "SD",
        "iso_alpha3": "SDN",
        "iso_numeric": 729,
    },
    {
        "label": "Suriname",
        "iso_en_shortname": "Suriname",
        "iso_fr_shortname": "Suriname (le)",
        "iso_alpha2": "SR",
        "iso_alpha3": "SUR",
        "iso_numeric": 740,
    },
    {
        "label": "Svalbard and Jan Mayen",
        "iso_en_shortname": "Svalbard and Jan Mayen",
        "iso_fr_shortname": "Svalbard et l'Île Jan Mayen (le)",
        "iso_alpha2": "SJ",
        "iso_alpha3": "SJM",
        "iso_numeric": 744,
    },
    {
        "label": "Sweden",
        "iso_en_shortname": "Sweden",
        "iso_fr_shortname": "Suède (la)",
        "iso_alpha2": "SE",
        "iso_alpha3": "SWE",
        "iso_numeric": 752,
    },
    {
        "label": "Switzerland",
        "iso_en_shortname": "Switzerland",
        "iso_fr_shortname": "Suisse (la)",
        "iso_alpha2": "CH",
        "iso_alpha3": "CHE",
        "iso_numeric": 756,
    },
    {
        "label": "Syria",
        "iso_en_shortname": "Syrian Arab Republic (the)",
        "iso_fr_shortname": "République arabe syrienne (la)",
        "iso_alpha2": "SY",
        "iso_alpha3": "SYR",
        "iso_numeric": 760,
    },
    {
        "label": "Taiwan (Province of China)",
        "iso_en_shortname": "Taiwan (Province of China)",
        "iso_fr_shortname": "Taïwan (Province de Chine)",
        "iso_alpha2": "TW",
        "iso_alpha3": "TWN",
        "iso_numeric": 158,
    },
    {
        "label": "Tajikistan",
        "iso_en_shortname": "Tajikistan",
        "iso_fr_shortname": "Tadjikistan (le)",
        "iso_alpha2": "TJ",
        "iso_alpha3": "TJK",
        "iso_numeric": 762,
    },
    {
        "label": "Tanzania",
        "iso_en_shortname": "Tanzania, the United Republic of",
        "iso_fr_shortname": "Tanzanie (la République-Unie de)",
        "iso_alpha2": "TZ",
        "iso_alpha3": "TZA",
        "iso_numeric": 834,
    },
    {
        "label": "Thailand",
        "iso_en_shortname": "Thailand",
        "iso_fr_shortname": "Thaïlande (la)",
        "iso_alpha2": "TH",
        "iso_alpha3": "THA",
        "iso_numeric": 764,
    },
    {
        "label": "Timor-Leste",
        "iso_en_shortname": "Timor-Leste",
        "iso_fr_shortname": "Timor-Leste (le)",
        "iso_alpha2": "TL",
        "iso_alpha3": "TLS",
        "iso_numeric": 626,
    },
    {
        "label": "Togo",
        "iso_en_shortname": "Togo",
        "iso_fr_shortname": "Togo (le)",
        "iso_alpha2": "TG",
        "iso_alpha3": "TGO",
        "iso_numeric": 768,
    },
    {
        "label": "Tokelau",
        "iso_en_shortname": "Tokelau",
        "iso_fr_shortname": "Tokelau (les)",
        "iso_alpha2": "TK",
        "iso_alpha3": "TKL",
        "iso_numeric": 772,
    },
    {
        "label": "Tonga",
        "iso_en_shortname": "Tonga",
        "iso_fr_shortname": "Tonga (les)",
        "iso_alpha2": "TO",
        "iso_alpha3": "TON",
        "iso_numeric": 776,
    },
    {
        "label": "Trinidad and Tobago",
        "iso_en_shortname": "Trinidad and Tobago",
        "iso_fr_shortname": "Trinité-et-Tobago (la)",
        "iso_alpha2": "TT",
        "iso_alpha3": "TTO",
        "iso_numeric": 780,
    },
    {
        "label": "Tunisia",
        "iso_en_shortname": "Tunisia",
        "iso_fr_shortname": "Tunisie (la)",
        "iso_alpha2": "TN",
        "iso_alpha3": "TUN",
        "iso_numeric": 788,
    },
    {
        "label": "Turkmenistan",
        "iso_en_shortname": "Turkmenistan",
        "iso_fr_shortname": "Turkménistan (le)",
        "iso_alpha2": "TM",
        "iso_alpha3": "TKM",
        "iso_numeric": 795,
    },
    {
        "label": "Turks and Caicos Islands",
        "iso_en_shortname": "Turks and Caicos Islands (the)",
        "iso_fr_shortname": "Turks-et-Caïcos (les Îles)",
        "iso_alpha2": "TC",
        "iso_alpha3": "TCA",
        "iso_numeric": 796,
    },
    {
        "label": "Tuvalu",
        "iso_en_shortname": "Tuvalu",
        "iso_fr_shortname": "Tuvalu (les)",
        "iso_alpha2": "TV",
        "iso_alpha3": "TUV",
        "iso_numeric": 798,
    },
    {
        "label": "Türkiye",
        "iso_en_shortname": "Türkiye",
        "iso_fr_shortname": "Türkiye (la)",
        "iso_alpha2": "TR",
        "iso_alpha3": "TUR",
        "iso_numeric": 792,
    },
    {
        "label": "Uganda",
        "iso_en_shortname": "Uganda",
        "iso_fr_shortname": "Ouganda (l')",
        "iso_alpha2": "UG",
        "iso_alpha3": "UGA",
        "iso_numeric": 800,
    },
    {
        "label": "Ukraine",
        "iso_en_shortname": "Ukraine",
        "iso_fr_shortname": "Ukraine (l')",
        "iso_alpha2": "UA",
        "iso_alpha3": "UKR",
        "iso_numeric": 804,
    },
    {
        "label": "United Arab Emirates",
        "iso_en_shortname": "United Arab Emirates (the)",
        "iso_fr_shortname": "Émirats arabes unis (les)",
        "iso_alpha2": "AE",
        "iso_alpha3": "ARE",
        "iso_numeric": 784,
    },
    {
        "label": "United Kingdom",
        "iso_en_shortname": "United Kingdom of Great Britain and Northern Ireland (the)",
        "iso_fr_shortname": "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)",
        "iso_alpha2": "GB",
        "iso_alpha3": "GBR",
        "iso_numeric": 826,
    },
    {
        "label": "United States Minor Outlying Islands",
        "iso_en_shortname": "United States Minor Outlying Islands (the)",
        "iso_fr_shortname": "Îles mineures éloignées des États-Unis (les)",
        "iso_alpha2": "UM",
        "iso_alpha3": "UMI",
        "iso_numeric": 581,
    },
    {
        "label": "United States of America",
        "iso_en_shortname": "United States of America (the)",
        "iso_fr_shortname": "États-Unis d'Amérique (les)",
        "iso_alpha2": "US",
        "iso_alpha3": "USA",
        "iso_numeric": 840,
    },
    {
        "label": "Uruguay",
        "iso_en_shortname": "Uruguay",
        "iso_fr_shortname": "Uruguay (l')",
        "iso_alpha2": "UY",
        "iso_alpha3": "URY",
        "iso_numeric": 858,
    },
    {
        "label": "Uzbekistan",
        "iso_en_shortname": "Uzbekistan",
        "iso_fr_shortname": "Ouzbékistan (l')",
        "iso_alpha2": "UZ",
        "iso_alpha3": "UZB",
        "iso_numeric": 860,
    },
    {
        "label": "Vanuatu",
        "iso_en_shortname": "Vanuatu",
        "iso_fr_shortname": "Vanuatu (le)",
        "iso_alpha2": "VU",
        "iso_alpha3": "VUT",
        "iso_numeric": 548,
    },
    {
        "label": "Venezuela",
        "iso_en_shortname": "Venezuela (Bolivarian Republic of)",
        "iso_fr_shortname": "Venezuela (République bolivarienne du)",
        "iso_alpha2": "VE",
        "iso_alpha3": "VEN",
        "iso_numeric": 862,
    },
    {
        "label": "Vietnam",
        "iso_en_shortname": "Viet Nam",
        "iso_fr_shortname": "Viet Nam (le)",
        "iso_alpha2": "VN",
        "iso_alpha3": "VNM",
        "iso_numeric": 704,
    },
    {
        "label": "British Virgin Islands",
        "iso_en_shortname": "Virgin Islands (British)",
        "iso_fr_shortname": "Vierges britanniques (les Îles)",
        "iso_alpha2": "VG",
        "iso_alpha3": "VGB",
        "iso_numeric": 92,
    },
    {
        "label": "United States Virgin Islands",
        "iso_en_shortname": "Virgin Islands (U.S.)",
        "iso_fr_shortname": "Vierges des États-Unis (les Îles)",
        "iso_alpha2": "VI",
        "iso_alpha3": "VIR",
        "iso_numeric": 850,
    },
    {
        "label": "Wallis and Futuna",
        "iso_en_shortname": "Wallis and Futuna",
        "iso_fr_shortname": "Wallis-et-Futuna ",
        "iso_alpha2": "WF",
        "iso_alpha3": "WLF",
        "iso_numeric": 876,
    },
    {
        "label": "Western Sahara",
        "iso_en_shortname": "Western Sahara*",
        "iso_fr_shortname": "Sahara occidental (le)*",
        "iso_alpha2": "EH",
        "iso_alpha3": "ESH",
        "iso_numeric": 732,
    },
    {
        "label": "Yemen",
        "iso_en_shortname": "Yemen",
        "iso_fr_shortname": "Yémen (le)",
        "iso_alpha2": "YE",
        "iso_alpha3": "YEM",
        "iso_numeric": 887,
    },
    {
        "label": "Zambia",
        "iso_en_shortname": "Zambia",
        "iso_fr_shortname": "Zambie (la)",
        "iso_alpha2": "ZM",
        "iso_alpha3": "ZMB",
        "iso_numeric": 894,
    },
    {
        "label": "Zimbabwe",
        "iso_en_shortname": "Zimbabwe",
        "iso_fr_shortname": "Zimbabwe (le)",
        "iso_alpha2": "ZW",
        "iso_alpha3": "ZWE",
        "iso_numeric": 716,
    },
    {
        "label": "Åland Islands",
        "iso_en_shortname": "Åland Islands",
        "iso_fr_shortname": "Åland (les Îles)",
        "iso_alpha2": "AX",
        "iso_alpha3": "ALA",
        "iso_numeric": 248,
    },
]
