# (generated with --quick)

from plain import preflight
from typing import Any, Never

NOT_PROVIDED: Any

class CheckFieldDefaultMixin:
    _default_hint: tuple[str, str]
    def _check_default(self) -> list: ...
    def check(self, **kwargs) -> Any: ...

class FieldCacheMixin:
    __doc__: str
    def delete_cached_value(self, instance) -> Never: ...
    def get_cache_name(self) -> Never: ...
    def get_cached_value(self, instance, default = ...) -> Never: ...
    def is_cached(self, instance) -> Never: ...
    def set_cached_value(self, instance, value) -> Never: ...
