
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-18T06:38:36+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "e7a3921f70f0005bf5fa77fc7222f1e2d7d06c23",
 "version": "0.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
