# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from dima_sdk.models.get_time_offs_query_for_organization200_response_data_inner_time_off_type_policy_policy_type import GetTimeOffsQueryForOrganization200ResponseDataInnerTimeOffTypePolicyPolicyType
from typing import Optional, Set
from typing_extensions import Self

class GetTimeOffsQueryForOrganization200ResponseDataInnerTimeOffTypePolicy(BaseModel):
    """
    GetTimeOffsQueryForOrganization200ResponseDataInnerTimeOffTypePolicy
    """ # noqa: E501
    id: StrictStr = Field(description="Policy id")
    name: StrictStr = Field(description="The custom name given to policy during policy creation.")
    policy_type: GetTimeOffsQueryForOrganization200ResponseDataInnerTimeOffTypePolicyPolicyType
    __properties: ClassVar[List[str]] = ["id", "name", "policy_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTimeOffsQueryForOrganization200ResponseDataInnerTimeOffTypePolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of policy_type
        if self.policy_type:
            _dict['policy_type'] = self.policy_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTimeOffsQueryForOrganization200ResponseDataInnerTimeOffTypePolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "policy_type": GetTimeOffsQueryForOrganization200ResponseDataInnerTimeOffTypePolicyPolicyType.from_dict(obj["policy_type"]) if obj.get("policy_type") is not None else None
        })
        return _obj


