# (generated with --quick)

SESSION_CLASS: str
SESSION_COOKIE_AGE: int
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_HTTPONLY: bool
SESSION_COOKIE_NAME: str
SESSION_COOKIE_PATH: str
SESSION_COOKIE_SAMESITE: str
SESSION_COOKIE_SECURE: bool
SESSION_EXPIRE_AT_BROWSER_CLOSE: bool
SESSION_SAVE_EVERY_REQUEST: bool
