from dlubal.api.common import common_pb2 as _common_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class MemberSetRepresentativeMemberModelType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_UNKNOWN: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_BEAM: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_BUCKLING: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_CABLE: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COMPRESSION: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_HINGE_HINGE: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_HINGE_RIGID: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_RIGID_HINGE: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_RIGID_RIGID: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_DAMPER: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_DEFINABLE_STIFFNESS: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_JOIST: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_PILE: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RESULT_BEAM: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RESULT_LINE: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RIB: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RIGID: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_SPRING: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_SURFACE_MODEL: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_TENSION: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_TRUSS: _ClassVar[MemberSetRepresentativeMemberModelType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_TRUSS_ONLY_N: _ClassVar[MemberSetRepresentativeMemberModelType]

class MemberSetRepresentativeMemberModelSectionDistributionType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_UNIFORM: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_CURVED: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_FISH_BEAM_PARABOLIC: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_LINEAR: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_NONE: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_OFFSET_AT_BOTH_SIDES: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_OFFSET_AT_END_OF_MEMBER: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_OFFSET_AT_START_OF_MEMBER: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_PITCHED_CAMBERED_BEAM_WITH_CONSTANT_HEIGHT: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_PITCHED_CAMBERED_BEAM_WITH_VARIABLE_HEIGHT: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_SADDLE: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_TAPERED_AT_BOTH_SIDES: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_TAPERED_AT_END_OF_MEMBER: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_TAPERED_AT_START_OF_MEMBER: _ClassVar[MemberSetRepresentativeMemberModelSectionDistributionType]

class MemberSetRepresentativeMemberModelReferenceType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_L: _ClassVar[MemberSetRepresentativeMemberModelReferenceType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_XY: _ClassVar[MemberSetRepresentativeMemberModelReferenceType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_XZ: _ClassVar[MemberSetRepresentativeMemberModelReferenceType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_YZ: _ClassVar[MemberSetRepresentativeMemberModelReferenceType]

class MemberSetRepresentativeMemberModelMemberTypeRibAlignment(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_ON_Z_SIDE_NEGATIVE: _ClassVar[MemberSetRepresentativeMemberModelMemberTypeRibAlignment]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_CENTRIC: _ClassVar[MemberSetRepresentativeMemberModelMemberTypeRibAlignment]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_ON_Z_SIDE_POSITIVE: _ClassVar[MemberSetRepresentativeMemberModelMemberTypeRibAlignment]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_USER_DEFINED_VIA_MEMBER_ECCENTRICITY: _ClassVar[MemberSetRepresentativeMemberModelMemberTypeRibAlignment]

class MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_INDENTED: _ClassVar[MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_ROUGH: _ClassVar[MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_SMOOTH: _ClassVar[MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_VERY_SMOOTH: _ClassVar[MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification]

class MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_WITHIN_CUBOID_QUADRATIC: _ClassVar[MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_FROM_LISTED_INCLUDE_OBJECTS: _ClassVar[MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_WITHIN_CUBOID_GENERAL: _ClassVar[MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_WITHIN_CYLINDER: _ClassVar[MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces]

class MemberSetRepresentativeMemberModelSectionAlignment(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_ALIGNMENT_TOP: _ClassVar[MemberSetRepresentativeMemberModelSectionAlignment]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_ALIGNMENT_BOTTOM: _ClassVar[MemberSetRepresentativeMemberModelSectionAlignment]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_ALIGNMENT_CENTRIC: _ClassVar[MemberSetRepresentativeMemberModelSectionAlignment]

class MemberSetRepresentativeMemberModelGrainAlignment(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_GRAIN_ALIGNMENT_TOP: _ClassVar[MemberSetRepresentativeMemberModelGrainAlignment]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_GRAIN_ALIGNMENT_BOTTOM: _ClassVar[MemberSetRepresentativeMemberModelGrainAlignment]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_GRAIN_ALIGNMENT_CENTRIC: _ClassVar[MemberSetRepresentativeMemberModelGrainAlignment]

class MemberSetRepresentativeMemberModelCurvedMemberCantileversType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_HORIZONTAL: _ClassVar[MemberSetRepresentativeMemberModelCurvedMemberCantileversType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_OFFSET: _ClassVar[MemberSetRepresentativeMemberModelCurvedMemberCantileversType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_PARALLEL: _ClassVar[MemberSetRepresentativeMemberModelCurvedMemberCantileversType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_TAPER: _ClassVar[MemberSetRepresentativeMemberModelCurvedMemberCantileversType]

class MemberSetRepresentativeMemberModelRotationSpecificationType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_BY_ANGLE: _ClassVar[MemberSetRepresentativeMemberModelRotationSpecificationType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_INSIDE: _ClassVar[MemberSetRepresentativeMemberModelRotationSpecificationType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_SURFACE: _ClassVar[MemberSetRepresentativeMemberModelRotationSpecificationType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_TO_NODE: _ClassVar[MemberSetRepresentativeMemberModelRotationSpecificationType]

class MemberSetRepresentativeMemberModelRotationPlaneType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_PLANE_TYPE_ROTATION_PLANE_XY: _ClassVar[MemberSetRepresentativeMemberModelRotationPlaneType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_PLANE_TYPE_ROTATION_PLANE_XZ: _ClassVar[MemberSetRepresentativeMemberModelRotationPlaneType]

class MemberSetRepresentativeMemberModelRotationSurfacePlaneType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SURFACE_PLANE_TYPE_ROTATION_PLANE_XY: _ClassVar[MemberSetRepresentativeMemberModelRotationSurfacePlaneType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SURFACE_PLANE_TYPE_ROTATION_PLANE_XZ: _ClassVar[MemberSetRepresentativeMemberModelRotationSurfacePlaneType]

class MemberSetRepresentativeMemberModelDeflectionCheckDirection(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Y: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z_AND_Y: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Y: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z_AND_Y: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_RESULTING_AXIS: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDirection]

class MemberSetRepresentativeMemberModelDeflectionCheckDisplacementReference(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_SEGMENT_ENDS: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDisplacementReference]
    MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_UNDEFORMED_SYSTEM: _ClassVar[MemberSetRepresentativeMemberModelDeflectionCheckDisplacementReference]

class MemberSetRepresentativeMemberSetModelSetType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_SET_TYPE_CONTINUOUS: _ClassVar[MemberSetRepresentativeMemberSetModelSetType]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_SET_TYPE_GROUP: _ClassVar[MemberSetRepresentativeMemberSetModelSetType]

class MemberSetRepresentativeMemberSetModelDeflectionCheckDirection(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Y: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z_AND_Y: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Y: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z_AND_Y: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_RESULTING_AXIS: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection]

class MemberSetRepresentativeMemberSetModelDeflectionCheckDisplacementReference(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_SEGMENT_ENDS: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDisplacementReference]
    MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_UNDEFORMED_SYSTEM: _ClassVar[MemberSetRepresentativeMemberSetModelDeflectionCheckDisplacementReference]
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_UNKNOWN: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_BEAM: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_BUCKLING: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_CABLE: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COMPRESSION: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_HINGE_HINGE: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_HINGE_RIGID: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_RIGID_HINGE: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_COUPLING_RIGID_RIGID: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_DAMPER: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_DEFINABLE_STIFFNESS: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_JOIST: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_PILE: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RESULT_BEAM: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RESULT_LINE: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RIB: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_RIGID: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_SPRING: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_SURFACE_MODEL: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_TENSION: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_TRUSS: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_TYPE_TRUSS_ONLY_N: MemberSetRepresentativeMemberModelType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_UNIFORM: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_CURVED: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_FISH_BEAM_PARABOLIC: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_LINEAR: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_NONE: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_OFFSET_AT_BOTH_SIDES: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_OFFSET_AT_END_OF_MEMBER: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_OFFSET_AT_START_OF_MEMBER: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_PITCHED_CAMBERED_BEAM_WITH_CONSTANT_HEIGHT: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_PITCHED_CAMBERED_BEAM_WITH_VARIABLE_HEIGHT: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_SADDLE: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_TAPERED_AT_BOTH_SIDES: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_TAPERED_AT_END_OF_MEMBER: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_TAPERED_AT_START_OF_MEMBER: MemberSetRepresentativeMemberModelSectionDistributionType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_L: MemberSetRepresentativeMemberModelReferenceType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_XY: MemberSetRepresentativeMemberModelReferenceType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_XZ: MemberSetRepresentativeMemberModelReferenceType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_REFERENCE_TYPE_YZ: MemberSetRepresentativeMemberModelReferenceType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_ON_Z_SIDE_NEGATIVE: MemberSetRepresentativeMemberModelMemberTypeRibAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_CENTRIC: MemberSetRepresentativeMemberModelMemberTypeRibAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_ON_Z_SIDE_POSITIVE: MemberSetRepresentativeMemberModelMemberTypeRibAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_USER_DEFINED_VIA_MEMBER_ECCENTRICITY: MemberSetRepresentativeMemberModelMemberTypeRibAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_INDENTED: MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_ROUGH: MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_SMOOTH: MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_VERY_SMOOTH: MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_WITHIN_CUBOID_QUADRATIC: MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_FROM_LISTED_INCLUDE_OBJECTS: MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_WITHIN_CUBOID_GENERAL: MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_WITHIN_CYLINDER: MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_ALIGNMENT_TOP: MemberSetRepresentativeMemberModelSectionAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_ALIGNMENT_BOTTOM: MemberSetRepresentativeMemberModelSectionAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_SECTION_ALIGNMENT_CENTRIC: MemberSetRepresentativeMemberModelSectionAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_GRAIN_ALIGNMENT_TOP: MemberSetRepresentativeMemberModelGrainAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_GRAIN_ALIGNMENT_BOTTOM: MemberSetRepresentativeMemberModelGrainAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_GRAIN_ALIGNMENT_CENTRIC: MemberSetRepresentativeMemberModelGrainAlignment
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_HORIZONTAL: MemberSetRepresentativeMemberModelCurvedMemberCantileversType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_OFFSET: MemberSetRepresentativeMemberModelCurvedMemberCantileversType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_PARALLEL: MemberSetRepresentativeMemberModelCurvedMemberCantileversType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_TAPER: MemberSetRepresentativeMemberModelCurvedMemberCantileversType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_BY_ANGLE: MemberSetRepresentativeMemberModelRotationSpecificationType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_INSIDE: MemberSetRepresentativeMemberModelRotationSpecificationType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_SURFACE: MemberSetRepresentativeMemberModelRotationSpecificationType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_TO_NODE: MemberSetRepresentativeMemberModelRotationSpecificationType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_PLANE_TYPE_ROTATION_PLANE_XY: MemberSetRepresentativeMemberModelRotationPlaneType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_PLANE_TYPE_ROTATION_PLANE_XZ: MemberSetRepresentativeMemberModelRotationPlaneType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SURFACE_PLANE_TYPE_ROTATION_PLANE_XY: MemberSetRepresentativeMemberModelRotationSurfacePlaneType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_ROTATION_SURFACE_PLANE_TYPE_ROTATION_PLANE_XZ: MemberSetRepresentativeMemberModelRotationSurfacePlaneType
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z: MemberSetRepresentativeMemberModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Y: MemberSetRepresentativeMemberModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z: MemberSetRepresentativeMemberModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z_AND_Y: MemberSetRepresentativeMemberModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Y: MemberSetRepresentativeMemberModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z_AND_Y: MemberSetRepresentativeMemberModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_RESULTING_AXIS: MemberSetRepresentativeMemberModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_SEGMENT_ENDS: MemberSetRepresentativeMemberModelDeflectionCheckDisplacementReference
MEMBER_SET_REPRESENTATIVE_MEMBER_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_UNDEFORMED_SYSTEM: MemberSetRepresentativeMemberModelDeflectionCheckDisplacementReference
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_SET_TYPE_CONTINUOUS: MemberSetRepresentativeMemberSetModelSetType
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_SET_TYPE_GROUP: MemberSetRepresentativeMemberSetModelSetType
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Y: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_AUXILIARY_LOCAL_AXIS_Z_AND_Y: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Y: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_LOCAL_AXIS_Z_AND_Y: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_RESULTING_AXIS: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_SEGMENT_ENDS: MemberSetRepresentativeMemberSetModelDeflectionCheckDisplacementReference
MEMBER_SET_REPRESENTATIVE_MEMBER_SET_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_DEFORMED_UNDEFORMED_SYSTEM: MemberSetRepresentativeMemberSetModelDeflectionCheckDisplacementReference

class MemberSetRepresentative(_message.Message):
    __slots__ = ("no", "user_defined_name_enabled", "name", "member_sets", "comment", "number_of_member_sets", "number_of_members", "section_ids", "total_length", "total_volume", "total_mass", "total_surface_of_coating", "total_center_of_gravity_x", "total_center_of_gravity_y", "total_center_of_gravity_z", "member_model_no", "member_model_type", "member_model_is_deactivated_for_calculation", "member_model_line", "member_model_section_distribution_type", "member_model_reference_type", "member_model_nodes", "member_model_node_start", "member_model_node_end", "member_model_analytical_length", "member_model_analytical_volume", "member_model_analytical_mass", "member_model_analytical_surface_of_coating", "member_model_analytical_center_of_gravity", "member_model_analytical_center_of_gravity_x", "member_model_analytical_center_of_gravity_y", "member_model_analytical_center_of_gravity_z", "member_model_length", "member_model_volume", "member_model_mass", "member_model_surface_of_coating", "member_model_center_of_gravity", "member_model_center_of_gravity_x", "member_model_center_of_gravity_y", "member_model_center_of_gravity_z", "member_set_model_position", "member_set_model_position_short", "member_model_member_representative", "member_model_design_properties_via_member", "member_model_design_properties_via_parent_member_set", "member_model_design_properties_parent_member_set", "member_model_comment", "member_model_member_type_rib_alignment", "member_model_member_rib_first_surface", "member_model_member_rib_second_surface", "member_model_member_rib_surface_assignment_autodetect", "member_model_member_rib_generating_longitudinal_reinforcement_items_from_surfaces_enabled", "member_model_align_local_z_axis_to_local_z_axis_of_surface", "member_model_member_rib_shear_joint_between_web_and_flange", "member_model_member_rib_surface_roughness_classification", "member_model_member_rib_reduction_of_joint_width", "member_model_flange_dimensions", "member_model_synchronize_width_mode", "member_model_relative_ordinates_mode", "member_model_member_type_definable_stiffness", "member_model_result_beam_integrate_stresses_and_forces", "member_model_result_beam_y_z", "member_model_result_beam_y_plus", "member_model_result_beam_z_plus", "member_model_result_beam_y_minus", "member_model_result_beam_z_minus", "member_model_result_beam_radius", "member_model_result_beam_include_surfaces", "member_model_result_beam_include_all_surfaces", "member_model_result_beam_include_solids", "member_model_result_beam_include_all_solids", "member_model_result_beam_include_members", "member_model_result_beam_include_all_members", "member_model_result_beam_exclude_surfaces", "member_model_result_beam_exclude_solids", "member_model_result_beam_exclude_members", "member_model_projected_length", "member_model_section_distance_from_start_is_defined_as_relative", "member_model_section_distance_from_start_absolute", "member_model_section_distance_from_end_relative", "member_model_section_distance_from_end_is_defined_as_relative", "member_model_section_distance_from_end_absolute", "member_model_section_distance_from_start_relative", "member_model_section_alignment", "member_model_grain_alignment", "member_model_is_curved", "member_model_curved_member_is_asymmetric_layout", "member_model_curved_member_is_cantilevers", "member_model_curved_member_cantilevers_type", "member_model_curved_member_is_capped_with_loose_ridge_wedge", "member_model_curved_member_parameters", "member_model_rotation_specification_type", "member_model_rotation_angle", "member_model_rotation_help_node", "member_model_rotation_plane_type", "member_model_rotation_surface", "member_model_rotation_surface_plane_type", "member_model_is_rotated", "member_model_section_start", "member_model_section_end", "member_model_section_internal", "member_model_section_material", "member_model_member_hinge_start", "member_model_member_hinge_end", "member_model_member_eccentricity_start", "member_model_member_eccentricity_end", "member_model_support", "member_model_member_transverse_stiffener", "member_model_member_openings", "member_model_member_nonlinearity", "member_model_member_result_intermediate_point", "member_model_concrete_effective_lengths", "member_model_steel_effective_lengths", "member_model_timber_effective_lengths", "member_model_aluminum_effective_lengths", "member_model_concrete_shear_reinforcement_spans", "member_model_concrete_longitudinal_reinforcement_items", "member_model_concrete_cover_user_defined_enabled", "member_model_concrete_cover_different_at_section_sides_enabled", "member_model_concrete_cover", "member_model_concrete_cover_top", "member_model_concrete_cover_bottom", "member_model_concrete_cover_left", "member_model_concrete_cover_right", "member_model_concrete_cover_min", "member_model_concrete_cover_min_top", "member_model_concrete_cover_min_bottom", "member_model_concrete_cover_min_left", "member_model_concrete_cover_min_right", "member_model_concrete_durability", "member_model_concrete_durability_top", "member_model_concrete_durability_bottom", "member_model_concrete_durability_left", "member_model_concrete_durability_right", "member_model_steel_boundary_conditions", "member_model_steel_member_local_section_reduction", "member_model_steel_member_transverse_weld", "member_model_timber_service_class", "member_model_timber_moisture_class", "member_model_timber_service_conditions", "member_model_timber_member_local_section_reduction", "member_model_aluminum_boundary_conditions", "member_model_aluminum_member_local_section_reduction", "member_model_aluminum_member_transverse_weld", "member_model_stress_analysis_configuration", "member_model_member_aluminum_design_uls_configuration", "member_model_member_aluminum_design_sls_configuration", "member_model_member_concrete_design_uls_configuration", "member_model_member_concrete_design_sls_configuration", "member_model_member_concrete_design_fr_configuration", "member_model_member_concrete_design_seismic_configuration", "member_model_member_steel_design_uls_configuration", "member_model_member_steel_design_sls_configuration", "member_model_member_steel_design_fr_configuration", "member_model_member_timber_design_uls_configuration", "member_model_member_timber_design_sls_configuration", "member_model_member_timber_design_fr_configuration", "member_model_end_modifications_member_start_extension", "member_model_end_modifications_member_start_slope_y", "member_model_end_modifications_member_start_slope_z", "member_model_end_modifications_member_end_extension", "member_model_end_modifications_member_end_slope_y", "member_model_end_modifications_member_end_slope_z", "member_model_has_any_end_modifications", "member_model_deflection_check_direction", "member_model_deflection_check_displacement_reference", "member_model_design_support_on_member_start", "member_model_design_support_on_member_end", "member_model_design_supports_on_internal_nodes", "member_model_is_generated", "member_model_generating_object_info", "member_set_model_no", "member_set_model_user_defined_name_enabled", "member_set_model_name", "member_set_model_set_type", "member_set_model_members", "member_set_model_length", "member_set_model_center_of_gravity", "member_set_model_center_of_gravity_x", "member_set_model_center_of_gravity_y", "member_set_model_center_of_gravity_z", "member_set_model_volume", "member_set_model_mass", "member_set_model_member_set_representative", "member_set_model_discontinuous_torsional_warping", "member_set_model_design_properties_activated", "member_set_model_steel_effective_lengths", "member_set_model_steel_boundary_conditions", "member_set_model_steel_member_local_section_reductions", "member_set_model_member_steel_design_uls_configuration", "member_set_model_member_steel_design_sls_configuration", "member_set_model_member_steel_design_fr_configuration", "member_set_model_member_steel_design_seismic_configuration", "member_set_model_aluminum_effective_lengths", "member_set_model_aluminum_boundary_conditions", "member_set_model_aluminum_member_local_section_reductions", "member_set_model_aluminum_member_transverse_weld", "member_set_model_member_aluminum_design_uls_configuration", "member_set_model_member_aluminum_design_sls_configuration", "member_set_model_concrete_shear_reinforcement_spans", "member_set_model_concrete_longitudinal_reinforcement_items", "member_set_model_concrete_cover_user_defined_enabled", "member_set_model_concrete_cover_different_at_section_sides_enabled", "member_set_model_concrete_cover", "member_set_model_concrete_cover_top", "member_set_model_concrete_cover_bottom", "member_set_model_concrete_cover_left", "member_set_model_concrete_cover_right", "member_set_model_concrete_cover_min", "member_set_model_concrete_cover_min_top", "member_set_model_concrete_cover_min_bottom", "member_set_model_concrete_cover_min_left", "member_set_model_concrete_cover_min_right", "member_set_model_concrete_durability", "member_set_model_concrete_durability_top", "member_set_model_concrete_durability_bottom", "member_set_model_concrete_durability_left", "member_set_model_concrete_durability_right", "member_set_model_concrete_effective_lengths", "member_set_model_member_concrete_design_uls_configuration", "member_set_model_member_concrete_design_sls_configuration", "member_set_model_member_concrete_design_fr_configuration", "member_set_model_member_concrete_design_seismic_configuration", "member_set_model_service_class_timber_design", "member_set_model_moisture_class_timber_design", "member_set_model_timber_effective_lengths", "member_set_model_service_conditions_timber_design", "member_set_model_timber_local_section_reductions", "member_set_model_member_timber_design_uls_configuration", "member_set_model_member_timber_design_sls_configuration", "member_set_model_member_timber_design_fr_configuration", "member_set_model_support", "member_set_model_member_transverse_stiffener", "member_set_model_member_openings", "member_set_model_stress_analysis_configuration", "member_set_model_deflection_check_direction", "member_set_model_deflection_check_displacement_reference", "member_set_model_design_support_on_member_set_start", "member_set_model_design_support_on_member_set_end", "member_set_model_design_supports_on_internal_nodes", "member_set_model_comment", "member_set_model_is_generated", "member_set_model_generating_object_info", "member_set_model_member_set_rib_generating_longitudinal_reinforcement_items_from_surfaces_enabled", "member_model_deflection_segments_defined_length_y_axis_enabled", "member_model_deflection_segments_defined_length_z_axis_enabled", "member_model_deflection_segments_y_axis", "member_model_deflection_segments_z_axis", "member_set_model_deflection_segments_defined_length_y_axis_enabled", "member_set_model_deflection_segments_defined_length_z_axis_enabled", "member_set_model_deflection_segments_y_axis", "member_set_model_deflection_segments_z_axis", "concrete_longitudinal_reinforcement_span", "concrete_shear_reinforcement_span", "id_for_export_import", "metadata_for_export_import")
    NO_FIELD_NUMBER: _ClassVar[int]
    USER_DEFINED_NAME_ENABLED_FIELD_NUMBER: _ClassVar[int]
    NAME_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SETS_FIELD_NUMBER: _ClassVar[int]
    COMMENT_FIELD_NUMBER: _ClassVar[int]
    NUMBER_OF_MEMBER_SETS_FIELD_NUMBER: _ClassVar[int]
    NUMBER_OF_MEMBERS_FIELD_NUMBER: _ClassVar[int]
    SECTION_IDS_FIELD_NUMBER: _ClassVar[int]
    TOTAL_LENGTH_FIELD_NUMBER: _ClassVar[int]
    TOTAL_VOLUME_FIELD_NUMBER: _ClassVar[int]
    TOTAL_MASS_FIELD_NUMBER: _ClassVar[int]
    TOTAL_SURFACE_OF_COATING_FIELD_NUMBER: _ClassVar[int]
    TOTAL_CENTER_OF_GRAVITY_X_FIELD_NUMBER: _ClassVar[int]
    TOTAL_CENTER_OF_GRAVITY_Y_FIELD_NUMBER: _ClassVar[int]
    TOTAL_CENTER_OF_GRAVITY_Z_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_NO_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_IS_DEACTIVATED_FOR_CALCULATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_LINE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_DISTRIBUTION_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_REFERENCE_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_NODES_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_NODE_START_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_NODE_END_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_LENGTH_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_VOLUME_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_MASS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_SURFACE_OF_COATING_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_CENTER_OF_GRAVITY_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_CENTER_OF_GRAVITY_X_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_CENTER_OF_GRAVITY_Y_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ANALYTICAL_CENTER_OF_GRAVITY_Z_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_LENGTH_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_VOLUME_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MASS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SURFACE_OF_COATING_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CENTER_OF_GRAVITY_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CENTER_OF_GRAVITY_X_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CENTER_OF_GRAVITY_Y_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CENTER_OF_GRAVITY_Z_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_POSITION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_POSITION_SHORT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_REPRESENTATIVE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DESIGN_PROPERTIES_VIA_MEMBER_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DESIGN_PROPERTIES_VIA_PARENT_MEMBER_SET_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DESIGN_PROPERTIES_PARENT_MEMBER_SET_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_COMMENT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_TYPE_RIB_ALIGNMENT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RIB_FIRST_SURFACE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RIB_SECOND_SURFACE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RIB_SURFACE_ASSIGNMENT_AUTODETECT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RIB_GENERATING_LONGITUDINAL_REINFORCEMENT_ITEMS_FROM_SURFACES_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ALIGN_LOCAL_Z_AXIS_TO_LOCAL_Z_AXIS_OF_SURFACE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RIB_SHEAR_JOINT_BETWEEN_WEB_AND_FLANGE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RIB_SURFACE_ROUGHNESS_CLASSIFICATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RIB_REDUCTION_OF_JOINT_WIDTH_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_FLANGE_DIMENSIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SYNCHRONIZE_WIDTH_MODE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RELATIVE_ORDINATES_MODE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_TYPE_DEFINABLE_STIFFNESS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_INTEGRATE_STRESSES_AND_FORCES_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_Y_Z_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_Y_PLUS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_Z_PLUS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_Y_MINUS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_Z_MINUS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_RADIUS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_INCLUDE_SURFACES_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_INCLUDE_ALL_SURFACES_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_INCLUDE_SOLIDS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_INCLUDE_ALL_SOLIDS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_INCLUDE_MEMBERS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_INCLUDE_ALL_MEMBERS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_EXCLUDE_SURFACES_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_EXCLUDE_SOLIDS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_RESULT_BEAM_EXCLUDE_MEMBERS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_PROJECTED_LENGTH_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_DISTANCE_FROM_START_IS_DEFINED_AS_RELATIVE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_DISTANCE_FROM_START_ABSOLUTE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_DISTANCE_FROM_END_RELATIVE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_DISTANCE_FROM_END_IS_DEFINED_AS_RELATIVE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_DISTANCE_FROM_END_ABSOLUTE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_DISTANCE_FROM_START_RELATIVE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_ALIGNMENT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_GRAIN_ALIGNMENT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_IS_CURVED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CURVED_MEMBER_IS_ASYMMETRIC_LAYOUT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CURVED_MEMBER_IS_CANTILEVERS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CURVED_MEMBER_CANTILEVERS_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CURVED_MEMBER_IS_CAPPED_WITH_LOOSE_RIDGE_WEDGE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CURVED_MEMBER_PARAMETERS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ROTATION_SPECIFICATION_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ROTATION_ANGLE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ROTATION_HELP_NODE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ROTATION_PLANE_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ROTATION_SURFACE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ROTATION_SURFACE_PLANE_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_IS_ROTATED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_START_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_END_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_INTERNAL_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SECTION_MATERIAL_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_HINGE_START_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_HINGE_END_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_ECCENTRICITY_START_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_ECCENTRICITY_END_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_SUPPORT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_TRANSVERSE_STIFFENER_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_OPENINGS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_NONLINEARITY_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_RESULT_INTERMEDIATE_POINT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_STEEL_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_TIMBER_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ALUMINUM_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_SHEAR_REINFORCEMENT_SPANS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_LONGITUDINAL_REINFORCEMENT_ITEMS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_USER_DEFINED_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_DIFFERENT_AT_SECTION_SIDES_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_TOP_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_LEFT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_RIGHT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_MIN_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_MIN_TOP_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_MIN_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_MIN_LEFT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_COVER_MIN_RIGHT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_DURABILITY_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_DURABILITY_TOP_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_DURABILITY_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_DURABILITY_LEFT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_CONCRETE_DURABILITY_RIGHT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_STEEL_BOUNDARY_CONDITIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_STEEL_MEMBER_LOCAL_SECTION_REDUCTION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_STEEL_MEMBER_TRANSVERSE_WELD_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_TIMBER_SERVICE_CLASS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_TIMBER_MOISTURE_CLASS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_TIMBER_SERVICE_CONDITIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_TIMBER_MEMBER_LOCAL_SECTION_REDUCTION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ALUMINUM_BOUNDARY_CONDITIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ALUMINUM_MEMBER_LOCAL_SECTION_REDUCTION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_ALUMINUM_MEMBER_TRANSVERSE_WELD_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_STRESS_ANALYSIS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_ALUMINUM_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_ALUMINUM_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_CONCRETE_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_CONCRETE_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_CONCRETE_DESIGN_FR_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_CONCRETE_DESIGN_SEISMIC_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_STEEL_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_STEEL_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_STEEL_DESIGN_FR_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_TIMBER_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_TIMBER_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_MEMBER_TIMBER_DESIGN_FR_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_END_MODIFICATIONS_MEMBER_START_EXTENSION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_END_MODIFICATIONS_MEMBER_START_SLOPE_Y_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_END_MODIFICATIONS_MEMBER_START_SLOPE_Z_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_END_MODIFICATIONS_MEMBER_END_EXTENSION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_END_MODIFICATIONS_MEMBER_END_SLOPE_Y_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_END_MODIFICATIONS_MEMBER_END_SLOPE_Z_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_HAS_ANY_END_MODIFICATIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DEFLECTION_CHECK_DIRECTION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DESIGN_SUPPORT_ON_MEMBER_START_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DESIGN_SUPPORT_ON_MEMBER_END_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DESIGN_SUPPORTS_ON_INTERNAL_NODES_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_IS_GENERATED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_GENERATING_OBJECT_INFO_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_NO_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_USER_DEFINED_NAME_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_NAME_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_SET_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBERS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_LENGTH_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CENTER_OF_GRAVITY_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CENTER_OF_GRAVITY_X_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CENTER_OF_GRAVITY_Y_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CENTER_OF_GRAVITY_Z_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_VOLUME_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MASS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_SET_REPRESENTATIVE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DISCONTINUOUS_TORSIONAL_WARPING_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DESIGN_PROPERTIES_ACTIVATED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_STEEL_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_STEEL_BOUNDARY_CONDITIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_STEEL_MEMBER_LOCAL_SECTION_REDUCTIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_STEEL_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_STEEL_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_STEEL_DESIGN_FR_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_STEEL_DESIGN_SEISMIC_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_ALUMINUM_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_ALUMINUM_BOUNDARY_CONDITIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_ALUMINUM_MEMBER_LOCAL_SECTION_REDUCTIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_ALUMINUM_MEMBER_TRANSVERSE_WELD_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_ALUMINUM_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_ALUMINUM_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_SHEAR_REINFORCEMENT_SPANS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_LONGITUDINAL_REINFORCEMENT_ITEMS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_USER_DEFINED_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_DIFFERENT_AT_SECTION_SIDES_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_TOP_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_LEFT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_RIGHT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_MIN_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_MIN_TOP_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_MIN_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_MIN_LEFT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_COVER_MIN_RIGHT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_DURABILITY_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_DURABILITY_TOP_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_DURABILITY_BOTTOM_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_DURABILITY_LEFT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_DURABILITY_RIGHT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_CONCRETE_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_CONCRETE_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_CONCRETE_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_CONCRETE_DESIGN_FR_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_CONCRETE_DESIGN_SEISMIC_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_SERVICE_CLASS_TIMBER_DESIGN_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MOISTURE_CLASS_TIMBER_DESIGN_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_TIMBER_EFFECTIVE_LENGTHS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_SERVICE_CONDITIONS_TIMBER_DESIGN_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_TIMBER_LOCAL_SECTION_REDUCTIONS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_TIMBER_DESIGN_ULS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_TIMBER_DESIGN_SLS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_TIMBER_DESIGN_FR_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_SUPPORT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_TRANSVERSE_STIFFENER_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_OPENINGS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_STRESS_ANALYSIS_CONFIGURATION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DEFLECTION_CHECK_DIRECTION_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DEFLECTION_CHECK_DISPLACEMENT_REFERENCE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DESIGN_SUPPORT_ON_MEMBER_SET_START_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DESIGN_SUPPORT_ON_MEMBER_SET_END_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DESIGN_SUPPORTS_ON_INTERNAL_NODES_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_COMMENT_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_IS_GENERATED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_GENERATING_OBJECT_INFO_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_MEMBER_SET_RIB_GENERATING_LONGITUDINAL_REINFORCEMENT_ITEMS_FROM_SURFACES_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DEFLECTION_SEGMENTS_DEFINED_LENGTH_Y_AXIS_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DEFLECTION_SEGMENTS_DEFINED_LENGTH_Z_AXIS_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DEFLECTION_SEGMENTS_Y_AXIS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_MODEL_DEFLECTION_SEGMENTS_Z_AXIS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DEFLECTION_SEGMENTS_DEFINED_LENGTH_Y_AXIS_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DEFLECTION_SEGMENTS_DEFINED_LENGTH_Z_AXIS_ENABLED_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DEFLECTION_SEGMENTS_Y_AXIS_FIELD_NUMBER: _ClassVar[int]
    MEMBER_SET_MODEL_DEFLECTION_SEGMENTS_Z_AXIS_FIELD_NUMBER: _ClassVar[int]
    CONCRETE_LONGITUDINAL_REINFORCEMENT_SPAN_FIELD_NUMBER: _ClassVar[int]
    CONCRETE_SHEAR_REINFORCEMENT_SPAN_FIELD_NUMBER: _ClassVar[int]
    ID_FOR_EXPORT_IMPORT_FIELD_NUMBER: _ClassVar[int]
    METADATA_FOR_EXPORT_IMPORT_FIELD_NUMBER: _ClassVar[int]
    no: int
    user_defined_name_enabled: bool
    name: str
    member_sets: _containers.RepeatedScalarFieldContainer[int]
    comment: str
    number_of_member_sets: int
    number_of_members: int
    section_ids: str
    total_length: float
    total_volume: float
    total_mass: float
    total_surface_of_coating: float
    total_center_of_gravity_x: float
    total_center_of_gravity_y: float
    total_center_of_gravity_z: float
    member_model_no: int
    member_model_type: MemberSetRepresentativeMemberModelType
    member_model_is_deactivated_for_calculation: bool
    member_model_line: int
    member_model_section_distribution_type: MemberSetRepresentativeMemberModelSectionDistributionType
    member_model_reference_type: MemberSetRepresentativeMemberModelReferenceType
    member_model_nodes: _containers.RepeatedScalarFieldContainer[int]
    member_model_node_start: int
    member_model_node_end: int
    member_model_analytical_length: float
    member_model_analytical_volume: float
    member_model_analytical_mass: float
    member_model_analytical_surface_of_coating: float
    member_model_analytical_center_of_gravity: _common_pb2.Vector3d
    member_model_analytical_center_of_gravity_x: float
    member_model_analytical_center_of_gravity_y: float
    member_model_analytical_center_of_gravity_z: float
    member_model_length: float
    member_model_volume: float
    member_model_mass: float
    member_model_surface_of_coating: float
    member_model_center_of_gravity: _common_pb2.Vector3d
    member_model_center_of_gravity_x: float
    member_model_center_of_gravity_y: float
    member_model_center_of_gravity_z: float
    member_set_model_position: str
    member_set_model_position_short: str
    member_model_member_representative: int
    member_model_design_properties_via_member: bool
    member_model_design_properties_via_parent_member_set: bool
    member_model_design_properties_parent_member_set: int
    member_model_comment: str
    member_model_member_type_rib_alignment: MemberSetRepresentativeMemberModelMemberTypeRibAlignment
    member_model_member_rib_first_surface: int
    member_model_member_rib_second_surface: int
    member_model_member_rib_surface_assignment_autodetect: bool
    member_model_member_rib_generating_longitudinal_reinforcement_items_from_surfaces_enabled: bool
    member_model_align_local_z_axis_to_local_z_axis_of_surface: bool
    member_model_member_rib_shear_joint_between_web_and_flange: bool
    member_model_member_rib_surface_roughness_classification: MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification
    member_model_member_rib_reduction_of_joint_width: float
    member_model_flange_dimensions: ArrayOfMemberSetRepresentativeMemberModelFlangeDimensions
    member_model_synchronize_width_mode: bool
    member_model_relative_ordinates_mode: bool
    member_model_member_type_definable_stiffness: int
    member_model_result_beam_integrate_stresses_and_forces: MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces
    member_model_result_beam_y_z: float
    member_model_result_beam_y_plus: float
    member_model_result_beam_z_plus: float
    member_model_result_beam_y_minus: float
    member_model_result_beam_z_minus: float
    member_model_result_beam_radius: float
    member_model_result_beam_include_surfaces: _containers.RepeatedScalarFieldContainer[int]
    member_model_result_beam_include_all_surfaces: bool
    member_model_result_beam_include_solids: _containers.RepeatedScalarFieldContainer[int]
    member_model_result_beam_include_all_solids: bool
    member_model_result_beam_include_members: _containers.RepeatedScalarFieldContainer[int]
    member_model_result_beam_include_all_members: bool
    member_model_result_beam_exclude_surfaces: _containers.RepeatedScalarFieldContainer[int]
    member_model_result_beam_exclude_solids: _containers.RepeatedScalarFieldContainer[int]
    member_model_result_beam_exclude_members: _containers.RepeatedScalarFieldContainer[int]
    member_model_projected_length: float
    member_model_section_distance_from_start_is_defined_as_relative: bool
    member_model_section_distance_from_start_absolute: float
    member_model_section_distance_from_end_relative: float
    member_model_section_distance_from_end_is_defined_as_relative: bool
    member_model_section_distance_from_end_absolute: float
    member_model_section_distance_from_start_relative: float
    member_model_section_alignment: MemberSetRepresentativeMemberModelSectionAlignment
    member_model_grain_alignment: MemberSetRepresentativeMemberModelGrainAlignment
    member_model_is_curved: bool
    member_model_curved_member_is_asymmetric_layout: bool
    member_model_curved_member_is_cantilevers: bool
    member_model_curved_member_cantilevers_type: MemberSetRepresentativeMemberModelCurvedMemberCantileversType
    member_model_curved_member_is_capped_with_loose_ridge_wedge: bool
    member_model_curved_member_parameters: ArrayOfMemberSetRepresentativeMemberModelCurvedMemberParametersAndChildItems
    member_model_rotation_specification_type: MemberSetRepresentativeMemberModelRotationSpecificationType
    member_model_rotation_angle: float
    member_model_rotation_help_node: int
    member_model_rotation_plane_type: MemberSetRepresentativeMemberModelRotationPlaneType
    member_model_rotation_surface: int
    member_model_rotation_surface_plane_type: MemberSetRepresentativeMemberModelRotationSurfacePlaneType
    member_model_is_rotated: bool
    member_model_section_start: int
    member_model_section_end: int
    member_model_section_internal: int
    member_model_section_material: int
    member_model_member_hinge_start: int
    member_model_member_hinge_end: int
    member_model_member_eccentricity_start: int
    member_model_member_eccentricity_end: int
    member_model_support: int
    member_model_member_transverse_stiffener: int
    member_model_member_openings: int
    member_model_member_nonlinearity: int
    member_model_member_result_intermediate_point: int
    member_model_concrete_effective_lengths: int
    member_model_steel_effective_lengths: int
    member_model_timber_effective_lengths: int
    member_model_aluminum_effective_lengths: int
    member_model_concrete_shear_reinforcement_spans: ArrayOfMemberSetRepresentativeMemberModelConcreteShearReinforcementSpans
    member_model_concrete_longitudinal_reinforcement_items: ArrayOfMemberSetRepresentativeMemberModelConcreteLongitudinalReinforcementItems
    member_model_concrete_cover_user_defined_enabled: bool
    member_model_concrete_cover_different_at_section_sides_enabled: bool
    member_model_concrete_cover: float
    member_model_concrete_cover_top: float
    member_model_concrete_cover_bottom: float
    member_model_concrete_cover_left: float
    member_model_concrete_cover_right: float
    member_model_concrete_cover_min: _containers.RepeatedScalarFieldContainer[int]
    member_model_concrete_cover_min_top: _containers.RepeatedScalarFieldContainer[int]
    member_model_concrete_cover_min_bottom: _containers.RepeatedScalarFieldContainer[int]
    member_model_concrete_cover_min_left: _containers.RepeatedScalarFieldContainer[int]
    member_model_concrete_cover_min_right: _containers.RepeatedScalarFieldContainer[int]
    member_model_concrete_durability: int
    member_model_concrete_durability_top: int
    member_model_concrete_durability_bottom: int
    member_model_concrete_durability_left: int
    member_model_concrete_durability_right: int
    member_model_steel_boundary_conditions: int
    member_model_steel_member_local_section_reduction: int
    member_model_steel_member_transverse_weld: int
    member_model_timber_service_class: int
    member_model_timber_moisture_class: int
    member_model_timber_service_conditions: int
    member_model_timber_member_local_section_reduction: int
    member_model_aluminum_boundary_conditions: int
    member_model_aluminum_member_local_section_reduction: int
    member_model_aluminum_member_transverse_weld: int
    member_model_stress_analysis_configuration: int
    member_model_member_aluminum_design_uls_configuration: int
    member_model_member_aluminum_design_sls_configuration: int
    member_model_member_concrete_design_uls_configuration: int
    member_model_member_concrete_design_sls_configuration: int
    member_model_member_concrete_design_fr_configuration: int
    member_model_member_concrete_design_seismic_configuration: int
    member_model_member_steel_design_uls_configuration: int
    member_model_member_steel_design_sls_configuration: int
    member_model_member_steel_design_fr_configuration: int
    member_model_member_timber_design_uls_configuration: int
    member_model_member_timber_design_sls_configuration: int
    member_model_member_timber_design_fr_configuration: int
    member_model_end_modifications_member_start_extension: float
    member_model_end_modifications_member_start_slope_y: float
    member_model_end_modifications_member_start_slope_z: float
    member_model_end_modifications_member_end_extension: float
    member_model_end_modifications_member_end_slope_y: float
    member_model_end_modifications_member_end_slope_z: float
    member_model_has_any_end_modifications: bool
    member_model_deflection_check_direction: MemberSetRepresentativeMemberModelDeflectionCheckDirection
    member_model_deflection_check_displacement_reference: MemberSetRepresentativeMemberModelDeflectionCheckDisplacementReference
    member_model_design_support_on_member_start: int
    member_model_design_support_on_member_end: int
    member_model_design_supports_on_internal_nodes: ArrayOfMemberSetRepresentativeMemberModelDesignSupportsOnInternalNodes
    member_model_is_generated: bool
    member_model_generating_object_info: str
    member_set_model_no: int
    member_set_model_user_defined_name_enabled: bool
    member_set_model_name: str
    member_set_model_set_type: MemberSetRepresentativeMemberSetModelSetType
    member_set_model_members: _containers.RepeatedScalarFieldContainer[int]
    member_set_model_length: float
    member_set_model_center_of_gravity: _common_pb2.Vector3d
    member_set_model_center_of_gravity_x: float
    member_set_model_center_of_gravity_y: float
    member_set_model_center_of_gravity_z: float
    member_set_model_volume: float
    member_set_model_mass: float
    member_set_model_member_set_representative: int
    member_set_model_discontinuous_torsional_warping: bool
    member_set_model_design_properties_activated: bool
    member_set_model_steel_effective_lengths: int
    member_set_model_steel_boundary_conditions: int
    member_set_model_steel_member_local_section_reductions: int
    member_set_model_member_steel_design_uls_configuration: int
    member_set_model_member_steel_design_sls_configuration: int
    member_set_model_member_steel_design_fr_configuration: int
    member_set_model_member_steel_design_seismic_configuration: int
    member_set_model_aluminum_effective_lengths: int
    member_set_model_aluminum_boundary_conditions: int
    member_set_model_aluminum_member_local_section_reductions: int
    member_set_model_aluminum_member_transverse_weld: int
    member_set_model_member_aluminum_design_uls_configuration: int
    member_set_model_member_aluminum_design_sls_configuration: int
    member_set_model_concrete_shear_reinforcement_spans: ArrayOfMemberSetRepresentativeMemberSetModelConcreteShearReinforcementSpans
    member_set_model_concrete_longitudinal_reinforcement_items: ArrayOfMemberSetRepresentativeMemberSetModelConcreteLongitudinalReinforcementItems
    member_set_model_concrete_cover_user_defined_enabled: bool
    member_set_model_concrete_cover_different_at_section_sides_enabled: bool
    member_set_model_concrete_cover: float
    member_set_model_concrete_cover_top: float
    member_set_model_concrete_cover_bottom: float
    member_set_model_concrete_cover_left: float
    member_set_model_concrete_cover_right: float
    member_set_model_concrete_cover_min: _containers.RepeatedScalarFieldContainer[int]
    member_set_model_concrete_cover_min_top: _containers.RepeatedScalarFieldContainer[int]
    member_set_model_concrete_cover_min_bottom: _containers.RepeatedScalarFieldContainer[int]
    member_set_model_concrete_cover_min_left: _containers.RepeatedScalarFieldContainer[int]
    member_set_model_concrete_cover_min_right: _containers.RepeatedScalarFieldContainer[int]
    member_set_model_concrete_durability: int
    member_set_model_concrete_durability_top: int
    member_set_model_concrete_durability_bottom: int
    member_set_model_concrete_durability_left: int
    member_set_model_concrete_durability_right: int
    member_set_model_concrete_effective_lengths: int
    member_set_model_member_concrete_design_uls_configuration: int
    member_set_model_member_concrete_design_sls_configuration: int
    member_set_model_member_concrete_design_fr_configuration: int
    member_set_model_member_concrete_design_seismic_configuration: int
    member_set_model_service_class_timber_design: int
    member_set_model_moisture_class_timber_design: int
    member_set_model_timber_effective_lengths: int
    member_set_model_service_conditions_timber_design: int
    member_set_model_timber_local_section_reductions: int
    member_set_model_member_timber_design_uls_configuration: int
    member_set_model_member_timber_design_sls_configuration: int
    member_set_model_member_timber_design_fr_configuration: int
    member_set_model_support: int
    member_set_model_member_transverse_stiffener: int
    member_set_model_member_openings: int
    member_set_model_stress_analysis_configuration: int
    member_set_model_deflection_check_direction: MemberSetRepresentativeMemberSetModelDeflectionCheckDirection
    member_set_model_deflection_check_displacement_reference: MemberSetRepresentativeMemberSetModelDeflectionCheckDisplacementReference
    member_set_model_design_support_on_member_set_start: int
    member_set_model_design_support_on_member_set_end: int
    member_set_model_design_supports_on_internal_nodes: ArrayOfMemberSetRepresentativeMemberSetModelDesignSupportsOnInternalNodes
    member_set_model_comment: str
    member_set_model_is_generated: bool
    member_set_model_generating_object_info: str
    member_set_model_member_set_rib_generating_longitudinal_reinforcement_items_from_surfaces_enabled: bool
    member_model_deflection_segments_defined_length_y_axis_enabled: bool
    member_model_deflection_segments_defined_length_z_axis_enabled: bool
    member_model_deflection_segments_y_axis: ArrayOfMemberSetRepresentativeMemberModelDeflectionSegmentsYAxis
    member_model_deflection_segments_z_axis: ArrayOfMemberSetRepresentativeMemberModelDeflectionSegmentsZAxis
    member_set_model_deflection_segments_defined_length_y_axis_enabled: bool
    member_set_model_deflection_segments_defined_length_z_axis_enabled: bool
    member_set_model_deflection_segments_y_axis: ArrayOfMemberSetRepresentativeMemberSetModelDeflectionSegmentsYAxis
    member_set_model_deflection_segments_z_axis: ArrayOfMemberSetRepresentativeMemberSetModelDeflectionSegmentsZAxis
    concrete_longitudinal_reinforcement_span: ArrayOfMemberSetRepresentativeConcreteLongitudinalReinforcementSpan
    concrete_shear_reinforcement_span: ArrayOfMemberSetRepresentativeConcreteShearReinforcementSpan
    id_for_export_import: str
    metadata_for_export_import: str
    def __init__(self, no: _Optional[int] = ..., user_defined_name_enabled: bool = ..., name: _Optional[str] = ..., member_sets: _Optional[_Iterable[int]] = ..., comment: _Optional[str] = ..., number_of_member_sets: _Optional[int] = ..., number_of_members: _Optional[int] = ..., section_ids: _Optional[str] = ..., total_length: _Optional[float] = ..., total_volume: _Optional[float] = ..., total_mass: _Optional[float] = ..., total_surface_of_coating: _Optional[float] = ..., total_center_of_gravity_x: _Optional[float] = ..., total_center_of_gravity_y: _Optional[float] = ..., total_center_of_gravity_z: _Optional[float] = ..., member_model_no: _Optional[int] = ..., member_model_type: _Optional[_Union[MemberSetRepresentativeMemberModelType, str]] = ..., member_model_is_deactivated_for_calculation: bool = ..., member_model_line: _Optional[int] = ..., member_model_section_distribution_type: _Optional[_Union[MemberSetRepresentativeMemberModelSectionDistributionType, str]] = ..., member_model_reference_type: _Optional[_Union[MemberSetRepresentativeMemberModelReferenceType, str]] = ..., member_model_nodes: _Optional[_Iterable[int]] = ..., member_model_node_start: _Optional[int] = ..., member_model_node_end: _Optional[int] = ..., member_model_analytical_length: _Optional[float] = ..., member_model_analytical_volume: _Optional[float] = ..., member_model_analytical_mass: _Optional[float] = ..., member_model_analytical_surface_of_coating: _Optional[float] = ..., member_model_analytical_center_of_gravity: _Optional[_Union[_common_pb2.Vector3d, _Mapping]] = ..., member_model_analytical_center_of_gravity_x: _Optional[float] = ..., member_model_analytical_center_of_gravity_y: _Optional[float] = ..., member_model_analytical_center_of_gravity_z: _Optional[float] = ..., member_model_length: _Optional[float] = ..., member_model_volume: _Optional[float] = ..., member_model_mass: _Optional[float] = ..., member_model_surface_of_coating: _Optional[float] = ..., member_model_center_of_gravity: _Optional[_Union[_common_pb2.Vector3d, _Mapping]] = ..., member_model_center_of_gravity_x: _Optional[float] = ..., member_model_center_of_gravity_y: _Optional[float] = ..., member_model_center_of_gravity_z: _Optional[float] = ..., member_set_model_position: _Optional[str] = ..., member_set_model_position_short: _Optional[str] = ..., member_model_member_representative: _Optional[int] = ..., member_model_design_properties_via_member: bool = ..., member_model_design_properties_via_parent_member_set: bool = ..., member_model_design_properties_parent_member_set: _Optional[int] = ..., member_model_comment: _Optional[str] = ..., member_model_member_type_rib_alignment: _Optional[_Union[MemberSetRepresentativeMemberModelMemberTypeRibAlignment, str]] = ..., member_model_member_rib_first_surface: _Optional[int] = ..., member_model_member_rib_second_surface: _Optional[int] = ..., member_model_member_rib_surface_assignment_autodetect: bool = ..., member_model_member_rib_generating_longitudinal_reinforcement_items_from_surfaces_enabled: bool = ..., member_model_align_local_z_axis_to_local_z_axis_of_surface: bool = ..., member_model_member_rib_shear_joint_between_web_and_flange: bool = ..., member_model_member_rib_surface_roughness_classification: _Optional[_Union[MemberSetRepresentativeMemberModelMemberRibSurfaceRoughnessClassification, str]] = ..., member_model_member_rib_reduction_of_joint_width: _Optional[float] = ..., member_model_flange_dimensions: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberModelFlangeDimensions, _Mapping]] = ..., member_model_synchronize_width_mode: bool = ..., member_model_relative_ordinates_mode: bool = ..., member_model_member_type_definable_stiffness: _Optional[int] = ..., member_model_result_beam_integrate_stresses_and_forces: _Optional[_Union[MemberSetRepresentativeMemberModelResultBeamIntegrateStressesAndForces, str]] = ..., member_model_result_beam_y_z: _Optional[float] = ..., member_model_result_beam_y_plus: _Optional[float] = ..., member_model_result_beam_z_plus: _Optional[float] = ..., member_model_result_beam_y_minus: _Optional[float] = ..., member_model_result_beam_z_minus: _Optional[float] = ..., member_model_result_beam_radius: _Optional[float] = ..., member_model_result_beam_include_surfaces: _Optional[_Iterable[int]] = ..., member_model_result_beam_include_all_surfaces: bool = ..., member_model_result_beam_include_solids: _Optional[_Iterable[int]] = ..., member_model_result_beam_include_all_solids: bool = ..., member_model_result_beam_include_members: _Optional[_Iterable[int]] = ..., member_model_result_beam_include_all_members: bool = ..., member_model_result_beam_exclude_surfaces: _Optional[_Iterable[int]] = ..., member_model_result_beam_exclude_solids: _Optional[_Iterable[int]] = ..., member_model_result_beam_exclude_members: _Optional[_Iterable[int]] = ..., member_model_projected_length: _Optional[float] = ..., member_model_section_distance_from_start_is_defined_as_relative: bool = ..., member_model_section_distance_from_start_absolute: _Optional[float] = ..., member_model_section_distance_from_end_relative: _Optional[float] = ..., member_model_section_distance_from_end_is_defined_as_relative: bool = ..., member_model_section_distance_from_end_absolute: _Optional[float] = ..., member_model_section_distance_from_start_relative: _Optional[float] = ..., member_model_section_alignment: _Optional[_Union[MemberSetRepresentativeMemberModelSectionAlignment, str]] = ..., member_model_grain_alignment: _Optional[_Union[MemberSetRepresentativeMemberModelGrainAlignment, str]] = ..., member_model_is_curved: bool = ..., member_model_curved_member_is_asymmetric_layout: bool = ..., member_model_curved_member_is_cantilevers: bool = ..., member_model_curved_member_cantilevers_type: _Optional[_Union[MemberSetRepresentativeMemberModelCurvedMemberCantileversType, str]] = ..., member_model_curved_member_is_capped_with_loose_ridge_wedge: bool = ..., member_model_curved_member_parameters: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberModelCurvedMemberParametersAndChildItems, _Mapping]] = ..., member_model_rotation_specification_type: _Optional[_Union[MemberSetRepresentativeMemberModelRotationSpecificationType, str]] = ..., member_model_rotation_angle: _Optional[float] = ..., member_model_rotation_help_node: _Optional[int] = ..., member_model_rotation_plane_type: _Optional[_Union[MemberSetRepresentativeMemberModelRotationPlaneType, str]] = ..., member_model_rotation_surface: _Optional[int] = ..., member_model_rotation_surface_plane_type: _Optional[_Union[MemberSetRepresentativeMemberModelRotationSurfacePlaneType, str]] = ..., member_model_is_rotated: bool = ..., member_model_section_start: _Optional[int] = ..., member_model_section_end: _Optional[int] = ..., member_model_section_internal: _Optional[int] = ..., member_model_section_material: _Optional[int] = ..., member_model_member_hinge_start: _Optional[int] = ..., member_model_member_hinge_end: _Optional[int] = ..., member_model_member_eccentricity_start: _Optional[int] = ..., member_model_member_eccentricity_end: _Optional[int] = ..., member_model_support: _Optional[int] = ..., member_model_member_transverse_stiffener: _Optional[int] = ..., member_model_member_openings: _Optional[int] = ..., member_model_member_nonlinearity: _Optional[int] = ..., member_model_member_result_intermediate_point: _Optional[int] = ..., member_model_concrete_effective_lengths: _Optional[int] = ..., member_model_steel_effective_lengths: _Optional[int] = ..., member_model_timber_effective_lengths: _Optional[int] = ..., member_model_aluminum_effective_lengths: _Optional[int] = ..., member_model_concrete_shear_reinforcement_spans: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberModelConcreteShearReinforcementSpans, _Mapping]] = ..., member_model_concrete_longitudinal_reinforcement_items: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberModelConcreteLongitudinalReinforcementItems, _Mapping]] = ..., member_model_concrete_cover_user_defined_enabled: bool = ..., member_model_concrete_cover_different_at_section_sides_enabled: bool = ..., member_model_concrete_cover: _Optional[float] = ..., member_model_concrete_cover_top: _Optional[float] = ..., member_model_concrete_cover_bottom: _Optional[float] = ..., member_model_concrete_cover_left: _Optional[float] = ..., member_model_concrete_cover_right: _Optional[float] = ..., member_model_concrete_cover_min: _Optional[_Iterable[int]] = ..., member_model_concrete_cover_min_top: _Optional[_Iterable[int]] = ..., member_model_concrete_cover_min_bottom: _Optional[_Iterable[int]] = ..., member_model_concrete_cover_min_left: _Optional[_Iterable[int]] = ..., member_model_concrete_cover_min_right: _Optional[_Iterable[int]] = ..., member_model_concrete_durability: _Optional[int] = ..., member_model_concrete_durability_top: _Optional[int] = ..., member_model_concrete_durability_bottom: _Optional[int] = ..., member_model_concrete_durability_left: _Optional[int] = ..., member_model_concrete_durability_right: _Optional[int] = ..., member_model_steel_boundary_conditions: _Optional[int] = ..., member_model_steel_member_local_section_reduction: _Optional[int] = ..., member_model_steel_member_transverse_weld: _Optional[int] = ..., member_model_timber_service_class: _Optional[int] = ..., member_model_timber_moisture_class: _Optional[int] = ..., member_model_timber_service_conditions: _Optional[int] = ..., member_model_timber_member_local_section_reduction: _Optional[int] = ..., member_model_aluminum_boundary_conditions: _Optional[int] = ..., member_model_aluminum_member_local_section_reduction: _Optional[int] = ..., member_model_aluminum_member_transverse_weld: _Optional[int] = ..., member_model_stress_analysis_configuration: _Optional[int] = ..., member_model_member_aluminum_design_uls_configuration: _Optional[int] = ..., member_model_member_aluminum_design_sls_configuration: _Optional[int] = ..., member_model_member_concrete_design_uls_configuration: _Optional[int] = ..., member_model_member_concrete_design_sls_configuration: _Optional[int] = ..., member_model_member_concrete_design_fr_configuration: _Optional[int] = ..., member_model_member_concrete_design_seismic_configuration: _Optional[int] = ..., member_model_member_steel_design_uls_configuration: _Optional[int] = ..., member_model_member_steel_design_sls_configuration: _Optional[int] = ..., member_model_member_steel_design_fr_configuration: _Optional[int] = ..., member_model_member_timber_design_uls_configuration: _Optional[int] = ..., member_model_member_timber_design_sls_configuration: _Optional[int] = ..., member_model_member_timber_design_fr_configuration: _Optional[int] = ..., member_model_end_modifications_member_start_extension: _Optional[float] = ..., member_model_end_modifications_member_start_slope_y: _Optional[float] = ..., member_model_end_modifications_member_start_slope_z: _Optional[float] = ..., member_model_end_modifications_member_end_extension: _Optional[float] = ..., member_model_end_modifications_member_end_slope_y: _Optional[float] = ..., member_model_end_modifications_member_end_slope_z: _Optional[float] = ..., member_model_has_any_end_modifications: bool = ..., member_model_deflection_check_direction: _Optional[_Union[MemberSetRepresentativeMemberModelDeflectionCheckDirection, str]] = ..., member_model_deflection_check_displacement_reference: _Optional[_Union[MemberSetRepresentativeMemberModelDeflectionCheckDisplacementReference, str]] = ..., member_model_design_support_on_member_start: _Optional[int] = ..., member_model_design_support_on_member_end: _Optional[int] = ..., member_model_design_supports_on_internal_nodes: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberModelDesignSupportsOnInternalNodes, _Mapping]] = ..., member_model_is_generated: bool = ..., member_model_generating_object_info: _Optional[str] = ..., member_set_model_no: _Optional[int] = ..., member_set_model_user_defined_name_enabled: bool = ..., member_set_model_name: _Optional[str] = ..., member_set_model_set_type: _Optional[_Union[MemberSetRepresentativeMemberSetModelSetType, str]] = ..., member_set_model_members: _Optional[_Iterable[int]] = ..., member_set_model_length: _Optional[float] = ..., member_set_model_center_of_gravity: _Optional[_Union[_common_pb2.Vector3d, _Mapping]] = ..., member_set_model_center_of_gravity_x: _Optional[float] = ..., member_set_model_center_of_gravity_y: _Optional[float] = ..., member_set_model_center_of_gravity_z: _Optional[float] = ..., member_set_model_volume: _Optional[float] = ..., member_set_model_mass: _Optional[float] = ..., member_set_model_member_set_representative: _Optional[int] = ..., member_set_model_discontinuous_torsional_warping: bool = ..., member_set_model_design_properties_activated: bool = ..., member_set_model_steel_effective_lengths: _Optional[int] = ..., member_set_model_steel_boundary_conditions: _Optional[int] = ..., member_set_model_steel_member_local_section_reductions: _Optional[int] = ..., member_set_model_member_steel_design_uls_configuration: _Optional[int] = ..., member_set_model_member_steel_design_sls_configuration: _Optional[int] = ..., member_set_model_member_steel_design_fr_configuration: _Optional[int] = ..., member_set_model_member_steel_design_seismic_configuration: _Optional[int] = ..., member_set_model_aluminum_effective_lengths: _Optional[int] = ..., member_set_model_aluminum_boundary_conditions: _Optional[int] = ..., member_set_model_aluminum_member_local_section_reductions: _Optional[int] = ..., member_set_model_aluminum_member_transverse_weld: _Optional[int] = ..., member_set_model_member_aluminum_design_uls_configuration: _Optional[int] = ..., member_set_model_member_aluminum_design_sls_configuration: _Optional[int] = ..., member_set_model_concrete_shear_reinforcement_spans: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberSetModelConcreteShearReinforcementSpans, _Mapping]] = ..., member_set_model_concrete_longitudinal_reinforcement_items: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberSetModelConcreteLongitudinalReinforcementItems, _Mapping]] = ..., member_set_model_concrete_cover_user_defined_enabled: bool = ..., member_set_model_concrete_cover_different_at_section_sides_enabled: bool = ..., member_set_model_concrete_cover: _Optional[float] = ..., member_set_model_concrete_cover_top: _Optional[float] = ..., member_set_model_concrete_cover_bottom: _Optional[float] = ..., member_set_model_concrete_cover_left: _Optional[float] = ..., member_set_model_concrete_cover_right: _Optional[float] = ..., member_set_model_concrete_cover_min: _Optional[_Iterable[int]] = ..., member_set_model_concrete_cover_min_top: _Optional[_Iterable[int]] = ..., member_set_model_concrete_cover_min_bottom: _Optional[_Iterable[int]] = ..., member_set_model_concrete_cover_min_left: _Optional[_Iterable[int]] = ..., member_set_model_concrete_cover_min_right: _Optional[_Iterable[int]] = ..., member_set_model_concrete_durability: _Optional[int] = ..., member_set_model_concrete_durability_top: _Optional[int] = ..., member_set_model_concrete_durability_bottom: _Optional[int] = ..., member_set_model_concrete_durability_left: _Optional[int] = ..., member_set_model_concrete_durability_right: _Optional[int] = ..., member_set_model_concrete_effective_lengths: _Optional[int] = ..., member_set_model_member_concrete_design_uls_configuration: _Optional[int] = ..., member_set_model_member_concrete_design_sls_configuration: _Optional[int] = ..., member_set_model_member_concrete_design_fr_configuration: _Optional[int] = ..., member_set_model_member_concrete_design_seismic_configuration: _Optional[int] = ..., member_set_model_service_class_timber_design: _Optional[int] = ..., member_set_model_moisture_class_timber_design: _Optional[int] = ..., member_set_model_timber_effective_lengths: _Optional[int] = ..., member_set_model_service_conditions_timber_design: _Optional[int] = ..., member_set_model_timber_local_section_reductions: _Optional[int] = ..., member_set_model_member_timber_design_uls_configuration: _Optional[int] = ..., member_set_model_member_timber_design_sls_configuration: _Optional[int] = ..., member_set_model_member_timber_design_fr_configuration: _Optional[int] = ..., member_set_model_support: _Optional[int] = ..., member_set_model_member_transverse_stiffener: _Optional[int] = ..., member_set_model_member_openings: _Optional[int] = ..., member_set_model_stress_analysis_configuration: _Optional[int] = ..., member_set_model_deflection_check_direction: _Optional[_Union[MemberSetRepresentativeMemberSetModelDeflectionCheckDirection, str]] = ..., member_set_model_deflection_check_displacement_reference: _Optional[_Union[MemberSetRepresentativeMemberSetModelDeflectionCheckDisplacementReference, str]] = ..., member_set_model_design_support_on_member_set_start: _Optional[int] = ..., member_set_model_design_support_on_member_set_end: _Optional[int] = ..., member_set_model_design_supports_on_internal_nodes: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberSetModelDesignSupportsOnInternalNodes, _Mapping]] = ..., member_set_model_comment: _Optional[str] = ..., member_set_model_is_generated: bool = ..., member_set_model_generating_object_info: _Optional[str] = ..., member_set_model_member_set_rib_generating_longitudinal_reinforcement_items_from_surfaces_enabled: bool = ..., member_model_deflection_segments_defined_length_y_axis_enabled: bool = ..., member_model_deflection_segments_defined_length_z_axis_enabled: bool = ..., member_model_deflection_segments_y_axis: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberModelDeflectionSegmentsYAxis, _Mapping]] = ..., member_model_deflection_segments_z_axis: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberModelDeflectionSegmentsZAxis, _Mapping]] = ..., member_set_model_deflection_segments_defined_length_y_axis_enabled: bool = ..., member_set_model_deflection_segments_defined_length_z_axis_enabled: bool = ..., member_set_model_deflection_segments_y_axis: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberSetModelDeflectionSegmentsYAxis, _Mapping]] = ..., member_set_model_deflection_segments_z_axis: _Optional[_Union[ArrayOfMemberSetRepresentativeMemberSetModelDeflectionSegmentsZAxis, _Mapping]] = ..., concrete_longitudinal_reinforcement_span: _Optional[_Union[ArrayOfMemberSetRepresentativeConcreteLongitudinalReinforcementSpan, _Mapping]] = ..., concrete_shear_reinforcement_span: _Optional[_Union[ArrayOfMemberSetRepresentativeConcreteShearReinforcementSpan, _Mapping]] = ..., id_for_export_import: _Optional[str] = ..., metadata_for_export_import: _Optional[str] = ...) -> None: ...

class ArrayOfMemberSetRepresentativeMemberModelFlangeDimensions(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberModelCurvedMemberParametersAndChildItems(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberModelConcreteShearReinforcementSpans(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberModelConcreteLongitudinalReinforcementItems(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberModelDesignSupportsOnInternalNodes(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberSetModelConcreteShearReinforcementSpans(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberSetModelConcreteLongitudinalReinforcementItems(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberSetModelDesignSupportsOnInternalNodes(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberModelDeflectionSegmentsYAxis(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberModelDeflectionSegmentsZAxis(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberSetModelDeflectionSegmentsYAxis(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeMemberSetModelDeflectionSegmentsZAxis(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeConcreteLongitudinalReinforcementSpan(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ArrayOfMemberSetRepresentativeConcreteShearReinforcementSpan(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...
