# coding: utf-8

"""
    Lead Scraping Service API

    Vector Lead Scraping Service API - Manages Lead Scraping Jobs

    The version of the OpenAPI document: 1.0
    Contact: yoanyomba@vector.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_backend_client_sdk.models.signature_block import SignatureBlock

class TestSignatureBlock(unittest.TestCase):
    """SignatureBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignatureBlock:
        """Test SignatureBlock
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignatureBlock`
        """
        model = SignatureBlock()
        if include_optional:
            return SignatureBlock(
                id = '',
                request_id = '',
                block_type = '',
                page_number = 56,
                x_position = 1.337,
                y_position = 1.337,
                width = 1.337,
                height = 1.337,
                is_required = True,
                signature_data = '',
                signed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SignatureBlock(
        )
        """

    def testSignatureBlock(self):
        """Test SignatureBlock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
