# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.stream_subscription_post_request_type import StreamSubscriptionPostRequestType

class TestStreamSubscriptionPostRequestType(unittest.TestCase):
    """StreamSubscriptionPostRequestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamSubscriptionPostRequestType(self):
        """Test StreamSubscriptionPostRequestType"""
        # inst = StreamSubscriptionPostRequestType()

if __name__ == '__main__':
    unittest.main()
