# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.marketplace_subscription import MarketplaceSubscription

class TestMarketplaceSubscription(unittest.TestCase):
    """MarketplaceSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceSubscription:
        """Test MarketplaceSubscription
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceSubscription`
        """
        model = MarketplaceSubscription()
        if include_optional:
            return MarketplaceSubscription(
                href = 'https://api.equinix.com/fabric/v4/marketplaceSubscriptions/20d32a80-0d61-4333-bc03-707b591ae2f5',
                type = 'AWS_MARKETPLACE_SUBSCRIPTION',
                uuid = '20d32a80-0d61-4333-bc03-707b591ae2f5'
            )
        else:
            return MarketplaceSubscription(
        )
        """

    def testMarketplaceSubscription(self):
        """Test MarketplaceSubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
