# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.cloud_router_change_status import CloudRouterChangeStatus

class TestCloudRouterChangeStatus(unittest.TestCase):
    """CloudRouterChangeStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudRouterChangeStatus(self):
        """Test CloudRouterChangeStatus"""
        # inst = CloudRouterChangeStatus()

if __name__ == '__main__':
    unittest.main()
