# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.api.ports_api import PortsApi


class TestPortsApi(unittest.TestCase):
    """PortsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortsApi()

    def tearDown(self) -> None:
        pass

    def test_add_to_lag(self) -> None:
        """Test case for add_to_lag

        Add to Lag
        """
        pass

    def test_create_bulk_port(self) -> None:
        """Test case for create_bulk_port

        Create Port
        """
        pass

    def test_create_port(self) -> None:
        """Test case for create_port

        Create Port
        """
        pass

    def test_delete_port(self) -> None:
        """Test case for delete_port

        Delete a single port
        """
        pass

    def test_get_port_by_uuid(self) -> None:
        """Test case for get_port_by_uuid

        Get Port by uuid
        """
        pass

    def test_get_ports(self) -> None:
        """Test case for get_ports

        Get All Ports
        """
        pass

    def test_get_vlans(self) -> None:
        """Test case for get_vlans

        Get Vlans
        """
        pass

    def test_search_ports(self) -> None:
        """Test case for search_ports

        Search ports
        """
        pass

    def test_update_port_by_uuid(self) -> None:
        """Test case for update_port_by_uuid

        Update by UUID
        """
        pass


if __name__ == '__main__':
    unittest.main()
