# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.route_aggregations_base_type import RouteAggregationsBaseType

class TestRouteAggregationsBaseType(unittest.TestCase):
    """RouteAggregationsBaseType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRouteAggregationsBaseType(self):
        """Test RouteAggregationsBaseType"""
        # inst = RouteAggregationsBaseType()

if __name__ == '__main__':
    unittest.main()
