# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.stream_put_request import StreamPutRequest

class TestStreamPutRequest(unittest.TestCase):
    """StreamPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamPutRequest:
        """Test StreamPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamPutRequest`
        """
        model = StreamPutRequest()
        if include_optional:
            return StreamPutRequest(
                name = '',
                description = ''
            )
        else:
            return StreamPutRequest(
        )
        """

    def testStreamPutRequest(self):
        """Test StreamPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
