# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.route_table_entry_filter import RouteTableEntryFilter

class TestRouteTableEntryFilter(unittest.TestCase):
    """RouteTableEntryFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RouteTableEntryFilter:
        """Test RouteTableEntryFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RouteTableEntryFilter`
        """
        model = RouteTableEntryFilter()
        if include_optional:
            return RouteTableEntryFilter(
                var_property = '/type',
                operator = '=',
                values = [
                    'IPv4_BGP_ROUTE'
                    ],
                var_or = [
                    equinix.services.fabricv4.models.route_table_entry_simple_expression.RouteTableEntrySimpleExpression(
                        property = '/type', 
                        operator = '=', 
                        values = [
                            'IPv4_BGP_ROUTE'
                            ], )
                    ]
            )
        else:
            return RouteTableEntryFilter(
        )
        """

    def testRouteTableEntryFilter(self):
        """Test RouteTableEntryFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
