# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.package_code import PackageCode

class TestPackageCode(unittest.TestCase):
    """PackageCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageCode(self):
        """Test PackageCode"""
        # inst = PackageCode()

if __name__ == '__main__':
    unittest.main()
