# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.search_field_name import SearchFieldName

class TestSearchFieldName(unittest.TestCase):
    """SearchFieldName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchFieldName(self):
        """Test SearchFieldName"""
        # inst = SearchFieldName()

if __name__ == '__main__':
    unittest.main()
