# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.time_service_price_connection_a_side import TimeServicePriceConnectionASide

class TestTimeServicePriceConnectionASide(unittest.TestCase):
    """TimeServicePriceConnectionASide unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeServicePriceConnectionASide:
        """Test TimeServicePriceConnectionASide
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeServicePriceConnectionASide`
        """
        model = TimeServicePriceConnectionASide()
        if include_optional:
            return TimeServicePriceConnectionASide(
                access_point = equinix.services.fabricv4.models.time_service_price_connection_access_point.TimeServicePriceConnectionAccessPoint(
                    location = equinix.services.fabricv4.models.price_location.PriceLocation(
                        metro_code = '', 
                        ibx = '', ), )
            )
        else:
            return TimeServicePriceConnectionASide(
        )
        """

    def testTimeServicePriceConnectionASide(self):
        """Test TimeServicePriceConnectionASide"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
