# (generated with --quick)

import datetime
from typing import Any

def _get_duration_components(duration) -> tuple[Any, Any, Any, Any, Any]: ...
def duration_iso_string(duration) -> str: ...
def duration_microseconds(delta) -> Any: ...
def duration_string(duration) -> str: ...
