pipenv run pip install -U setuptools
pipenv run pip install -U wheel
pipenv run pip install -U scikit-learn
pipenv run pip install -U matplotlib
pipenv run pip install -U tqdm
pipenv run pip install -U pytesseract
pipenv run pip install -U pillow>=10.1.0
pipenv run pip install -U jax>=0.4.38
pipenv run pip install -U jaxlib>=0.4.38
pipenv run pip install -U mediapipe
pipenv run pip install -U opencv-python
pipenv run pip install -U pandas
pipenv run pip install -U tensorrt
pipenv run pip install -U tensorrt-lean
pipenv run pip install -U tensorrt-dispatch
pipenv run pip install -U tensorflow[and_cuda]
pipenv run pip install -U tf-keras
pipenv run pip install -U tensorflow-hub
pipenv run pip install -U sentence_transformers
pipenv run pip install -U spacy[cuda12x]
pipenv run pip install -U ocrmypdf
pipenv run pip install -U easyocr
pipenv run pip install -U pdf2image
pipenv run pip install -U pdfplumber
pipenv run pip install -U langchain-community
pipenv run pip install -U pymongo
pipenv run pip install -U nvidia-cudnn-cu12
python -m spacy download fr_core_news_lg
