from enum import StrEnum


class TaskType(StrEnum):
    TURNSTILE_PROXYLESS = "TurnstileTaskProxyless"
    TURNSTILE = "TurnstileTask"
    RECAPTCHA_V2_TASK_PROXYLESS = "RecaptchaV2TaskProxyless"
    RECAPTCHA_V2_TASK = "RecaptchaV2Task"
    RECAPTCHA_V3_TASK_PROXYLESS = "RecaptchaV3TaskProxyless"
    RECAPTCHA_V2_ENTERPRISE_TASK_PROXYLESS = "RecaptchaV2EnterpriseTaskProxyless"
    RECAPTCHA_V2_ENTERPRISE_TASK = "RecaptchaV2EnterpriseTask"
    FUNCAPTCHA_TASK_PROXYLESS = "FunCaptchaTaskProxyless"
    FUNCAPTCHA_TASK = "FunCaptchaTask"
    GEETEST_TASK_PROXYLESS = "GeeTestTaskProxyless"
    GEETEST_TASK = "GeeTestTask"
    CAPY_TASK_PROXYLESS = "CapyTaskProxyless"
    CAPY_TASK = "CapyTask"
    KEYCAPTCHA_TASK_PROXYLESS = "KeyCaptchaTaskProxyless"
    KEYCAPTCHA_TASK = "KeyCaptchaTask"
    LEMIN_TASK_PROXYLESS = "LeminTaskProxyless"
    LEMIN_TASK = "LeminTask"
    AMAZON_TASK_PROXYLESS = "AmazonTaskProxyless"
    AMAZON_TASK = "AmazonTask"
    ANTICYBERSIARA_TASK = "AntiCyberSiAraTask"
    ANTICYBERSIARA_TASK_PROXYLESS = "AntiCyberSiAraTaskProxyless"
    MTCAPTCHA_TASK_PROXYLESS = "MtCaptchaTaskProxyless"
    MTCAPTCHA_TASK = "MtCaptchaTask"
    CUTCAPTCHA_TASK_PROXYLESS = "CutCaptchaTaskProxyless"
    CUTCAPTCHA_TASK = "CutCaptchaTask"
    FRIENDLYCAPTCHA_TASK_PROXYLESS = "FriendlyCaptchaTaskProxyless"
    FRIENDLYCAPTCHA_TASK = "FriendlyCaptchaTask"
    DATADOME_SLIDER_TASK = "DataDomeSliderTask"
    ATB_CAPTCHA_TASK_PROXYLESS = "AtbCaptchaTaskProxyless"
    ATB_CAPTCHA_TASK = "AtbCaptchaTask"
    TENCENT_TASK_PROXYLESS = "TencentTaskProxyless"
    TENCENT_TASK = "TencentTask"
    PROSOPO_TASK_PROXYLESS = "ProsopoTaskProxyless"
    PROSOPO_TASK = "ProsopoTask"

    IMAGE_TO_TEXT_TASK = "ImageToTextTask"
    TEXT_CAPTCHA_TASK = "TextCaptchaTask"
    COORDINATES = "CoordinatesTask"
    ROTATE_TASK = "RotateTask"
    GRID_TASK = "GridTask"
    DRAW_AROUND_TASK = "DrawAroundTask"
    BOUNDING_BOX_TASK = "BoundingBoxTask"
    AUDIO_TASK = "AudioTask"
