# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.request_termination201_response import RequestTermination201Response

class TestRequestTermination201Response(unittest.TestCase):
    """RequestTermination201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestTermination201Response:
        """Test RequestTermination201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestTermination201Response`
        """
        model = RequestTermination201Response()
        if include_optional:
            return RequestTermination201Response(
                data = dima_test_sdk.models.request_termination_201_response_data.requestTermination_201_response_data(
                    id = '6f50539e-9f62-45d0-a42e-62a62fbb984a', 
                    last_date_of_work = '2022-05-24T09:38:46.235Z', )
            )
        else:
            return RequestTermination201Response(
                data = dima_test_sdk.models.request_termination_201_response_data.requestTermination_201_response_data(
                    id = '6f50539e-9f62-45d0-a42e-62a62fbb984a', 
                    last_date_of_work = '2022-05-24T09:38:46.235Z', ),
        )
        """

    def testRequestTermination201Response(self):
        """Test RequestTermination201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
