# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.bank_account_added import BankAccountAdded

class TestBankAccountAdded(unittest.TestCase):
    """BankAccountAdded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankAccountAdded:
        """Test BankAccountAdded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankAccountAdded`
        """
        model = BankAccountAdded()
        if include_optional:
            return BankAccountAdded(
                id = 'dcc7b587-2246-4909-853e-12056e90c451',
                status = 'new',
                created_at = '2022-05-24T09:38:46.235Z',
                updated_at = '2022-05-24T09:38:46.235Z'
            )
        else:
            return BankAccountAdded(
        )
        """

    def testBankAccountAdded(self):
        """Test BankAccountAdded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
