# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.invite_team_member_to_sign import InviteTeamMemberToSign

class TestInviteTeamMemberToSign(unittest.TestCase):
    """InviteTeamMemberToSign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteTeamMemberToSign:
        """Test InviteTeamMemberToSign
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteTeamMemberToSign`
        """
        model = InviteTeamMemberToSign()
        if include_optional:
            return InviteTeamMemberToSign(
                contract_oid = '',
                contract_name = '',
                invitee_id = 1.337,
                invitee_name = ''
            )
        else:
            return InviteTeamMemberToSign(
                contract_oid = '',
                contract_name = '',
                invitee_id = 1.337,
                invitee_name = '',
        )
        """

    def testInviteTeamMemberToSign(self):
        """Test InviteTeamMemberToSign"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
