# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.gp_employee_address_updated import GPEmployeeAddressUpdated

class TestGPEmployeeAddressUpdated(unittest.TestCase):
    """GPEmployeeAddressUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GPEmployeeAddressUpdated:
        """Test GPEmployeeAddressUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GPEmployeeAddressUpdated`
        """
        model = GPEmployeeAddressUpdated()
        if include_optional:
            return GPEmployeeAddressUpdated(
                country = 'US',
                state = 'CO',
                city = 'Denver',
                street = '123 Deel Street',
                zip = '12345',
                updated_at = '2022-05-24T09:38:46.235Z'
            )
        else:
            return GPEmployeeAddressUpdated(
        )
        """

    def testGPEmployeeAddressUpdated(self):
        """Test GPEmployeeAddressUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
