# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.create_eor_contract_request_data_compensation_details import CreateEorContractRequestDataCompensationDetails

class TestCreateEorContractRequestDataCompensationDetails(unittest.TestCase):
    """CreateEorContractRequestDataCompensationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEorContractRequestDataCompensationDetails:
        """Test CreateEorContractRequestDataCompensationDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEorContractRequestDataCompensationDetails`
        """
        model = CreateEorContractRequestDataCompensationDetails()
        if include_optional:
            return CreateEorContractRequestDataCompensationDetails(
                salary = 100000,
                currency = 'USD',
                variable_compensation = 1.337,
                variable_compensation_type = 'PERCENTAGE'
            )
        else:
            return CreateEorContractRequestDataCompensationDetails(
                currency = 'USD',
        )
        """

    def testCreateEorContractRequestDataCompensationDetails(self):
        """Test CreateEorContractRequestDataCompensationDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
