# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.contract_search_form_with_cursor import ContractSearchFormWithCursor

class TestContractSearchFormWithCursor(unittest.TestCase):
    """ContractSearchFormWithCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractSearchFormWithCursor:
        """Test ContractSearchFormWithCursor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractSearchFormWithCursor`
        """
        model = ContractSearchFormWithCursor()
        if include_optional:
            return ContractSearchFormWithCursor(
                after_cursor = '',
                limit = '10'
            )
        else:
            return ContractSearchFormWithCursor(
        )
        """

    def testContractSearchFormWithCursor(self):
        """Test ContractSearchFormWithCursor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
