# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.invoice_download_container import InvoiceDownloadContainer

class TestInvoiceDownloadContainer(unittest.TestCase):
    """InvoiceDownloadContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceDownloadContainer:
        """Test InvoiceDownloadContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceDownloadContainer`
        """
        model = InvoiceDownloadContainer()
        if include_optional:
            return InvoiceDownloadContainer(
                data = dima_test_sdk.models.invoice_download_object.InvoiceDownloadObject(
                    url = 'https://s3URL/letsdeel.com/invoices/12345.pdf', )
            )
        else:
            return InvoiceDownloadContainer(
                data = dima_test_sdk.models.invoice_download_object.InvoiceDownloadObject(
                    url = 'https://s3URL/letsdeel.com/invoices/12345.pdf', ),
        )
        """

    def testInvoiceDownloadContainer(self):
        """Test InvoiceDownloadContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
