# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.create_worker_relation_container_data import CreateWorkerRelationContainerData

class TestCreateWorkerRelationContainerData(unittest.TestCase):
    """CreateWorkerRelationContainerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkerRelationContainerData:
        """Test CreateWorkerRelationContainerData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkerRelationContainerData`
        """
        model = CreateWorkerRelationContainerData()
        if include_optional:
            return CreateWorkerRelationContainerData(
                parent_hris_profile_id = '2612dbba-9cf0-4273-bb36-aeb7d0a54676',
                child_hris_profile_ids = ["2612dbba-9cf0-4273-bb36-aeb7d0a54676"],
                hris_relationship_type_id = '2612dbba-9cf0-4273-bb36-aeb7d0a54676'
            )
        else:
            return CreateWorkerRelationContainerData(
                parent_hris_profile_id = '2612dbba-9cf0-4273-bb36-aeb7d0a54676',
                child_hris_profile_ids = ["2612dbba-9cf0-4273-bb36-aeb7d0a54676"],
                hris_relationship_type_id = '2612dbba-9cf0-4273-bb36-aeb7d0a54676',
        )
        """

    def testCreateWorkerRelationContainerData(self):
        """Test CreateWorkerRelationContainerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
