# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.update_gp_employee_pto_request_data import UpdateGPEmployeePtoRequestData

class TestUpdateGPEmployeePtoRequestData(unittest.TestCase):
    """UpdateGPEmployeePtoRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateGPEmployeePtoRequestData:
        """Test UpdateGPEmployeePtoRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateGPEmployeePtoRequestData`
        """
        model = UpdateGPEmployeePtoRequestData()
        if include_optional:
            return UpdateGPEmployeePtoRequestData(
                yearly_allowance = '15',
                accrual_start_date = 'Fri Dec 31 01:00:00 CET 1999'
            )
        else:
            return UpdateGPEmployeePtoRequestData(
                yearly_allowance = '15',
                accrual_start_date = 'Fri Dec 31 01:00:00 CET 1999',
        )
        """

    def testUpdateGPEmployeePtoRequestData(self):
        """Test UpdateGPEmployeePtoRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
