# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.people_personal_container_data import PeoplePersonalContainerData

class TestPeoplePersonalContainerData(unittest.TestCase):
    """PeoplePersonalContainerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeoplePersonalContainerData:
        """Test PeoplePersonalContainerData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeoplePersonalContainerData`
        """
        model = PeoplePersonalContainerData()
        if include_optional:
            return PeoplePersonalContainerData(
                legal_first_name = '',
                legal_last_name = '',
                preferred_name = '',
                personal_email = '',
                work_email = '',
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                phone_numbers = [
                    dima_test_sdk.models.people_personal_container_data_phone_numbers_inner.PeoplePersonalContainer_data_phone_numbers_inner(
                        type = 'PERSONAL', 
                        phone_number = '', 
                        dial_code = '', )
                    ],
                nationalities = [
                    dima_test_sdk.models.people_personal_container_data_nationalities_inner.PeoplePersonalContainer_data_nationalities_inner(
                        code = '', 
                        name = '', )
                    ],
                emergency_contacts = [
                    dima_test_sdk.models.people_personal_container_data_emergency_contacts_inner.PeoplePersonalContainer_data_emergency_contacts_inner(
                        id = '', 
                        name = '', 
                        relationship = '', 
                        phone = '', 
                        email = '', 
                        preferred_language = dima_test_sdk.models.people_personal_container_data_emergency_contacts_inner_preferred_language.PeoplePersonalContainer_data_emergency_contacts_inner_preferred_language(
                            id = 1.337, 
                            language = '', ), )
                    ],
                addresses = [
                    dima_test_sdk.models.people_personal_container_data_addresses_inner.PeoplePersonalContainer_data_addresses_inner(
                        id = '', 
                        type = 'HOME', 
                        street = '', 
                        city = '', 
                        state = '', 
                        country = '', 
                        zip = '', )
                    ],
                demographics = dima_test_sdk.models.people_personal_container_data_demographics.PeoplePersonalContainer_data_demographics(
                    gender = dima_test_sdk.models.people_personal_container_data_demographics_gender.PeoplePersonalContainer_data_demographics_gender(
                        id = '', 
                        name = '', 
                        other_name = '', ), 
                    ethnicity = dima_test_sdk.models.people_personal_container_data_demographics_ethnicity.PeoplePersonalContainer_data_demographics_ethnicity(
                        id = '', 
                        name = '', 
                        other_name = '', ), ),
                kyc = dima_test_sdk.models.people_personal_container_data_kyc.PeoplePersonalContainer_data_kyc(
                    is_kyc_approved = True, 
                    kyc_approval_date = '', ),
                ooo = dima_test_sdk.models.people_personal_container_data_ooo.PeoplePersonalContainer_data_ooo(
                    leave_type = 'LONG_TERM_LEAVE', 
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    name = '', )
            )
        else:
            return PeoplePersonalContainerData(
                legal_first_name = '',
                legal_last_name = '',
                preferred_name = '',
                personal_email = '',
                work_email = '',
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                phone_numbers = [
                    dima_test_sdk.models.people_personal_container_data_phone_numbers_inner.PeoplePersonalContainer_data_phone_numbers_inner(
                        type = 'PERSONAL', 
                        phone_number = '', 
                        dial_code = '', )
                    ],
                nationalities = [
                    dima_test_sdk.models.people_personal_container_data_nationalities_inner.PeoplePersonalContainer_data_nationalities_inner(
                        code = '', 
                        name = '', )
                    ],
                emergency_contacts = [
                    dima_test_sdk.models.people_personal_container_data_emergency_contacts_inner.PeoplePersonalContainer_data_emergency_contacts_inner(
                        id = '', 
                        name = '', 
                        relationship = '', 
                        phone = '', 
                        email = '', 
                        preferred_language = dima_test_sdk.models.people_personal_container_data_emergency_contacts_inner_preferred_language.PeoplePersonalContainer_data_emergency_contacts_inner_preferred_language(
                            id = 1.337, 
                            language = '', ), )
                    ],
                addresses = [
                    dima_test_sdk.models.people_personal_container_data_addresses_inner.PeoplePersonalContainer_data_addresses_inner(
                        id = '', 
                        type = 'HOME', 
                        street = '', 
                        city = '', 
                        state = '', 
                        country = '', 
                        zip = '', )
                    ],
                demographics = dima_test_sdk.models.people_personal_container_data_demographics.PeoplePersonalContainer_data_demographics(
                    gender = dima_test_sdk.models.people_personal_container_data_demographics_gender.PeoplePersonalContainer_data_demographics_gender(
                        id = '', 
                        name = '', 
                        other_name = '', ), 
                    ethnicity = dima_test_sdk.models.people_personal_container_data_demographics_ethnicity.PeoplePersonalContainer_data_demographics_ethnicity(
                        id = '', 
                        name = '', 
                        other_name = '', ), ),
        )
        """

    def testPeoplePersonalContainerData(self):
        """Test PeoplePersonalContainerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
