# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.api.carta_api import CartaApi


class TestCartaApi(unittest.TestCase):
    """CartaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CartaApi()

    def tearDown(self) -> None:
        pass

    def test_get_equity_stakeholders(self) -> None:
        """Test case for get_equity_stakeholders

        Retrieve stakeholders
        """
        pass


if __name__ == '__main__':
    unittest.main()
