# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.get_year_to_date_pay200_response import GetYearToDatePay200Response

class TestGetYearToDatePay200Response(unittest.TestCase):
    """GetYearToDatePay200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetYearToDatePay200Response:
        """Test GetYearToDatePay200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetYearToDatePay200Response`
        """
        model = GetYearToDatePay200Response()
        if include_optional:
            return GetYearToDatePay200Response(
                end_date = 'Fri Jan 15 01:00:00 CET 2021',
                employees = [
                    dima_test_sdk.models.get_year_to_date_pay_200_response_employees_inner.getYearToDatePay_200_response_employees_inner(
                        gross_pay = 1000, 
                        contract_id = '123', 
                        employee_id = '123e4567-e89b-12d3-a456-426614174000', 
                        hours_worked = 40, 
                        contributions = [
                            dima_test_sdk.models.get_year_to_date_pay_200_response_employees_inner_contributions_inner.getYearToDatePay_200_response_employees_inner_contributions_inner(
                                name = '401k', 
                                type = 'roth', 
                                amount = 10, )
                            ], 
                        employer_contributions = [
                            dima_test_sdk.models.get_year_to_date_pay_200_response_employees_inner_employer_contributions_inner.getYearToDatePay_200_response_employees_inner_employer_contributions_inner(
                                name = '401k', 
                                type = 'match_rate', 
                                amount = 10, )
                            ], )
                    ],
                start_date = 'Fri Jan 01 01:00:00 CET 2021'
            )
        else:
            return GetYearToDatePay200Response(
        )
        """

    def testGetYearToDatePay200Response(self):
        """Test GetYearToDatePay200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
