# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.basic_timesheet_payment_cycle import BasicTimesheetPaymentCycle

class TestBasicTimesheetPaymentCycle(unittest.TestCase):
    """BasicTimesheetPaymentCycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BasicTimesheetPaymentCycle:
        """Test BasicTimesheetPaymentCycle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BasicTimesheetPaymentCycle`
        """
        model = BasicTimesheetPaymentCycle()
        if include_optional:
            return BasicTimesheetPaymentCycle(
                start_date = '2022-05-24T09:38:46.235Z',
                end_date = '2022-05-24T09:38:46.235Z'
            )
        else:
            return BasicTimesheetPaymentCycle(
        )
        """

    def testBasicTimesheetPaymentCycle(self):
        """Test BasicTimesheetPaymentCycle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
