# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.api.consent_api import ConsentApi


class TestConsentApi(unittest.TestCase):
    """ConsentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConsentApi()

    def tearDown(self) -> None:
        pass

    def test_create_consent_token(self) -> None:
        """Test case for create_consent_token

        Create a consent token
        """
        pass


if __name__ == '__main__':
    unittest.main()
