# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.get_payout_methods200_response_data_address import GetPayoutMethods200ResponseDataAddress

class TestGetPayoutMethods200ResponseDataAddress(unittest.TestCase):
    """GetPayoutMethods200ResponseDataAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPayoutMethods200ResponseDataAddress:
        """Test GetPayoutMethods200ResponseDataAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPayoutMethods200ResponseDataAddress`
        """
        model = GetPayoutMethods200ResponseDataAddress()
        if include_optional:
            return GetPayoutMethods200ResponseDataAddress(
                city = 'San Francisco',
                state = 'CA',
                country = 'US',
                post_code = '210000',
                first_line = 'First Line'
            )
        else:
            return GetPayoutMethods200ResponseDataAddress(
                city = 'San Francisco',
                country = 'US',
                post_code = '210000',
                first_line = 'First Line',
        )
        """

    def testGetPayoutMethods200ResponseDataAddress(self):
        """Test GetPayoutMethods200ResponseDataAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
