# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.create_gp_contract201_response_data import CreateGPContract201ResponseData

class TestCreateGPContract201ResponseData(unittest.TestCase):
    """CreateGPContract201ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateGPContract201ResponseData:
        """Test CreateGPContract201ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateGPContract201ResponseData`
        """
        model = CreateGPContract201ResponseData()
        if include_optional:
            return CreateGPContract201ResponseData(
                id = '',
                type = 'ongoing_time_based',
                client = dima_test_sdk.models.create_gp_contract_201_response_data_client.createGPContract_201_response_data_client(
                    legal_entity = dima_test_sdk.models.create_gp_contract_201_response_data_client_legal_entity.createGPContract_201_response_data_client_legal_entity(
                        name = '', ), ),
                status = 'new',
                employee = dima_test_sdk.models.create_gp_contract_201_response_data_employee.createGPContract_201_response_data_employee(
                    email = '', 
                    last_name = '', 
                    first_name = '', 
                    employee_number = '', ),
                job_title = 'Designer',
                created_at = '2022-05-24T09:38:46.235Z',
                employment = dima_test_sdk.models.create_gp_contract_201_response_data_employment.createGPContract_201_response_data_employment(
                    type = '', 
                    state = '', 
                    country = '', 
                    end_date = '2022-05-24T09:38:46.235Z', 
                    holidays = dima_test_sdk.models.create_gp_contract_201_response_data_employment_holidays.createGPContract_201_response_data_employment_holidays(
                        allowance = 1.337, 
                        start_date = '2022-05-24T09:38:46.235Z', ), 
                    start_date = '2022-05-24T09:38:46.235Z', 
                    work_visa_required = True, ),
                compensation_details = dima_test_sdk.models.create_gp_contract_201_response_data_compensation_details.createGPContract_201_response_data_compensation_details(
                    scale = '', 
                    salary = 1.337, 
                    currency = '', )
            )
        else:
            return CreateGPContract201ResponseData(
        )
        """

    def testCreateGPContract201ResponseData(self):
        """Test CreateGPContract201ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
