# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.legal_entity_list_container import LegalEntityListContainer

class TestLegalEntityListContainer(unittest.TestCase):
    """LegalEntityListContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LegalEntityListContainer:
        """Test LegalEntityListContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LegalEntityListContainer`
        """
        model = LegalEntityListContainer()
        if include_optional:
            return LegalEntityListContainer(
                data = [
                    dima_test_sdk.models.basic_legal_entity.BasicLegalEntity(
                        id = '00000000-0000-0000-0000-000000000000', 
                        name = '', 
                        country = '', 
                        entity_type = 'individual', 
                        entity_subtype = '', )
                    ]
            )
        else:
            return LegalEntityListContainer(
        )
        """

    def testLegalEntityListContainer(self):
        """Test LegalEntityListContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
