# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.immigration_case_details200_response_data_inner_process import ImmigrationCaseDetails200ResponseDataInnerProcess

class TestImmigrationCaseDetails200ResponseDataInnerProcess(unittest.TestCase):
    """ImmigrationCaseDetails200ResponseDataInnerProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImmigrationCaseDetails200ResponseDataInnerProcess:
        """Test ImmigrationCaseDetails200ResponseDataInnerProcess
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImmigrationCaseDetails200ResponseDataInnerProcess`
        """
        model = ImmigrationCaseDetails200ResponseDataInnerProcess()
        if include_optional:
            return ImmigrationCaseDetails200ResponseDataInnerProcess(
                id = '5f5b3b3b-4b3b-4b3b-4b3b-4b3b3b3b3b3b',
                name = 'Document check',
                status = 'In Review'
            )
        else:
            return ImmigrationCaseDetails200ResponseDataInnerProcess(
        )
        """

    def testImmigrationCaseDetails200ResponseDataInnerProcess(self):
        """Test ImmigrationCaseDetails200ResponseDataInnerProcess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
