# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.get_benefit_employees200_response_page import GetBenefitEmployees200ResponsePage

class TestGetBenefitEmployees200ResponsePage(unittest.TestCase):
    """GetBenefitEmployees200ResponsePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBenefitEmployees200ResponsePage:
        """Test GetBenefitEmployees200ResponsePage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBenefitEmployees200ResponsePage`
        """
        model = GetBenefitEmployees200ResponsePage()
        if include_optional:
            return GetBenefitEmployees200ResponsePage(
                offset = 0,
                total_rows = 100,
                items_per_page = 100
            )
        else:
            return GetBenefitEmployees200ResponsePage(
        )
        """

    def testGetBenefitEmployees200ResponsePage(self):
        """Test GetBenefitEmployees200ResponsePage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
