# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.created_hris_direct_employee_container_data_compensation_details import CreatedHrisDirectEmployeeContainerDataCompensationDetails

class TestCreatedHrisDirectEmployeeContainerDataCompensationDetails(unittest.TestCase):
    """CreatedHrisDirectEmployeeContainerDataCompensationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatedHrisDirectEmployeeContainerDataCompensationDetails:
        """Test CreatedHrisDirectEmployeeContainerDataCompensationDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatedHrisDirectEmployeeContainerDataCompensationDetails`
        """
        model = CreatedHrisDirectEmployeeContainerDataCompensationDetails()
        if include_optional:
            return CreatedHrisDirectEmployeeContainerDataCompensationDetails(
                currency = 'USD',
                salary = 1.337
            )
        else:
            return CreatedHrisDirectEmployeeContainerDataCompensationDetails(
                currency = 'USD',
                salary = 1.337,
        )
        """

    def testCreatedHrisDirectEmployeeContainerDataCompensationDetails(self):
        """Test CreatedHrisDirectEmployeeContainerDataCompensationDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
