# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.time_tracking_shift_meta_schema_start import TimeTrackingShiftMetaSchemaStart

class TestTimeTrackingShiftMetaSchemaStart(unittest.TestCase):
    """TimeTrackingShiftMetaSchemaStart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeTrackingShiftMetaSchemaStart:
        """Test TimeTrackingShiftMetaSchemaStart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeTrackingShiftMetaSchemaStart`
        """
        model = TimeTrackingShiftMetaSchemaStart()
        if include_optional:
            return TimeTrackingShiftMetaSchemaStart(
                var_date = '2022-05-04',
                time = '09:00',
                is_rest_day = False,
                is_public_holiday = False
            )
        else:
            return TimeTrackingShiftMetaSchemaStart(
                var_date = '2022-05-04',
                time = '09:00',
                is_rest_day = False,
                is_public_holiday = False,
        )
        """

    def testTimeTrackingShiftMetaSchemaStart(self):
        """Test TimeTrackingShiftMetaSchemaStart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
