# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.equity_tax_events201_response_data import EquityTaxEvents201ResponseData

class TestEquityTaxEvents201ResponseData(unittest.TestCase):
    """EquityTaxEvents201ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EquityTaxEvents201ResponseData:
        """Test EquityTaxEvents201ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EquityTaxEvents201ResponseData`
        """
        model = EquityTaxEvents201ResponseData()
        if include_optional:
            return EquityTaxEvents201ResponseData(
                id = 'cb50474d-2f76-42d8-a795-5277007a29d9'
            )
        else:
            return EquityTaxEvents201ResponseData(
        )
        """

    def testEquityTaxEvents201ResponseData(self):
        """Test EquityTaxEvents201ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
