# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.contract_who_reports_enum import ContractWhoReportsEnum

class TestContractWhoReportsEnum(unittest.TestCase):
    """ContractWhoReportsEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContractWhoReportsEnum(self):
        """Test ContractWhoReportsEnum"""
        # inst = ContractWhoReportsEnum()

if __name__ == '__main__':
    unittest.main()
