# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.role_to_create_container import RoleToCreateContainer

class TestRoleToCreateContainer(unittest.TestCase):
    """RoleToCreateContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoleToCreateContainer:
        """Test RoleToCreateContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoleToCreateContainer`
        """
        model = RoleToCreateContainer()
        if include_optional:
            return RoleToCreateContainer(
                data = dima_test_sdk.models.role_to_create_container_data.RoleToCreateContainer_data(
                    name = '', 
                    scope = 'ORGANIZATION', 
                    description = '', 
                    permission_sets = [
                        ''
                        ], 
                    hris_org_structure_id = '', )
            )
        else:
            return RoleToCreateContainer(
        )
        """

    def testRoleToCreateContainer(self):
        """Test RoleToCreateContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
