# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_test_sdk.models.bg_check_individual_check import BgCheckIndividualCheck

class TestBgCheckIndividualCheck(unittest.TestCase):
    """BgCheckIndividualCheck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BgCheckIndividualCheck:
        """Test BgCheckIndividualCheck
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BgCheckIndividualCheck`
        """
        model = BgCheckIndividualCheck()
        if include_optional:
            return BgCheckIndividualCheck(
                id = '331320f0-d9f5-4904-acc9-1693c93863c1',
                name = 'Softcheck',
                third_party_name = 'request_softcheck',
                is_available = True,
                price = 49,
                currency = 'USD'
            )
        else:
            return BgCheckIndividualCheck(
        )
        """

    def testBgCheckIndividualCheck(self):
        """Test BgCheckIndividualCheck"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
