from .api import *


__author__ = "Gian Glen Lopez Pintos"
__email__ = "gianlopez.cv@gmail.com"
__version__ = "0.0.1"
__license__ = "MIT"
__api__ = "https://frontend-api.pump.fun/api"


__all__ = [
    hello_world,
    health_check,
    get_latest_trades,
    get_all_trades,
    # create_trade_signature,
    # create_small_trade_signature,
    get_trade_count,
    get_trades_follows_user,
    get_trades_follows_user_count,
    # sign_create_coin_tx,
    # create_coin,
    # get_top_runners,
    get_top_runners,
    get_king_of_the_hill,
    get_currently_live,
    get_coins_for_you,
    get_featured_coins,
    get_user_created_coins,
    get_default_bookmarks,
    get_bookmarks_by_id,
    check_free_coin,
    get_latest_coins,
    get_protected_coins,
    get_personalized_coins,
    get_similar_coins,
    # create_mint,
    search_coins,
    get_coin,
    get_coins,
    # ban_coin,
    get_sol_price,
    is_admin,
    is_super_admin,
    # login,
    get_my_profile,
    is_valid_jurisdiction,
    # logout,
    check_address,
    get_moderation_logs,
    # ban_address,
    # mark_as_nsfw,
    # mark_bulk_as_nsfw,
    # mark_as_hidden,
    # mark_bulk_as_hidden,
    # ban_item,
    # ban_bulk_items,
    # ban_terms,
    get_ban_terms,
    # ban_image_terms,
    get_ban_image_terms,
    # ban_regex_patterns
    get_ban_regex_patterns,
    # add_throttle_exception,
    get_throttle_exceptions,
    # delete_ban_term,
    # delete_ban_image_term,
    # delete_ban_regex_pattern,
    # delete_throttle_exception,
    get_ban,
    get_ban_users,
    get_moderated_comments,
    get_moderated_reports,
    # mark_as_ignored,
    # delete_photo,
    get_vanity_key,
]
