# coding: utf-8

"""
    IBM Guardium Data Security Center

    IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_software.models.healthcollectorv3_mu_details_obj import Healthcollectorv3MUDetailsObj

class TestHealthcollectorv3MUDetailsObj(unittest.TestCase):
    """Healthcollectorv3MUDetailsObj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Healthcollectorv3MUDetailsObj:
        """Test Healthcollectorv3MUDetailsObj
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Healthcollectorv3MUDetailsObj`
        """
        model = Healthcollectorv3MUDetailsObj()
        if include_optional:
            return Healthcollectorv3MUDetailsObj(
                aggregation_details_list = [
                    ibm_gdsc_sdk_software.models.healthcollectorv3_aggregation_details_object.healthcollectorv3AggregationDetailsObject(
                        aggregation_action_error = '', 
                        aggregation_action_health_status = 56, 
                        aggregation_type = '', 
                        error = 56, 
                        unit = '', )
                    ],
                connectivity_details = ibm_gdsc_sdk_software.models.healthcollectorv3_general_details_object.healthcollectorv3GeneralDetailsObject(
                    err_messages = '', ),
                general_err_messages = [
                    ''
                    ],
                utilization_parameters_values = ibm_gdsc_sdk_software.models.healthcollectorv3_utilization_parameter_object.healthcollectorv3UtilizationParameterObject(
                    analyzer_queue_value = 56, 
                    detailed_err_message = '', 
                    error = 56, 
                    free_buffer_space_value = 56, 
                    logger_queue_value = 56, 
                    mysql_disk_usage_value = 56, 
                    no_of_exceptions_value = 56, 
                    no_of_flat_log_requests_value = 56, 
                    no_of_policy_violations_value = 56, 
                    no_of_requests_value = 56, 
                    no_of_restarts_value = 56, 
                    prec_mysql_memory_value = 56, 
                    sniffer_memory_value = 56, 
                    system_cpu_load_value = 56, 
                    system_var_disk_usage_value = 56, )
            )
        else:
            return Healthcollectorv3MUDetailsObj(
        )
        """

    def testHealthcollectorv3MUDetailsObj(self):
        """Test Healthcollectorv3MUDetailsObj"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
