# coding: utf-8

"""
    IBM Guardium Data Security Center

    IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_software.models.reportsv3_chart_type import Reportsv3ChartType

class TestReportsv3ChartType(unittest.TestCase):
    """Reportsv3ChartType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportsv3ChartType(self):
        """Test Reportsv3ChartType"""
        # inst = Reportsv3ChartType()

if __name__ == '__main__':
    unittest.main()
