# coding: utf-8

"""
    IBM Guardium Data Security Center

    IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_software.api.ecosystem_service_api import EcosystemServiceApi


class TestEcosystemServiceApi(unittest.TestCase):
    """EcosystemServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EcosystemServiceApi()

    def tearDown(self) -> None:
        pass

    def test_ecosystem_service_create_dataset(self) -> None:
        """Test case for ecosystem_service_create_dataset

        Summary: Create dataset Description: Save a definition in the database.
        """
        pass

    def test_ecosystem_service_data_insert(self) -> None:
        """Test case for ecosystem_service_data_insert

        Summary: Data insert Description: Process Data received from webhook API and insert.
        """
        pass

    def test_ecosystem_service_delete_datasets(self) -> None:
        """Test case for ecosystem_service_delete_datasets

        Summary: Delete datasets Description: Delete an array of datasets.
        """
        pass

    def test_ecosystem_service_get_dataset_data(self) -> None:
        """Test case for ecosystem_service_get_dataset_data

        Summary: Get dataset data Description: Return data report for a given dataset.
        """
        pass

    def test_ecosystem_service_get_dataset_detail(self) -> None:
        """Test case for ecosystem_service_get_dataset_detail

        Summary: Get dataset detail Description: Return detail on a dataset definition.
        """
        pass

    def test_ecosystem_service_get_datasets(self) -> None:
        """Test case for ecosystem_service_get_datasets

        Summary: Get datasets Description: Return dataset list that matches the specified filter.
        """
        pass

    def test_ecosystem_service_get_purgable_rows(self) -> None:
        """Test case for ecosystem_service_get_purgable_rows

        Summary: Get purgable rows Description: Check the number of rows that can be purged.
        """
        pass

    def test_ecosystem_service_purge_data(self) -> None:
        """Test case for ecosystem_service_purge_data

        Summary: Purge data Description: Purge data.
        """
        pass


if __name__ == '__main__':
    unittest.main()
