# coding: utf-8

"""
    IBM Guardium Data Security Center

    IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_software.models.qspmdatamanagerv3_app_data import Qspmdatamanagerv3AppData

class TestQspmdatamanagerv3AppData(unittest.TestCase):
    """Qspmdatamanagerv3AppData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Qspmdatamanagerv3AppData:
        """Test Qspmdatamanagerv3AppData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Qspmdatamanagerv3AppData`
        """
        model = Qspmdatamanagerv3AppData()
        if include_optional:
            return Qspmdatamanagerv3AppData(
                app_client_specific = '',
                app_end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                app_generic_id = '',
                app_name = '',
                app_owner_email = '',
                app_start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                app_uuid = '',
                app_ver = ''
            )
        else:
            return Qspmdatamanagerv3AppData(
        )
        """

    def testQspmdatamanagerv3AppData(self):
        """Test Qspmdatamanagerv3AppData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
