# coding: utf-8

"""
    IBM Guardium Data Security Center

    IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_software.api.data_movements_api import DataMovementsApi


class TestDataMovementsApi(unittest.TestCase):
    """DataMovementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataMovementsApi()

    def tearDown(self) -> None:
        pass

    def test_get_actual_flow(self) -> None:
        """Test case for get_actual_flow

        Get actual flow by providing its ID
        """
        pass

    def test_get_actual_flows_summary(self) -> None:
        """Test case for get_actual_flows_summary

        Get summary of actual flows
        """
        pass

    def test_get_potential_flow(self) -> None:
        """Test case for get_potential_flow

        Get potential flow by providing its ID
        """
        pass

    def test_get_potential_flow_path(self) -> None:
        """Test case for get_potential_flow_path

        Get potential flow path by providing its ID
        """
        pass

    def test_get_potential_flows_summary(self) -> None:
        """Test case for get_potential_flows_summary

        Get summary of potential flows according to the filter applied
        """
        pass

    def test_list_actual_flow_paths(self) -> None:
        """Test case for list_actual_flow_paths

        Get summary of actual flows according to the filter applied
        """
        pass

    def test_list_actual_flows(self) -> None:
        """Test case for list_actual_flows

        List actual flows
        """
        pass

    def test_list_potential_flows(self) -> None:
        """Test case for list_potential_flows

        List potential flows
        """
        pass

    def test_list_potential_flows_paths(self) -> None:
        """Test case for list_potential_flows_paths

        List potential flow paths
        """
        pass


if __name__ == '__main__':
    unittest.main()
