# coding: utf-8

"""
    IBM Guardium Data Security Center

    IBM Guardium Data Security Center simplifies your organization's Data Security architecture and enables access to long-term data security and compliance data. It provides security teams with risk-based views and alerts, as well as advanced analytics based on proprietary ML technology to uncover hidden threats. IBM Guardium Data Security Center gives security professionals the ability to quickly create data security and audit reports, monitor activity in on-prem and DBaaS sources, and take action from a central location.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_software.api.streams_service_api import StreamsServiceApi


class TestStreamsServiceApi(unittest.TestCase):
    """StreamsServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StreamsServiceApi()

    def tearDown(self) -> None:
        pass

    def test_streams_service_check_aws_credentials(self) -> None:
        """Test case for streams_service_check_aws_credentials

        Summary: Check AWS credentials Description: Service to verify AWS credentials.
        """
        pass

    def test_streams_service_check_azure_event_hub(self) -> None:
        """Test case for streams_service_check_azure_event_hub

        Summary: Check Azure event hub Description: Service to check Azure event hub.
        """
        pass

    def test_streams_service_check_azure_storage_string(self) -> None:
        """Test case for streams_service_check_azure_storage_string

        Summary: Check Azure storage string Description: Service to verify Azure storage connection.
        """
        pass

    def test_streams_service_get_aws_regions(self) -> None:
        """Test case for streams_service_get_aws_regions

        Summary: Get AWS regions Description: Service to get AWS regions.
        """
        pass

    def test_streams_service_list_aws_streams(self) -> None:
        """Test case for streams_service_list_aws_streams

        Summary: List AWS streams Description: Service to list AWS Kinesis streams.
        """
        pass


if __name__ == '__main__':
    unittest.main()
