from typing import List

import pandas as pd

from endpoints.model import JslModel

# blacklist = ["en.resolve.HPO", "en.explain_doc.era"]
blacklist = []


def generate_payloads(df, uploaded_models_df=None) -> List[JslModel]:
    # Optionally provide a df of uploaded models to filter out models that already uploaded
    # df = df of models to upload

    df["Relations"] = df["Relations"].replace("-", None)
    df["Entities"] = df["Entities"].replace("-", None)
    df = df.where(pd.notna(df), None)
    payloads = []
    for idx, row in df.iterrows():
        # TODO TASKS FIELD
        if not isinstance(row["Include as DB Serve Listing"], str):
            continue
        if row["Include as DB Serve Listing"].lower() != "yes":
            continue

        if not isinstance(row["nlu_ref"], str):
            print("missing nlu ref for ", row["Pipeline Name"])
            continue

        nlu_ref = row["nlu_ref"].strip().replace("\n", " ")
        if nlu_ref in blacklist:
            continue
        if (
            uploaded_models_df is not None
            # TODO USE TITLE/ID
            and row["Pipeline Name"] in uploaded_models_df["Title"].values
        ):
            # this model is already uploaded, skip
            continue

        payload = {
            # "price_group": row["Price Group"],
            # "listing_group": row["Listing Group"],
            "domain": row["Domain"],
            "group": row["Group"],
            "subdomain": row["Subdomain"],
            "language": row["Language"],
            "pipe_name": row["Pipeline Name"],  # use this as listing name!
            "short_description": row["Short Description"],
            "long_description": row["Long Description"],
            "entities": row["Entities"],
            "relations": row["Relations"],
            "nlp_ref": row[
                "Pipeline/Models"
            ],  # aka model name nlp ref, #TODO WAS MODEL
            "demo": row["Demo"],
            "model_hub_url": row["Models Hub URL"],
            "nlu_ref": nlu_ref,
            "tasks": row["Tasks"],
            "id": str(int(row["id"])),
            "example_text": row["Example Text"],
            "dropdown_id": str(int(row["id"])) + ". " + row["Pipeline Name"],
            "file_url": None,  # TODO handel propelry
            "is_ocr_model": False,
        }

        payload["long_description"] = payload["long_description"].replace(
            "Key Features:", "**Key Features:**"
        )

        payload[
            "long_description"
        ] = f"""**{payload['pipe_name']}:** 
 
 {payload["long_description"]}"""

        if not payload["nlu_ref"] or not payload["long_description"]:
            print(f"no nlu ref for {payload['model']}")
            continue

        # Suffix for Docs
        base_suffix = f"""\n\n**Additional Model Information**\n"""
        doc_suffix = f"""\n\n**Additional Model Information**\n"""

        if payload["demo"]:
            doc_suffix = (
                doc_suffix + f"""- [Industry Use-Case Demo]({payload['demo']})\n"""
            )
        if payload["model_hub_url"]:
            doc_suffix = (
                doc_suffix
                + f"""- [Full model info on John Snow Labs Models Hub]({payload['model_hub_url']})\n"""
            )

        if payload["domain"]:
            doc_suffix = doc_suffix + f"""- **Domain:** {payload['domain']}\n"""

        if payload["subdomain"]:
            doc_suffix = doc_suffix + f"""- **Subdomain:** {payload['subdomain']}\n"""

        if payload["entities"]:
            doc_suffix = (
                doc_suffix + f"""- **Predictable entities:** {payload['entities']}\n"""
            )
        if payload["relations"]:
            doc_suffix = (
                doc_suffix
                + f"""- **Predictable Relationships between entities:** {payload['relations']}\n"""
            )
        doc_suffix = (
            doc_suffix + f"""- **Deployment Identifier:** {payload["dropdown_id"]}\n"""
        )
        if doc_suffix != base_suffix:
            # only add suffix if there is something to add
            payload[
                "long_description"
            ] = f"""{payload["long_description"]}
            
{doc_suffix}"""
        instruction_suffix = f"""**How to run this model:**
1. Acquire a John Snow Labs Pay As You Go (PAYG) license from [John Snow Labs](https://my.johnsnowlabs.com/).
2. Import this listing.
3. Use the attached notebook to deploy the model with **{payload["dropdown_id"].rstrip(" ")}** as the model parameter. **Do Not use the Deploy button on this page, it does not work yet**.   

This model comes with optimized CPU and GPU builds. You can select which one to deploy via the notebook. 

**How to obtain a PAYG license:**
1. Access [my.JohnSnowLabs.com](https://my.johnsnowlabs.com) and log in to your account. If you don't have an account, create one.
2. Go to the Get License page.
3. Switch to the PAYG Subscription tab and provide your credit card details.
4. Carefully review the End User License Agreement and the Terms and Conditions documents. If you agree, click on the Create Subscription button.
5. Once the process is complete, you will find your PAY-As-You-GO license listed on the My Subscriptions page.
6. Visit the My Subscriptions page and copy the PAYG license key by clicking on the copy icon in the License Key column.
7. Go to your Databricks notebook and paste your JSL-license into the JSL-License field in the top of the notebook. You are now ready to go!
        """
        payload[
            "long_description"
        ] = f"""{payload["long_description"]} 

{instruction_suffix}"""

        payloads.append(payload)

    return [JslModel(**p) for p in payloads]
    # return payloads
    # return [JslModel(**p for p in payloads)]


models_uploaded = {
    "index": {
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 7,
        7: 9,
        8: 10,
        9: 12,
        10: 13,
        11: 14,
        12: 15,
        13: 18,
        14: 20,
        15: 21,
        16: 22,
        17: 23,
        18: 24,
        19: 26,
        20: 27,
        21: 29,
        22: 30,
        23: 31,
        24: 32,
        25: 34,
        26: 35,
        27: 36,
        28: 37,
        29: 38,
        30: 39,
        31: 40,
        32: 41,
        33: 42,
        34: 43,
        35: 44,
        36: 46,
        37: 47,
        38: 48,
        39: 49,
        40: 50,
        41: 51,
        42: 52,
        43: 53,
        44: 54,
        45: 55,
        46: 56,
        47: 57,
        48: 58,
        49: 60,
        50: 62,
        51: 64,
        52: 66,
        53: 69,
        54: 70,
        55: 71,
        56: 72,
        57: 74,
        58: 79,
    },
    "NluRef": {
        0: "en.map_entity.umls_disease_syndrome_resolver",
        1: "en.classify.bert_sequence.vop_hcp_consult.pipeline",
        2: "en.resolve.cpt.augmented",
        3: "en.resolve.loinc.augmented",
        4: "en.summarize.clinical_guidelines_large.pipeline",
        5: "en.icd10cm_resolver.pipeline",
        6: "en.map_entity.umls_clinical_findings_resolver",
        7: "en.med_ner.nihss_pipeline",
        8: "en.resolve.icd9.pipeline",
        9: "en.map_entity.rxnorm_resolver.pipe",
        10: "en.resolve.HPO",
        11: "en.classify.bert_sequence.vop_drug_side_effect.pipeline",
        12: "en.map_entity.umls_drug_resolver",
        13: "en.summarize.clinical_laymen_onnx.pipeline",
        14: "en.explain_doc.clinical_radiology.pipeline",
        15: "en.med_ner.pathogen.pipeline",
        16: "en.med_ner.vop_langtest",
        17: "en.resolve.icdo_augmented",
        18: "pt.deid.clinical",
        19: "ro.deid.clinical",
        20: "en.med_ner.sdoh_langtest.pipeline",
        21: "fr.deid_obfuscated",
        22: "en.summarize.clinical_questions.pipeline",
        23: "es.deid.clinical",
        24: "it.deid.clinical",
        25: "ar.deid.clinical",
        26: "en.de_identify.clinical_pipeline",
        27: "de.deid.clinical",
        28: "en.resolve.snomed.findings",
        29: "en.ner.oncology.pipeline",
        30: "pt.deid.clinical",
        31: "en.summarize.clinical_jsl_augmented.pipeline",
        32: "en.map_entity.umls_drug_resolver",
        33: "en.map_entity.icd10cm_to_snomed.pipe",
        34: "ro.deid.clinical",
        35: "en.map_entity.snomed_to_icd10cm.pipe",
        36: "fr.deid_obfuscated",
        37: "es.deid.clinical",
        38: "ar.deid.clinical",
        39: "de.deid.clinical",
        40: "it.deid.clinical",
        41: "en.explain_doc.era",
        42: "en.de_identify.clinical_pipeline",
        43: "en.summarize.biomedical_pubmed.pipeline",
        44: "en.map_entity.snomed_to_icdo",
        45: "en.explain_doc.clinical_ade",
        46: "en.med_ner.risk_factors.pipeline",
        47: "en.map_entity.rxnorm_to_ndc.pipe",
        48: "en.summarize.radiology.pipeline",
        49: "en.med_ner.anatom.pipeline",
        50: "en.icd10cm.umls.mapping",
        51: "en.med_ner.living_species.pipeline",
        52: "en.icd10_icd9.mapping",
        53: "en.rxnorm.umls.mapping",
        54: "en.med_ner.bionlp.pipeline",
        55: "en.snomed.umls.mapping",
        56: "en.rxnorm.mes.mapping",
        57: "en.mesh.umls.mapping",
        58: "en.resolve.medication",
    },
    "Title": {
        0: "Extract Disease and Syndrom entities and their UMLS Codes",
        1: "Detect Healthcare Professional Consult documents",
        2: "Extract procedures and measurements and their corresponding CPT codes",
        3: "Extract Laboratory Observations and the corresponding LOINC codes",
        4: "Guideline Summarizer for Asthma & Breast Cancer",
        5: "Extract Clinical Findings and the corresponding ICD10CM codes",
        6: "Extract Clinical Findings and their UMLS Codes",
        7: "Extract neurologic deficits related to Stroke Scale (NIHSS)",
        8: "Extract Clinical Findings and the corresponding ICD 9 codes",
        9: "Extract Drugs and the correspondingt RXNORM codes",
        10: "Extract phenotypic abnormalities and the coresponding HPO codes ",
        11: "Detect Drug Side Effect Narratives",
        12: "Extract  Drugs and Substances and their UMLS Codes",
        13: "Summarize Clinical Notes in Laymen Terms ",
        14: "Extract findings in radiology reports",
        15: "Detect Pathogen, Medical Condition and Medicine",
        16: "Extract patient information from patient narratives",
        17: "Resolve Oncology terminology with ICD-O Taxonomy",
        18: "Clinical De-identification for Portuguese (Obfuscate)",
        19: "Clinical De-identification for Romanian (Obfuscate)",
        20: "Extract Social Determinants of Health",
        21: "Clinical De-identification for French (Obfuscate)",
        22: "Summarize Clinical Question Notes",
        23: "Clinical De-identification for Spanish (Obfuscate)",
        24: "Clinical De-identification for Italian (Obfuscate)",
        25: "Clinical De-identification for Arabic (Obfuscate)",
        26: "Clinical De-identification (Obfuscate)",
        27: "Clinical De-identification for German (Obfuscate)",
        28: "SNOMED Clinical Health Information Coder",
        29: "Extract oncological entities and relations",
        30: "Clinical De-identification for Portuguese (Mask)",
        31: "Clinical Text Summarization",
        32: "Extract Drugs and their UMLS Codes",
        33: "ICD-10-CM to SNOMED Code Mapper",
        34: "Clinical De-identification for Romanian (Mask)",
        35: "SNOMED to ICD-10-CM Code Mapper",
        36: "Clinical De-identification for French (Mask)",
        37: "Clinical De-identification for Spanish (Mask)",
        38: "Clinical De-identification for Arabic (Mask)",
        39: "Clinical De-identification for German (Mask)",
        40: "Clinical De-identification forItalian (Mask)",
        41: "Extract clinical events and find temporal relations (ERA)",
        42: "Clinical De-identification (Mask)",
        43: "Summarize PubMed Research",
        44: "SNOMED Codes to ICDO Codes Mapper",
        45: "Extract Adverse Drug Events (ADE)",
        46: "Extract clinical risk factors",
        47: "RxNorm to NDC Code Converter",
        48: "Summarize Radiology Reports",
        49: "Extract Anatomical Structures",
        50: " ICD-10-CM to UMLS Code Mapper",
        51: "Extract Living Species",
        52: "ICD-10 to ICD-9 Code Converter",
        53: "RxNorm to UMLS Code Mapper",
        54: "Detect Cancer Genetics",
        55: "SNOMED to UMLS Code Mapper",
        56: "RxNorm to MeSH Code Mapper",
        57: "MeSH to UMLS Code Mapper",
        58: "Medication Coder",
    },
    "ReleaseID": {
        0: "0.9",
        1: "0.9",
        2: "0.9",
        3: "0.9",
        4: "0.9",
        5: "0.9",
        6: "0.9",
        7: "0.9",
        8: "0.9",
        9: "0.9",
        10: "0.9",
        11: "0.9",
        12: "0.9",
        13: "0.9",
        14: "0.9",
        15: "0.9",
        16: "0.9",
        17: "0.9",
        18: "0.9",
        19: "0.9",
        20: "0.9",
        21: "0.9",
        22: "0.9",
        23: "0.9",
        24: "0.9",
        25: "0.9",
        26: "0.9",
        27: "0.9",
        28: "0.9",
        29: "0.9",
        30: "0.9",
        31: "0.9",
        32: "0.9",
        33: "0.9",
        34: "0.9",
        35: "0.9",
        36: "0.9",
        37: "0.9",
        38: "0.9",
        39: "0.9",
        40: "0.9",
        41: "0.9",
        42: "0.9",
        43: "0.9",
        44: "0.9",
        45: "0.9",
        46: "0.9",
        47: "0.9",
        48: "0.9",
        49: "0.9",
        50: "0.9",
        51: "0.9",
        52: "0.9",
        53: "0.9",
        54: "0.9",
        55: "0.9",
        56: "0.9",
        57: "0.9",
        58: "0.9",
    },
    "BaseModelPath": {
        0: "john_snow_labs_extract_disease_and_syndrom_entities_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_disease_syndrome_resolver",
        1: "john_snow_labs_detect_healthcare_professional_consult_documents.johnsnowlabs_folder.en_classify_bert_sequence_vop_hcp_consult_pipeline",
        2: "john_snow_labs_extract_procedures_and_measurements_and_their_corresponding_cpt_codes.johnsnowlabs_folder.en_resolve_cpt_augmented",
        3: "john_snow_labs_extract_laboratory_observations_and_the_corresponding_loinc_codes.johnsnowlabs_folder.en_resolve_loinc_augmented",
        4: "john_snow_labs_guideline_summarizer_for_asthma___breast_cancer.johnsnowlabs_folder.en_summarize_clinical_guidelines_large_pipeline",
        5: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd10cm_codes.johnsnowlabs_folder.en_icd10cm_resolver_pipeline",
        6: "john_snow_labs_extract_clinical_findings_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_clinical_findings_resolver",
        7: "john_snow_labs_extract_neurologic_deficits_related_to_stroke_scale_nihss.johnsnowlabs_folder.en_med_ner_nihss_pipeline",
        8: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd_9_codes.johnsnowlabs_folder.en_resolve_icd9_pipeline",
        9: "john_snow_labs_extract_drugs_and_the_correspondingt_rxnorm_codes.johnsnowlabs_folder.en_map_entity_rxnorm_resolver_pipe",
        10: "john_snow_labs_extract_phenotypic_abnormalities_and_the_coresponding_hpo_codes_.johnsnowlabs_folder.en_resolve_HPO",
        11: "john_snow_labs_detect_drug_side_effect_narratives.johnsnowlabs_folder.en_classify_bert_sequence_vop_drug_side_effect_pipeline",
        12: "john_snow_labs_extract__drugs_and_substances_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_drug_resolver",
        13: "john_snow_labs_summarize_clinical_notes_in_laymen_terms_.johnsnowlabs_folder.en_summarize_clinical_laymen_onnx_pipeline",
        14: "john_snow_labs_extract_findings_in_radiology_reports.johnsnowlabs_folder.en_explain_doc_clinical_radiology_pipeline",
        15: "john_snow_labs_detect_pathogen,_medical_condition_and_medicine.johnsnowlabs_folder.en_med_ner_pathogen_pipeline",
        16: "john_snow_labs_extract_patient_information_from_patient_narratives.johnsnowlabs_folder.en_med_ner_vop_langtest",
        17: "john_snow_labs_resolve_oncology_terminology_with_icd_o_taxonomy.johnsnowlabs_folder.en_resolve_icdo_augmented",
        18: "john_snow_labs_clinical_de_identification_for_portuguese_obfuscate.johnsnowlabs_folder.pt_deid_clinical",
        19: "john_snow_labs_clinical_de_identification_for_romanian_obfuscate.johnsnowlabs_folder.ro_deid_clinical",
        20: "john_snow_labs_extract_social_determinants_of_health.johnsnowlabs_folder.en_med_ner_sdoh_langtest_pipeline",
        21: "john_snow_labs_clinical_de_identification_for_french_obfuscate.johnsnowlabs_folder.fr_deid_obfuscated",
        22: "john_snow_labs_summarize_clinical_question_notes.johnsnowlabs_folder.en_summarize_clinical_questions_pipeline",
        23: "john_snow_labs_clinical_de_identification_for_spanish_obfuscate.johnsnowlabs_folder.es_deid_clinical",
        24: "john_snow_labs_clinical_de_identification_for_italian_obfuscate.johnsnowlabs_folder.it_deid_clinical",
        25: "john_snow_labs_clinical_de_identification_for_arabic_obfuscate.johnsnowlabs_folder.ar_deid_clinical",
        26: "john_snow_labs_clinical_de_identification_obfuscate.johnsnowlabs_folder.en_de_identify_clinical_pipeline",
        27: "john_snow_labs_clinical_de_identification_for_german_obfuscate.johnsnowlabs_folder.de_deid_clinical",
        28: "john_snow_labs_snomed_clinical_health_information_coder.johnsnowlabs_folder.en_resolve_snomed_findings",
        29: "john_snow_labs_extract_oncological_entities_and_relations.johnsnowlabs_folder.en_ner_oncology_pipeline",
        30: "john_snow_labs_clinical_de_identification_for_portuguese_mask.johnsnowlabs_folder.pt_deid_clinical",
        31: "john_snow_labs_clinical_text_summarization.johnsnowlabs_folder.en_summarize_clinical_jsl_augmented_pipeline",
        32: "john_snow_labs_extract_drugs_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_drug_resolver",
        33: "john_snow_labs_icd_10_cm_to_snomed_code_mapper.johnsnowlabs_folder.en_map_entity_icd10cm_to_snomed_pipe",
        34: "john_snow_labs_clinical_de_identification_for_romanian_mask.johnsnowlabs_folder.ro_deid_clinical",
        35: "john_snow_labs_snomed_to_icd_10_cm_code_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icd10cm_pipe",
        36: "john_snow_labs_clinical_de_identification_for_french_mask.johnsnowlabs_folder.fr_deid_obfuscated",
        37: "john_snow_labs_clinical_de_identification_for_spanish_mask.johnsnowlabs_folder.es_deid_clinical",
        38: "john_snow_labs_clinical_de_identification_for_arabic_mask.johnsnowlabs_folder.ar_deid_clinical",
        39: "john_snow_labs_clinical_de_identification_for_german_mask.johnsnowlabs_folder.de_deid_clinical",
        40: "john_snow_labs_clinical_de_identification_foritalian_mask.johnsnowlabs_folder.it_deid_clinical",
        41: "john_snow_labs_extract_clinical_events_and_find_temporal_relations_era.johnsnowlabs_folder.en_explain_doc_era",
        42: "john_snow_labs_clinical_de_identification_mask.johnsnowlabs_folder.en_de_identify_clinical_pipeline",
        43: "john_snow_labs_summarize_pubmed_research.johnsnowlabs_folder.en_summarize_biomedical_pubmed_pipeline",
        44: "john_snow_labs_snomed_codes_to_icdo_codes_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icdo",
        45: "john_snow_labs_extract_adverse_drug_events_ade.johnsnowlabs_folder.en_explain_doc_clinical_ade",
        46: "john_snow_labs_extract_clinical_risk_factors.johnsnowlabs_folder.en_med_ner_risk_factors_pipeline",
        47: "john_snow_labs_rxnorm_to_ndc_code_converter.johnsnowlabs_folder.en_map_entity_rxnorm_to_ndc_pipe",
        48: "john_snow_labs_summarize_radiology_reports.johnsnowlabs_folder.en_summarize_radiology_pipeline",
        49: "john_snow_labs_extract_anatomical_structures.johnsnowlabs_folder.en_med_ner_anatom_pipeline",
        50: "john_snow_labs__icd_10_cm_to_umls_code_mapper.johnsnowlabs_folder.en_icd10cm_umls_mapping",
        51: "john_snow_labs_extract_living_species.johnsnowlabs_folder.en_med_ner_living_species_pipeline",
        52: "john_snow_labs_icd_10_to_icd_9_code_converter.johnsnowlabs_folder.en_icd10_icd9_mapping",
        53: "john_snow_labs_rxnorm_to_umls_code_mapper.johnsnowlabs_folder.en_rxnorm_umls_mapping",
        54: "john_snow_labs_detect_cancer_genetics.johnsnowlabs_folder.en_med_ner_bionlp_pipeline",
        55: "john_snow_labs_snomed_to_umls_code_mapper.johnsnowlabs_folder.en_snomed_umls_mapping",
        56: "john_snow_labs_rxnorm_to_mesh_code_mapper.johnsnowlabs_folder.en_rxnorm_mes_mapping",
        57: "john_snow_labs_mesh_to_umls_code_mapper.johnsnowlabs_folder.en_mesh_umls_mapping",
        58: "john_snow_labs_medication_coder.johnsnowlabs_folder.en_resolve_medication",
    },
    "CpuModelPath": {
        0: "john_snow_labs_extract_disease_and_syndrom_entities_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_disease_syndrome_resolver_cpu",
        1: "john_snow_labs_detect_healthcare_professional_consult_documents.johnsnowlabs_folder.en_classify_bert_sequence_vop_hcp_consult_pipeline_cpu",
        2: "john_snow_labs_extract_procedures_and_measurements_and_their_corresponding_cpt_codes.johnsnowlabs_folder.en_resolve_cpt_augmented_cpu",
        3: "john_snow_labs_extract_laboratory_observations_and_the_corresponding_loinc_codes.johnsnowlabs_folder.en_resolve_loinc_augmented_cpu",
        4: "john_snow_labs_guideline_summarizer_for_asthma___breast_cancer.johnsnowlabs_folder.en_summarize_clinical_guidelines_large_pipeline_cpu",
        5: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd10cm_codes.johnsnowlabs_folder.en_icd10cm_resolver_pipeline_cpu",
        6: "john_snow_labs_extract_clinical_findings_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_clinical_findings_resolver_cpu",
        7: "john_snow_labs_extract_neurologic_deficits_related_to_stroke_scale_nihss.johnsnowlabs_folder.en_med_ner_nihss_pipeline_cpu",
        8: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd_9_codes.johnsnowlabs_folder.en_resolve_icd9_pipeline_cpu",
        9: "john_snow_labs_extract_drugs_and_the_correspondingt_rxnorm_codes.johnsnowlabs_folder.en_map_entity_rxnorm_resolver_pipe_cpu",
        10: "john_snow_labs_extract_phenotypic_abnormalities_and_the_coresponding_hpo_codes_.johnsnowlabs_folder.en_resolve_HPO_cpu",
        11: "john_snow_labs_detect_drug_side_effect_narratives.johnsnowlabs_folder.en_classify_bert_sequence_vop_drug_side_effect_pipeline_cpu",
        12: "john_snow_labs_extract__drugs_and_substances_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_drug_resolver_cpu",
        13: "john_snow_labs_summarize_clinical_notes_in_laymen_terms_.johnsnowlabs_folder.en_summarize_clinical_laymen_onnx_pipeline_cpu",
        14: "john_snow_labs_extract_findings_in_radiology_reports.johnsnowlabs_folder.en_explain_doc_clinical_radiology_pipeline_cpu",
        15: "john_snow_labs_detect_pathogen,_medical_condition_and_medicine.johnsnowlabs_folder.en_med_ner_pathogen_pipeline_cpu",
        16: "john_snow_labs_extract_patient_information_from_patient_narratives.johnsnowlabs_folder.en_med_ner_vop_langtest_cpu",
        17: "john_snow_labs_resolve_oncology_terminology_with_icd_o_taxonomy.johnsnowlabs_folder.en_resolve_icdo_augmented_cpu",
        18: "john_snow_labs_clinical_de_identification_for_portuguese_obfuscate.johnsnowlabs_folder.pt_deid_clinical_cpu",
        19: "john_snow_labs_clinical_de_identification_for_romanian_obfuscate.johnsnowlabs_folder.ro_deid_clinical_cpu",
        20: "john_snow_labs_extract_social_determinants_of_health.johnsnowlabs_folder.en_med_ner_sdoh_langtest_pipeline_cpu",
        21: "john_snow_labs_clinical_de_identification_for_french_obfuscate.johnsnowlabs_folder.fr_deid_obfuscated_cpu",
        22: "john_snow_labs_summarize_clinical_question_notes.johnsnowlabs_folder.en_summarize_clinical_questions_pipeline_cpu",
        23: "john_snow_labs_clinical_de_identification_for_spanish_obfuscate.johnsnowlabs_folder.es_deid_clinical_cpu",
        24: "john_snow_labs_clinical_de_identification_for_italian_obfuscate.johnsnowlabs_folder.it_deid_clinical_cpu",
        25: "john_snow_labs_clinical_de_identification_for_arabic_obfuscate.johnsnowlabs_folder.ar_deid_clinical_cpu",
        26: "john_snow_labs_clinical_de_identification_obfuscate.johnsnowlabs_folder.en_de_identify_clinical_pipeline_cpu",
        27: "john_snow_labs_clinical_de_identification_for_german_obfuscate.johnsnowlabs_folder.de_deid_clinical_cpu",
        28: "john_snow_labs_snomed_clinical_health_information_coder.johnsnowlabs_folder.en_resolve_snomed_findings_cpu",
        29: "john_snow_labs_extract_oncological_entities_and_relations.johnsnowlabs_folder.en_ner_oncology_pipeline_cpu",
        30: "john_snow_labs_clinical_de_identification_for_portuguese_mask.johnsnowlabs_folder.pt_deid_clinical_cpu",
        31: "john_snow_labs_clinical_text_summarization.johnsnowlabs_folder.en_summarize_clinical_jsl_augmented_pipeline_cpu",
        32: "john_snow_labs_extract_drugs_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_drug_resolver_cpu",
        33: "john_snow_labs_icd_10_cm_to_snomed_code_mapper.johnsnowlabs_folder.en_map_entity_icd10cm_to_snomed_pipe_cpu",
        34: "john_snow_labs_clinical_de_identification_for_romanian_mask.johnsnowlabs_folder.ro_deid_clinical_cpu",
        35: "john_snow_labs_snomed_to_icd_10_cm_code_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icd10cm_pipe_cpu",
        36: "john_snow_labs_clinical_de_identification_for_french_mask.johnsnowlabs_folder.fr_deid_obfuscated_cpu",
        37: "john_snow_labs_clinical_de_identification_for_spanish_mask.johnsnowlabs_folder.es_deid_clinical_cpu",
        38: "john_snow_labs_clinical_de_identification_for_arabic_mask.johnsnowlabs_folder.ar_deid_clinical_cpu",
        39: "john_snow_labs_clinical_de_identification_for_german_mask.johnsnowlabs_folder.de_deid_clinical_cpu",
        40: "john_snow_labs_clinical_de_identification_foritalian_mask.johnsnowlabs_folder.it_deid_clinical_cpu",
        41: "john_snow_labs_extract_clinical_events_and_find_temporal_relations_era.johnsnowlabs_folder.en_explain_doc_era_cpu",
        42: "john_snow_labs_clinical_de_identification_mask.johnsnowlabs_folder.en_de_identify_clinical_pipeline_cpu",
        43: "john_snow_labs_summarize_pubmed_research.johnsnowlabs_folder.en_summarize_biomedical_pubmed_pipeline_cpu",
        44: "john_snow_labs_snomed_codes_to_icdo_codes_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icdo_cpu",
        45: "john_snow_labs_extract_adverse_drug_events_ade.johnsnowlabs_folder.en_explain_doc_clinical_ade_cpu",
        46: "john_snow_labs_extract_clinical_risk_factors.johnsnowlabs_folder.en_med_ner_risk_factors_pipeline_cpu",
        47: "john_snow_labs_rxnorm_to_ndc_code_converter.johnsnowlabs_folder.en_map_entity_rxnorm_to_ndc_pipe_cpu",
        48: "john_snow_labs_summarize_radiology_reports.johnsnowlabs_folder.en_summarize_radiology_pipeline_cpu",
        49: "john_snow_labs_extract_anatomical_structures.johnsnowlabs_folder.en_med_ner_anatom_pipeline_cpu",
        50: "john_snow_labs__icd_10_cm_to_umls_code_mapper.johnsnowlabs_folder.en_icd10cm_umls_mapping_cpu",
        51: "john_snow_labs_extract_living_species.johnsnowlabs_folder.en_med_ner_living_species_pipeline_cpu",
        52: "john_snow_labs_icd_10_to_icd_9_code_converter.johnsnowlabs_folder.en_icd10_icd9_mapping_cpu",
        53: "john_snow_labs_rxnorm_to_umls_code_mapper.johnsnowlabs_folder.en_rxnorm_umls_mapping_cpu",
        54: "john_snow_labs_detect_cancer_genetics.johnsnowlabs_folder.en_med_ner_bionlp_pipeline_cpu",
        55: "john_snow_labs_snomed_to_umls_code_mapper.johnsnowlabs_folder.en_snomed_umls_mapping_cpu",
        56: "john_snow_labs_rxnorm_to_mesh_code_mapper.johnsnowlabs_folder.en_rxnorm_mes_mapping_cpu",
        57: "john_snow_labs_mesh_to_umls_code_mapper.johnsnowlabs_folder.en_mesh_umls_mapping_cpu",
        58: "john_snow_labs_medication_coder.johnsnowlabs_folder.en_resolve_medication_cpu",
    },
    "GpuModelPath": {
        0: "john_snow_labs_extract_disease_and_syndrom_entities_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_disease_syndrome_resolver_gpu",
        1: "john_snow_labs_detect_healthcare_professional_consult_documents.johnsnowlabs_folder.en_classify_bert_sequence_vop_hcp_consult_pipeline_gpu",
        2: "john_snow_labs_extract_procedures_and_measurements_and_their_corresponding_cpt_codes.johnsnowlabs_folder.en_resolve_cpt_augmented_gpu",
        3: "john_snow_labs_extract_laboratory_observations_and_the_corresponding_loinc_codes.johnsnowlabs_folder.en_resolve_loinc_augmented_gpu",
        4: "john_snow_labs_guideline_summarizer_for_asthma___breast_cancer.johnsnowlabs_folder.en_summarize_clinical_guidelines_large_pipeline_gpu",
        5: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd10cm_codes.johnsnowlabs_folder.en_icd10cm_resolver_pipeline_gpu",
        6: "john_snow_labs_extract_clinical_findings_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_clinical_findings_resolver_gpu",
        7: "john_snow_labs_extract_neurologic_deficits_related_to_stroke_scale_nihss.johnsnowlabs_folder.en_med_ner_nihss_pipeline_gpu",
        8: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd_9_codes.johnsnowlabs_folder.en_resolve_icd9_pipeline_gpu",
        9: "john_snow_labs_extract_drugs_and_the_correspondingt_rxnorm_codes.johnsnowlabs_folder.en_map_entity_rxnorm_resolver_pipe_gpu",
        10: "john_snow_labs_extract_phenotypic_abnormalities_and_the_coresponding_hpo_codes_.johnsnowlabs_folder.en_resolve_HPO_gpu",
        11: "john_snow_labs_detect_drug_side_effect_narratives.johnsnowlabs_folder.en_classify_bert_sequence_vop_drug_side_effect_pipeline_gpu",
        12: "john_snow_labs_extract__drugs_and_substances_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_drug_resolver_gpu",
        13: "john_snow_labs_summarize_clinical_notes_in_laymen_terms_.johnsnowlabs_folder.en_summarize_clinical_laymen_onnx_pipeline_gpu",
        14: "john_snow_labs_extract_findings_in_radiology_reports.johnsnowlabs_folder.en_explain_doc_clinical_radiology_pipeline_gpu",
        15: "john_snow_labs_detect_pathogen,_medical_condition_and_medicine.johnsnowlabs_folder.en_med_ner_pathogen_pipeline_gpu",
        16: "john_snow_labs_extract_patient_information_from_patient_narratives.johnsnowlabs_folder.en_med_ner_vop_langtest_gpu",
        17: "john_snow_labs_resolve_oncology_terminology_with_icd_o_taxonomy.johnsnowlabs_folder.en_resolve_icdo_augmented_gpu",
        18: "john_snow_labs_clinical_de_identification_for_portuguese_obfuscate.johnsnowlabs_folder.pt_deid_clinical_gpu",
        19: "john_snow_labs_clinical_de_identification_for_romanian_obfuscate.johnsnowlabs_folder.ro_deid_clinical_gpu",
        20: "john_snow_labs_extract_social_determinants_of_health.johnsnowlabs_folder.en_med_ner_sdoh_langtest_pipeline_gpu",
        21: "john_snow_labs_clinical_de_identification_for_french_obfuscate.johnsnowlabs_folder.fr_deid_obfuscated_gpu",
        22: "john_snow_labs_summarize_clinical_question_notes.johnsnowlabs_folder.en_summarize_clinical_questions_pipeline_gpu",
        23: "john_snow_labs_clinical_de_identification_for_spanish_obfuscate.johnsnowlabs_folder.es_deid_clinical_gpu",
        24: "john_snow_labs_clinical_de_identification_for_italian_obfuscate.johnsnowlabs_folder.it_deid_clinical_gpu",
        25: "john_snow_labs_clinical_de_identification_for_arabic_obfuscate.johnsnowlabs_folder.ar_deid_clinical_gpu",
        26: "john_snow_labs_clinical_de_identification_obfuscate.johnsnowlabs_folder.en_de_identify_clinical_pipeline_gpu",
        27: "john_snow_labs_clinical_de_identification_for_german_obfuscate.johnsnowlabs_folder.de_deid_clinical_gpu",
        28: "john_snow_labs_snomed_clinical_health_information_coder.johnsnowlabs_folder.en_resolve_snomed_findings_gpu",
        29: "john_snow_labs_extract_oncological_entities_and_relations.johnsnowlabs_folder.en_ner_oncology_pipeline_gpu",
        30: "john_snow_labs_clinical_de_identification_for_portuguese_mask.johnsnowlabs_folder.pt_deid_clinical_gpu",
        31: "john_snow_labs_clinical_text_summarization.johnsnowlabs_folder.en_summarize_clinical_jsl_augmented_pipeline_gpu",
        32: "john_snow_labs_extract_drugs_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_drug_resolver_gpu",
        33: "john_snow_labs_icd_10_cm_to_snomed_code_mapper.johnsnowlabs_folder.en_map_entity_icd10cm_to_snomed_pipe_gpu",
        34: "john_snow_labs_clinical_de_identification_for_romanian_mask.johnsnowlabs_folder.ro_deid_clinical_gpu",
        35: "john_snow_labs_snomed_to_icd_10_cm_code_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icd10cm_pipe_gpu",
        36: "john_snow_labs_clinical_de_identification_for_french_mask.johnsnowlabs_folder.fr_deid_obfuscated_gpu",
        37: "john_snow_labs_clinical_de_identification_for_spanish_mask.johnsnowlabs_folder.es_deid_clinical_gpu",
        38: "john_snow_labs_clinical_de_identification_for_arabic_mask.johnsnowlabs_folder.ar_deid_clinical_gpu",
        39: "john_snow_labs_clinical_de_identification_for_german_mask.johnsnowlabs_folder.de_deid_clinical_gpu",
        40: "john_snow_labs_clinical_de_identification_foritalian_mask.johnsnowlabs_folder.it_deid_clinical_gpu",
        41: "john_snow_labs_extract_clinical_events_and_find_temporal_relations_era.johnsnowlabs_folder.en_explain_doc_era_gpu",
        42: "john_snow_labs_clinical_de_identification_mask.johnsnowlabs_folder.en_de_identify_clinical_pipeline_gpu",
        43: "john_snow_labs_summarize_pubmed_research.johnsnowlabs_folder.en_summarize_biomedical_pubmed_pipeline_gpu",
        44: "john_snow_labs_snomed_codes_to_icdo_codes_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icdo_gpu",
        45: "john_snow_labs_extract_adverse_drug_events_ade.johnsnowlabs_folder.en_explain_doc_clinical_ade_gpu",
        46: "john_snow_labs_extract_clinical_risk_factors.johnsnowlabs_folder.en_med_ner_risk_factors_pipeline_gpu",
        47: "john_snow_labs_rxnorm_to_ndc_code_converter.johnsnowlabs_folder.en_map_entity_rxnorm_to_ndc_pipe_gpu",
        48: "john_snow_labs_summarize_radiology_reports.johnsnowlabs_folder.en_summarize_radiology_pipeline_gpu",
        49: "john_snow_labs_extract_anatomical_structures.johnsnowlabs_folder.en_med_ner_anatom_pipeline_gpu",
        50: "john_snow_labs__icd_10_cm_to_umls_code_mapper.johnsnowlabs_folder.en_icd10cm_umls_mapping_gpu",
        51: "john_snow_labs_extract_living_species.johnsnowlabs_folder.en_med_ner_living_species_pipeline_gpu",
        52: "john_snow_labs_icd_10_to_icd_9_code_converter.johnsnowlabs_folder.en_icd10_icd9_mapping_gpu",
        53: "john_snow_labs_rxnorm_to_umls_code_mapper.johnsnowlabs_folder.en_rxnorm_umls_mapping_gpu",
        54: "john_snow_labs_detect_cancer_genetics.johnsnowlabs_folder.en_med_ner_bionlp_pipeline_gpu",
        55: "john_snow_labs_snomed_to_umls_code_mapper.johnsnowlabs_folder.en_snomed_umls_mapping_gpu",
        56: "john_snow_labs_rxnorm_to_mesh_code_mapper.johnsnowlabs_folder.en_rxnorm_mes_mapping_gpu",
        57: "john_snow_labs_mesh_to_umls_code_mapper.johnsnowlabs_folder.en_mesh_umls_mapping_gpu",
        58: "john_snow_labs_medication_coder.johnsnowlabs_folder.en_resolve_medication_gpu",
    },
    "ListingId": {
        0: "cf968e18-d8d8-4b9f-b79a-fc4e4a3337a7",
        1: "f29c9e93-8f2d-4969-b472-f3524bdfd883",
        2: "e1a5be5d-b799-4bd1-a664-c31b9c47225f",
        3: "a299884a-7a95-4ddf-96e0-b8594c4290d3",
        4: "153b223a-d73f-479f-a51c-8905434b545d",
        5: "80b9ec4d-c7b8-401c-b177-aa388259f422",
        6: "29d9158d-33ed-4805-ad4b-92ff210e808b",
        7: "7afe6ca0-ad66-489b-b2d0-b31b0644d053",
        8: "c2469843-c104-4201-9db5-ba1542823448",
        9: "2b8709b8-4a42-406b-bd93-43172eae07b9",
        10: "d07d7654-d483-4f1d-bb26-13b02197b87f",
        11: "48daa468-2417-437a-b59d-0a06a8935d99",
        12: "10de7650-8e88-461e-bea4-6c38bb3f0d00",
        13: "3ec7ae21-ef22-4ae3-ac52-70a0ef4dedc2",
        14: "a516cbd4-107d-4194-ab02-74095c155f34",
        15: "f52c1b80-794f-457f-bb94-51c5df3ee4be",
        16: "685dab5c-03cb-4545-9a71-e08ae72946e6",
        17: "074bbfa7-20ad-4444-8e0a-bc05ff07d6ea",
        18: "8dd5abe1-4df8-41b5-a251-dcf3b161f5c3",
        19: "68c7064e-c1dc-459f-971b-e759bb80810d",
        20: "c23fe435-9461-4d0e-a829-d64f6fecb659",
        21: "eb2042f5-8a50-459c-8884-e11f9573c618",
        22: "251eeb55-2ff6-4e7f-ab92-dbbbabe5c2a4",
        23: "bb9e02a3-3926-4125-bfdf-49cdef5d1ca7",
        24: "ac413121-3018-4a1f-95c1-fadbbf321708",
        25: "b3bac611-ed88-4391-b013-08de4e32a503",
        26: "facfaf55-00f6-496c-a8db-a395631130ec",
        27: "37b22ea9-caf2-429e-ac3c-8b1adb0324cc",
        28: "de82227b-b6d2-4243-857f-071c4b860e8b",
        29: "00affefe-d268-4bd2-9fa1-8d3a07199be0",
        30: "a5111c18-1c60-4c02-a25a-fa709e819ecd",
        31: "88bf2ba0-fb95-44f8-801d-325a720b6f03",
        32: "bfb569e4-69a2-4f4b-8d6e-e306982e4a95",
        33: "1edf9844-470b-4e3a-a157-3ed8c5af89a9",
        34: "8a7ef1cd-c307-4bc7-94c7-4b812a64d3c4",
        35: "5e6f0af1-bcc7-4aa6-a1de-21ca58638fce",
        36: "c600aad0-84c6-4f3d-ae92-5541d3cad171",
        37: "c0456a4c-beeb-4258-9b4a-12e0964e33e5",
        38: "7f5d667a-82a9-48b8-b559-408c589259cd",
        39: "833ccefd-89a0-4e74-8b1d-ddb32181693b",
        40: "51ec7304-2cce-4c60-830e-9fe735ac2a89",
        41: "2a078943-c56d-48b1-a99d-3addb38d688f",
        42: "40f9b4db-ba84-4af1-aba6-57abfba24676",
        43: "9956314c-f7a4-42e0-8081-a7f933ea0c8c",
        44: "e3d2930b-b3bc-4f26-9d35-e81fa9fdd161",
        45: "64d6608b-8341-4b14-8edd-c1a1b31823a6",
        46: "4d973f25-f457-4af7-8ea7-7c3fddaf9493",
        47: "bf4cd2a7-55b5-40fa-b010-c89f54b29ab8",
        48: "0fa941ad-cf3d-4b03-8e46-854e6299afe8",
        49: "7487be7b-0f6d-4aaf-82ef-ea2b1833685a",
        50: "0ee92a5c-35f1-40c9-a7b3-0282e67d9bd1",
        51: "7418db61-8ff0-49db-ae87-756fc17382fc",
        52: "5c645046-e195-4164-a5f5-d3015a7f7647",
        53: "379d172e-cc3f-4c17-ae25-6c83f91e2e6a",
        54: "0a5aebb4-6f73-4af6-96d4-f8d2acfce25d",
        55: "83306cbb-ac15-46e4-86a1-43036dd0c1ec",
        56: "b1a7c3ca-3d76-4434-a979-7ed9ad720530",
        57: "5b4cc372-b9b5-4632-9090-89ddfbef7fe5",
        58: "c0511f92-316e-4106-b09c-b3f55fcca24f",
    },
    "DropDownId": {
        0: "42. Extract Disease and Syndrom entities and their UMLS Codes",
        1: "29. Detect Healthcare Professional Consult documents",
        2: "48. Extract procedures and measurements and their corresponding CPT codes",
        3: "60. Extract Laboratory Observations and the corresponding LOINC codes",
        4: "18. Guideline Summarizer for Asthma & Breast Cancer",
        5: "40. Extract Clinical Findings and the corresponding ICD10CM codes",
        6: "45. Extract Clinical Findings and their UMLS Codes",
        7: "32. Extract neurologic deficits related to Stroke Scale (NIHSS)",
        8: "44. Extract Clinical Findings and the corresponding ICD 9 codes",
        9: "39. Extract Drugs and the correspondingt RXNORM codes",
        10: "47. Extract phenotypic abnormalities and the coresponding HPO codes ",
        11: "30. Detect Drug Side Effect Narratives",
        12: "38. Extract  Drugs and Substances and their UMLS Codes",
        13: "19. Summarize Clinical Notes in Laymen Terms ",
        14: "25. Extract findings in radiology reports",
        15: "35. Detect Pathogen, Medical Condition and Medicine",
        16: "28. Extract patient information from patient narratives",
        17: "52. Resolve Oncology terminology with ICD-O Taxonomy",
        18: "12. Clinical De-identification for Portuguese (Obfuscate)",
        19: "16. Clinical De-identification for Romanian (Obfuscate)",
        20: "31. Extract Social Determinants of Health",
        21: "10. Clinical De-identification for French (Obfuscate)",
        22: "20. Summarize Clinical Question Notes",
        23: "6. Clinical De-identification for Spanish (Obfuscate)",
        24: "8. Clinical De-identification for Italian (Obfuscate)",
        25: "14. Clinical De-identification for Arabic (Obfuscate)",
        26: "2. Clinical De-identification (Obfuscate)",
        27: "4. Clinical De-identification for German (Obfuscate)",
        28: "56. SNOMED Clinical Health Information Coder",
        29: "27. Extract oncological entities and relations",
        30: "11. Clinical De-identification for Portuguese (Mask)",
        31: "22. Clinical Text Summarization",
        32: "46. Extract Drugs and their UMLS Codes",
        33: "49. ICD-10-CM to SNOMED Code Mapper",
        34: "15. Clinical De-identification for Romanian (Mask)",
        35: "58. SNOMED to ICD-10-CM Code Mapper",
        36: "9. Clinical De-identification for French (Mask)",
        37: "5. Clinical De-identification for Spanish (Mask)",
        38: "13. Clinical De-identification for Arabic (Mask)",
        39: "3. Clinical De-identification for German (Mask)",
        40: "7. Clinical De-identification forItalian (Mask)",
        41: None,
        42: "1. Clinical De-identification (Mask)",
        43: "21. Summarize PubMed Research",
        44: "57. SNOMED Codes to ICDO Codes Mapper",
        45: "26. Extract Adverse Drug Events (ADE)",
        46: "33. Extract clinical risk factors",
        47: "54. RxNorm to NDC Code Converter",
        48: "17. Summarize Radiology Reports",
        49: "37. Extract Anatomical Structures",
        50: "43. ICD-10-CM to UMLS Code Mapper",
        51: "36. Extract Living Species",
        52: "50. ICD-10 to ICD-9 Code Converter",
        53: "55. RxNorm to UMLS Code Mapper",
        54: "34. Detect Cancer Genetics",
        55: "59. SNOMED to UMLS Code Mapper",
        56: "53. RxNorm to MeSH Code Mapper",
        57: "51. MeSH to UMLS Code Mapper",
        58: "41. Medication Coder",
    },
    "Id": {
        0: 42.0,
        1: 29.0,
        2: 48.0,
        3: 60.0,
        4: 18.0,
        5: 40.0,
        6: 45.0,
        7: 32.0,
        8: 44.0,
        9: 39.0,
        10: 47.0,
        11: 30.0,
        12: 38.0,
        13: 19.0,
        14: 25.0,
        15: 35.0,
        16: 28.0,
        17: 52.0,
        18: 12.0,
        19: 16.0,
        20: 31.0,
        21: 10.0,
        22: 20.0,
        23: 6.0,
        24: 8.0,
        25: 14.0,
        26: 2.0,
        27: 4.0,
        28: 56.0,
        29: 27.0,
        30: 11.0,
        31: 22.0,
        32: 46.0,
        33: 49.0,
        34: 15.0,
        35: 58.0,
        36: 9.0,
        37: 5.0,
        38: 13.0,
        39: 3.0,
        40: 7.0,
        41: 24.0,
        42: 1.0,
        43: 21.0,
        44: 57.0,
        45: 26.0,
        46: 33.0,
        47: 54.0,
        48: 17.0,
        49: 37.0,
        50: 43.0,
        51: 36.0,
        52: 50.0,
        53: 55.0,
        54: 34.0,
        55: 59.0,
        56: 53.0,
        57: 51.0,
        58: 41.0,
    },
    "Title_d": {
        0: "[Extract Disease and Syndrom entities and their UMLS Codes](./marketplace/consumer/listings/cf968e18-d8d8-4b9f-b79a-fc4e4a3337a7)",
        1: "[Detect Healthcare Professional Consult documents](./marketplace/consumer/listings/f29c9e93-8f2d-4969-b472-f3524bdfd883)",
        2: "[Extract procedures and measurements and their corresponding CPT codes](./marketplace/consumer/listings/e1a5be5d-b799-4bd1-a664-c31b9c47225f)",
        3: "[Extract Laboratory Observations and the corresponding LOINC codes](./marketplace/consumer/listings/a299884a-7a95-4ddf-96e0-b8594c4290d3)",
        4: "[Guideline Summarizer for Asthma & Breast Cancer](./marketplace/consumer/listings/153b223a-d73f-479f-a51c-8905434b545d)",
        5: "[Extract Clinical Findings and the corresponding ICD10CM codes](./marketplace/consumer/listings/80b9ec4d-c7b8-401c-b177-aa388259f422)",
        6: "[Extract Clinical Findings and their UMLS Codes](./marketplace/consumer/listings/29d9158d-33ed-4805-ad4b-92ff210e808b)",
        7: "[Extract neurologic deficits related to Stroke Scale (NIHSS)](./marketplace/consumer/listings/7afe6ca0-ad66-489b-b2d0-b31b0644d053)",
        8: "[Extract Clinical Findings and the corresponding ICD 9 codes](./marketplace/consumer/listings/c2469843-c104-4201-9db5-ba1542823448)",
        9: "[Extract Drugs and the correspondingt RXNORM codes](./marketplace/consumer/listings/2b8709b8-4a42-406b-bd93-43172eae07b9)",
        10: "[Extract phenotypic abnormalities and the coresponding HPO codes ](./marketplace/consumer/listings/d07d7654-d483-4f1d-bb26-13b02197b87f)",
        11: "[Detect Drug Side Effect Narratives](./marketplace/consumer/listings/48daa468-2417-437a-b59d-0a06a8935d99)",
        12: "[Extract  Drugs and Substances and their UMLS Codes](./marketplace/consumer/listings/10de7650-8e88-461e-bea4-6c38bb3f0d00)",
        13: "[Summarize Clinical Notes in Laymen Terms ](./marketplace/consumer/listings/3ec7ae21-ef22-4ae3-ac52-70a0ef4dedc2)",
        14: "[Extract findings in radiology reports](./marketplace/consumer/listings/a516cbd4-107d-4194-ab02-74095c155f34)",
        15: "[Detect Pathogen, Medical Condition and Medicine](./marketplace/consumer/listings/f52c1b80-794f-457f-bb94-51c5df3ee4be)",
        16: "[Extract patient information from patient narratives](./marketplace/consumer/listings/685dab5c-03cb-4545-9a71-e08ae72946e6)",
        17: "[Resolve Oncology terminology with ICD-O Taxonomy](./marketplace/consumer/listings/074bbfa7-20ad-4444-8e0a-bc05ff07d6ea)",
        18: "[Clinical De-identification for Portuguese (Obfuscate)](./marketplace/consumer/listings/8dd5abe1-4df8-41b5-a251-dcf3b161f5c3)",
        19: "[Clinical De-identification for Romanian (Obfuscate)](./marketplace/consumer/listings/68c7064e-c1dc-459f-971b-e759bb80810d)",
        20: "[Extract Social Determinants of Health](./marketplace/consumer/listings/c23fe435-9461-4d0e-a829-d64f6fecb659)",
        21: "[Clinical De-identification for French (Obfuscate)](./marketplace/consumer/listings/eb2042f5-8a50-459c-8884-e11f9573c618)",
        22: "[Summarize Clinical Question Notes](./marketplace/consumer/listings/251eeb55-2ff6-4e7f-ab92-dbbbabe5c2a4)",
        23: "[Clinical De-identification for Spanish (Obfuscate)](./marketplace/consumer/listings/bb9e02a3-3926-4125-bfdf-49cdef5d1ca7)",
        24: "[Clinical De-identification for Italian (Obfuscate)](./marketplace/consumer/listings/ac413121-3018-4a1f-95c1-fadbbf321708)",
        25: "[Clinical De-identification for Arabic (Obfuscate)](./marketplace/consumer/listings/b3bac611-ed88-4391-b013-08de4e32a503)",
        26: "[Clinical De-identification (Obfuscate)](./marketplace/consumer/listings/facfaf55-00f6-496c-a8db-a395631130ec)",
        27: "[Clinical De-identification for German (Obfuscate)](./marketplace/consumer/listings/37b22ea9-caf2-429e-ac3c-8b1adb0324cc)",
        28: "[SNOMED Clinical Health Information Coder](./marketplace/consumer/listings/de82227b-b6d2-4243-857f-071c4b860e8b)",
        29: "[Extract oncological entities and relations](./marketplace/consumer/listings/00affefe-d268-4bd2-9fa1-8d3a07199be0)",
        30: "[Clinical De-identification for Portuguese (Mask)](./marketplace/consumer/listings/a5111c18-1c60-4c02-a25a-fa709e819ecd)",
        31: "[Clinical Text Summarization](./marketplace/consumer/listings/88bf2ba0-fb95-44f8-801d-325a720b6f03)",
        32: "[Extract Drugs and their UMLS Codes](./marketplace/consumer/listings/bfb569e4-69a2-4f4b-8d6e-e306982e4a95)",
        33: "[ICD-10-CM to SNOMED Code Mapper](./marketplace/consumer/listings/1edf9844-470b-4e3a-a157-3ed8c5af89a9)",
        34: "[Clinical De-identification for Romanian (Mask)](./marketplace/consumer/listings/8a7ef1cd-c307-4bc7-94c7-4b812a64d3c4)",
        35: "[SNOMED to ICD-10-CM Code Mapper](./marketplace/consumer/listings/5e6f0af1-bcc7-4aa6-a1de-21ca58638fce)",
        36: "[Clinical De-identification for French (Mask)](./marketplace/consumer/listings/c600aad0-84c6-4f3d-ae92-5541d3cad171)",
        37: "[Clinical De-identification for Spanish (Mask)](./marketplace/consumer/listings/c0456a4c-beeb-4258-9b4a-12e0964e33e5)",
        38: "[Clinical De-identification for Arabic (Mask)](./marketplace/consumer/listings/7f5d667a-82a9-48b8-b559-408c589259cd)",
        39: "[Clinical De-identification for German (Mask)](./marketplace/consumer/listings/833ccefd-89a0-4e74-8b1d-ddb32181693b)",
        40: "[Clinical De-identification forItalian (Mask)](./marketplace/consumer/listings/51ec7304-2cce-4c60-830e-9fe735ac2a89)",
        41: "[Extract clinical events and find temporal relations (ERA)](./marketplace/consumer/listings/2a078943-c56d-48b1-a99d-3addb38d688f)",
        42: "[Clinical De-identification (Mask)](./marketplace/consumer/listings/40f9b4db-ba84-4af1-aba6-57abfba24676)",
        43: "[Summarize PubMed Research](./marketplace/consumer/listings/9956314c-f7a4-42e0-8081-a7f933ea0c8c)",
        44: "[SNOMED Codes to ICDO Codes Mapper](./marketplace/consumer/listings/e3d2930b-b3bc-4f26-9d35-e81fa9fdd161)",
        45: "[Extract Adverse Drug Events (ADE)](./marketplace/consumer/listings/64d6608b-8341-4b14-8edd-c1a1b31823a6)",
        46: "[Extract clinical risk factors](./marketplace/consumer/listings/4d973f25-f457-4af7-8ea7-7c3fddaf9493)",
        47: "[RxNorm to NDC Code Converter](./marketplace/consumer/listings/bf4cd2a7-55b5-40fa-b010-c89f54b29ab8)",
        48: "[Summarize Radiology Reports](./marketplace/consumer/listings/0fa941ad-cf3d-4b03-8e46-854e6299afe8)",
        49: "[Extract Anatomical Structures](./marketplace/consumer/listings/7487be7b-0f6d-4aaf-82ef-ea2b1833685a)",
        50: "[ ICD-10-CM to UMLS Code Mapper](./marketplace/consumer/listings/0ee92a5c-35f1-40c9-a7b3-0282e67d9bd1)",
        51: "[Extract Living Species](./marketplace/consumer/listings/7418db61-8ff0-49db-ae87-756fc17382fc)",
        52: "[ICD-10 to ICD-9 Code Converter](./marketplace/consumer/listings/5c645046-e195-4164-a5f5-d3015a7f7647)",
        53: "[RxNorm to UMLS Code Mapper](./marketplace/consumer/listings/379d172e-cc3f-4c17-ae25-6c83f91e2e6a)",
        54: "[Detect Cancer Genetics](./marketplace/consumer/listings/0a5aebb4-6f73-4af6-96d4-f8d2acfce25d)",
        55: "[SNOMED to UMLS Code Mapper](./marketplace/consumer/listings/83306cbb-ac15-46e4-86a1-43036dd0c1ec)",
        56: "[RxNorm to MeSH Code Mapper](./marketplace/consumer/listings/b1a7c3ca-3d76-4434-a979-7ed9ad720530)",
        57: "[MeSH to UMLS Code Mapper](./marketplace/consumer/listings/5b4cc372-b9b5-4632-9090-89ddfbef7fe5)",
        58: "[Medication Coder](./marketplace/consumer/listings/c0511f92-316e-4106-b09c-b3f55fcca24f)",
    },
}

# TODO stop using dis?
titles_in_marketplace = [
    "Resolve Oncology terminology with ICD-O Taxonomy",
    "Detect Cancer Genetics",
    "Summarize Radiology Reports",
    "Guideline Summarizer for Asthma & Breast Cancer",
    "Summarize Clinical Question Notes",
    "Extract clinical events and find temporal relations",
    "Clinical De-identification (Mask)",
    "Detect Drug Side Effect Narratives",
    "Extract clinical risk factors",
    "Clinical De-identification for Italian (Mask)",
    "Extract Adverse Drug Events (ADE)",
    "Extract Living Species",
    "Extract Anatomical Structures",
    "Extract neurologic deficits related to Stroke Scale (NIHSS)",
    "Clinical De-identification for Arabic (Mask)",
    "Clinical De-identification for German (Mask)",
    "Clinical De-identification (Mask)",
    "Clinical Text Summarization",
    "Clinical De-identification for Romanian (Mask)",
    "Summarize PubMed Research",
    "Extract Laboratory Observations and the corresponding LOINC codes",
    "Clinical De-identification for Portuguese (Mask)",
    "Extract findings in radiology reports",
    "Clinical De-identification for Spanish (Mask)",
    "Extract Social Determinants of Health",
    "Extract Clinical Findings and the corresponding ICD 9 codes",
    "Clinical De-identification for French (Mask)",
    "Extract phenotypic abnormalities and the coresponding HPO codes",
    "Extract procedures and measurements and their corresponding CPT codes",
    "SNOMED Codes to ICDO Codes Mapper",
    "Detect Healthcare Professional Consult documents",
    "Detect Pathogen, Medical Condition and Medicine",
]

# TODO replace (my.JohnSnowLabs.com) with (https://my.johnsnowlabs.com/)
# TODO add 4. Your input strings must be of the format  **CONTEXT ||| QUESTION** i.e. **My name is Christian ||| What is my name?** .  if QA model
