# coding: utf-8

"""
    Lead Scraping Service API

    Vector Lead Scraping Service API - Manages Lead Scraping Jobs

    The version of the OpenAPI document: 1.0
    Contact: yoanyomba@vector.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from playbookmedia_backend_client_sdk.models.create_api_key_request import CreateAPIKeyRequest

class TestCreateAPIKeyRequest(unittest.TestCase):
    """CreateAPIKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAPIKeyRequest:
        """Test CreateAPIKeyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAPIKeyRequest`
        """
        model = CreateAPIKeyRequest()
        if include_optional:
            return CreateAPIKeyRequest(
                organization_id = '',
                workspace_id = '',
                tenant_id = '',
                account_id = '',
                name = '',
                description = '',
                scopes = [
                    ''
                    ],
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                max_uses = 56,
                allowed_ips = [
                    ''
                    ],
                rate_limit = 56,
                enforce_signing = True,
                allowed_signature_algorithms = [
                    ''
                    ],
                enforce_mutual_tls = True,
                alert_emails = [
                    ''
                    ],
                alert_on_quota_threshold = True,
                quota_alert_threshold = 1.337
            )
        else:
            return CreateAPIKeyRequest(
        )
        """

    def testCreateAPIKeyRequest(self):
        """Test CreateAPIKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
