# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.stream_subscription_sink_type import StreamSubscriptionSinkType

class TestStreamSubscriptionSinkType(unittest.TestCase):
    """StreamSubscriptionSinkType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamSubscriptionSinkType(self):
        """Test StreamSubscriptionSinkType"""
        # inst = StreamSubscriptionSinkType()

if __name__ == '__main__':
    unittest.main()
