# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.service_profile_link_protocol_config_encapsulation_strategy import ServiceProfileLinkProtocolConfigEncapsulationStrategy

class TestServiceProfileLinkProtocolConfigEncapsulationStrategy(unittest.TestCase):
    """ServiceProfileLinkProtocolConfigEncapsulationStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceProfileLinkProtocolConfigEncapsulationStrategy(self):
        """Test ServiceProfileLinkProtocolConfigEncapsulationStrategy"""
        # inst = ServiceProfileLinkProtocolConfigEncapsulationStrategy()

if __name__ == '__main__':
    unittest.main()
