# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.network_change_status import NetworkChangeStatus

class TestNetworkChangeStatus(unittest.TestCase):
    """NetworkChangeStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkChangeStatus(self):
        """Test NetworkChangeStatus"""
        # inst = NetworkChangeStatus()

if __name__ == '__main__':
    unittest.main()
