# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.sort_item_property import SortItemProperty

class TestSortItemProperty(unittest.TestCase):
    """SortItemProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortItemProperty(self):
        """Test SortItemProperty"""
        # inst = SortItemProperty()

if __name__ == '__main__':
    unittest.main()
