# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.link_protocol_request_type import LinkProtocolRequestType

class TestLinkProtocolRequestType(unittest.TestCase):
    """LinkProtocolRequestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkProtocolRequestType(self):
        """Test LinkProtocolRequestType"""
        # inst = LinkProtocolRequestType()

if __name__ == '__main__':
    unittest.main()
