# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.cloud_router_change import CloudRouterChange

class TestCloudRouterChange(unittest.TestCase):
    """CloudRouterChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CloudRouterChange:
        """Test CloudRouterChange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CloudRouterChange`
        """
        model = CloudRouterChange()
        if include_optional:
            return CloudRouterChange(
                uuid = '',
                type = 'ROUTER_UPDATE',
                status = 'COMPLETED',
                created_date_time = '2020-11-06T07:00Z',
                updated_date_time = '2020-11-06T07:00Z',
                information = '',
                data = equinix.services.fabricv4.models.cloud_router_change_operation.CloudRouterChangeOperation(
                    op = 'replace', 
                    path = '', 
                    value = equinix.services.fabricv4.models.value.value(), )
            )
        else:
            return CloudRouterChange(
                type = 'ROUTER_UPDATE',
                updated_date_time = '2020-11-06T07:00Z',
        )
        """

    def testCloudRouterChange(self):
        """Test CloudRouterChange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
