# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.route_filters_change_type import RouteFiltersChangeType

class TestRouteFiltersChangeType(unittest.TestCase):
    """RouteFiltersChangeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRouteFiltersChangeType(self):
        """Test RouteFiltersChangeType"""
        # inst = RouteFiltersChangeType()

if __name__ == '__main__':
    unittest.main()
