# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.service_token_search_expression import ServiceTokenSearchExpression

class TestServiceTokenSearchExpression(unittest.TestCase):
    """ServiceTokenSearchExpression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceTokenSearchExpression:
        """Test ServiceTokenSearchExpression
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceTokenSearchExpression`
        """
        model = ServiceTokenSearchExpression()
        if include_optional:
            return ServiceTokenSearchExpression(
                var_and = [
                    equinix.services.fabricv4.models.service_token_search_expression.ServiceTokenSearchExpression(
                        and = [
                            equinix.services.fabricv4.models.service_token_search_expression.ServiceTokenSearchExpression(
                                and = , 
                                property = '/uuid', 
                                operator = '=', 
                                values = [
                                    ''
                                    ], )
                            ], 
                        property = '/uuid', 
                        operator = '=', 
                        values = [
                            ''
                            ], )
                    ],
                var_property = '/uuid',
                operator = '=',
                values = [
                    ''
                    ]
            )
        else:
            return ServiceTokenSearchExpression(
        )
        """

    def testServiceTokenSearchExpression(self):
        """Test ServiceTokenSearchExpression"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
