# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.fabricv4.models.port_notification_type import PortNotificationType

class TestPortNotificationType(unittest.TestCase):
    """PortNotificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortNotificationType(self):
        """Test PortNotificationType"""
        # inst = PortNotificationType()

if __name__ == '__main__':
    unittest.main()
