from muphyn.utils.paths import ROOT_DIR

class ApplicationIcons:

    class BoxIcons:
        Addition = ROOT_DIR + "/assets/BoxIcons/addition.svg"
        BandPassFilter = ROOT_DIR + "/assets/BoxIcons/band_pass_filter.svg"
        BoxParameterWidgetsTest = ROOT_DIR + "/assets/BoxIcons/TestBoxIcon/BoxParameterWidgetsTest.svg"
        Constant = ROOT_DIR + "/assets/BoxIcons/constant.svg"
        Derivator = ROOT_DIR + "/assets/BoxIcons/derivator.svg"
        Graph = ROOT_DIR + "/assets/BoxIcons/graph.svg"
        HighPassFilter = ROOT_DIR + "/assets/BoxIcons/high_pass_filter.svg"
        Impulse = ROOT_DIR + "/assets/BoxIcons/impulse.svg"
        InfiniteInputTest = ROOT_DIR + "/assets/BoxIcons/TestBoxIcon/InfiniteInputTest.svg"
        InfiniteOutputTest = ROOT_DIR + "/assets/BoxIcons/TestBoxIcon/InfiniteOutputTest.svg"
        Integrator = ROOT_DIR + "/assets/BoxIcons/integrator.svg"
        LowPassFilter = ROOT_DIR + "/assets/BoxIcons/low_pass_filter.svg"
        Multiplication = ROOT_DIR + "/assets/BoxIcons/multiplication.svg"
        Noise = ROOT_DIR + "/assets/BoxIcons/noise.svg"
        NotchFilter = ROOT_DIR + "/assets/BoxIcons/notch_filter.svg"
        OmLogoSmall = ROOT_DIR + "/assets/BoxIcons/omlogosmall.svg"
        Ramp = ROOT_DIR + "/assets/BoxIcons/ramp.svg"
        SawTooth = ROOT_DIR + "/assets/BoxIcons/saw_tooth.svg"
        Sine = ROOT_DIR + "/assets/BoxIcons/sine.svg"
        Square = ROOT_DIR + "/assets/BoxIcons/square.svg"
        Step = ROOT_DIR + "/assets/BoxIcons/step.svg"

    class Components:

        class Electrics:
            Capacitor = ROOT_DIR + "/assets/Components/Electrics/capacitor.svg"
            Conductor = ROOT_DIR + "/assets/Components/Electrics/conductor.svg"
            ConstantCurrentSource = ROOT_DIR + "/assets/Components/Electrics/constant_current_source.svg"
            ConstantVoltageSource = ROOT_DIR + "/assets/Components/Electrics/constant_voltage_source.svg"
            CosineCurrentSource = ROOT_DIR + "/assets/Components/Electrics/cosine_current_source.svg"
            CosineVoltageSource = ROOT_DIR + "/assets/Components/Electrics/cosine_voltage_source.svg"
            ExpCosineCurrentSource = ROOT_DIR + "/assets/Components/Electrics/exp_cosine_current_source.svg"
            ExpCosineVoltageSource = ROOT_DIR + "/assets/Components/Electrics/exp_cosine_voltage_source.svg"
            ExpSineCurrentSource = ROOT_DIR + "/assets/Components/Electrics/exp_sine_current_source.svg"
            ExpSineVoltageSource = ROOT_DIR + "/assets/Components/Electrics/exp_sine_voltage_source.svg"
            Ground = ROOT_DIR + "/assets/Components/Electrics/ground.svg"
            Gyrator = ROOT_DIR + "/assets/Components/Electrics/gyrator.svg"
            inductor = ROOT_DIR + "/assets/Components/Electrics/inductor.svg"
            NTransformer = ROOT_DIR + "/assets/Components/Electrics/n_transformer.svg"
            PulseVoltageSource = ROOT_DIR + "/assets/Components/Electrics/pulse_voltage_source.svg"
            RampCurrentSource = ROOT_DIR + "/assets/Components/Electrics/ramp_current_source.svg"
            RampVoltageSource = ROOT_DIR + "/assets/Components/Electrics/ramp_voltage_source.svg"
            Resistor = ROOT_DIR + "/assets/Components/Electrics/resistor.svg"
            SaturatingInductor = ROOT_DIR + "/assets/Components/Electrics/saturating_inductor.svg"
            SawtoothCurrentSource = ROOT_DIR + "/assets/Components/Electrics/sawtooth_current_source.svg"
            SawtoothVoltageSource = ROOT_DIR + "/assets/Components/Electrics/sawtooth_voltage_source.svg"
            SignalCurrentSource = ROOT_DIR + "/assets/Components/Electrics/signal_current_source.svg"
            SignalVoltageSource = ROOT_DIR + "/assets/Components/Electrics/signal_voltage_source.svg"
            SineCurrentSource = ROOT_DIR + "/assets/Components/Electrics/sine_current_source.svg"
            SineVoltageSource = ROOT_DIR + "/assets/Components/Electrics/sine_voltage_source.svg"
            StepCurrentSource = ROOT_DIR + "/assets/Components/Electrics/step_current_source.svg"
            StepVoltageSource = ROOT_DIR + "/assets/Components/Electrics/step_voltage_source.svg"
            Transformer = ROOT_DIR + "/assets/Components/Electrics/transformer.svg"
            TrapezoidCurrentSource = ROOT_DIR + "/assets/Components/Electrics/trapezoid_current_source.svg"
            TrapezoidVoltageSource = ROOT_DIR + "/assets/Components/Electrics/trapezoid_voltage_source.svg"
            VariableConductor = ROOT_DIR + "/assets/Components/Electrics/variable_conductor.svg"
            VariableAmplitudeFrequencyCosineCurrentSource = ROOT_DIR + "/assets/Components/Electrics/variable_amplitude_frequency_cosine_current_source.svg"
            VariableAmplitudeFrequencyCosineVoltageSource = ROOT_DIR + "/assets/Components/Electrics/variable_amplitude_frequency_cosine_voltage_source.svg"
            VariableAmplitudeFrequencySineCurrentSource = ROOT_DIR + "/assets/Components/Electrics/variable_amplitude_frequency_sine_current_source.svg"
            VariableAmplitudeFrequencySineVoltageSource = ROOT_DIR + "/assets/Components/Electrics/variable_amplitude_frequency_sine_voltage_source.svg"
            VariableCapacitor = ROOT_DIR + "/assets/Components/Electrics/variable_capacitor.svg"
            VariableInductor = ROOT_DIR + "/assets/Components/Electrics/variable_inductor.svg"
            VariableResistor = ROOT_DIR + "/assets/Components/Electrics/variable_resistor.svg"

    class General:

        class Checkbox:
            Checked = ROOT_DIR + "/assets/GeneralIcons/checkbox/checked.svg"
            Checked2 = ROOT_DIR + "/assets/GeneralIcons/checkbox/checked2.svg"
            CheckedHover = ROOT_DIR + "/assets/GeneralIcons/checkbox/checked_hover.svg"
            CheckedPressed = ROOT_DIR + "/assets/GeneralIcons/checkbox/checked_pressed.svg"
            Unchecked = ROOT_DIR + "/assets/GeneralIcons/checkbox/unchecked.svg"
            UncheckedHover = ROOT_DIR + "/assets/GeneralIcons/checkbox/unchecked_hover.svg"
            UncheckedPressed = ROOT_DIR + "/assets/GeneralIcons/checkbox/unchecked_pressed.svg"

        Delete = ROOT_DIR + "/assets/GeneralIcons/delete.svg"
        DownArrow = ROOT_DIR + "/assets/GeneralIcons/down_arrow.svg"
        Error = ROOT_DIR + "/assets/GeneralIcons/error.svg"
        LeftArrow = ROOT_DIR + "/assets/GeneralIcons/left_arrow.svg"
        Redo = ROOT_DIR + "/assets/GeneralIcons/redo.svg"
        Refresh = ROOT_DIR + "/assets/GeneralIcons/refresh.svg"
        RightArrow = ROOT_DIR + "/assets/GeneralIcons/right_arrow.svg"
        RotateLeft = ROOT_DIR + "/assets/GeneralIcons/rotate_left.svg"
        RotateRight = ROOT_DIR + "/assets/GeneralIcons/rotate_right.svg"
        Start = ROOT_DIR + "/assets/GeneralIcons/start.svg"
        Stop = ROOT_DIR + "/assets/GeneralIcons/stop.svg"
        undo = ROOT_DIR + "/assets/GeneralIcons/undo.svg"
        upArrow = ROOT_DIR + "/assets/GeneralIcons/up_arrow.svg"

    MuphynIcon = ROOT_DIR + "/assets/MuPhyN.ico"
    MuphynSplashScreen = ROOT_DIR + "/assets/splashscreen.png"
    MuphynSvg = ROOT_DIR + "/assets/MuPhyN.svg"