# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from dima_test_sdk.models.payments_detailed_report_container_data_inner_contract import PaymentsDetailedReportContainerDataInnerContract
from dima_test_sdk.models.payments_detailed_report_container_data_inner_invoice import PaymentsDetailedReportContainerDataInnerInvoice
from dima_test_sdk.models.payments_detailed_report_container_data_inner_line_item import PaymentsDetailedReportContainerDataInnerLineItem
from dima_test_sdk.models.payments_detailed_report_container_data_inner_payment import PaymentsDetailedReportContainerDataInnerPayment
from typing import Optional, Set
from typing_extensions import Self

class PaymentsDetailedReportContainerDataInner(BaseModel):
    """
    PaymentsDetailedReportContainerDataInner
    """ # noqa: E501
    invoice: Optional[PaymentsDetailedReportContainerDataInnerInvoice] = None
    line_item: Optional[PaymentsDetailedReportContainerDataInnerLineItem] = None
    payment: Optional[PaymentsDetailedReportContainerDataInnerPayment] = None
    contract: Optional[PaymentsDetailedReportContainerDataInnerContract] = None
    __properties: ClassVar[List[str]] = ["invoice", "line_item", "payment", "contract"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentsDetailedReportContainerDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of invoice
        if self.invoice:
            _dict['invoice'] = self.invoice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of line_item
        if self.line_item:
            _dict['line_item'] = self.line_item.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment
        if self.payment:
            _dict['payment'] = self.payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contract
        if self.contract:
            _dict['contract'] = self.contract.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentsDetailedReportContainerDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invoice": PaymentsDetailedReportContainerDataInnerInvoice.from_dict(obj["invoice"]) if obj.get("invoice") is not None else None,
            "line_item": PaymentsDetailedReportContainerDataInnerLineItem.from_dict(obj["line_item"]) if obj.get("line_item") is not None else None,
            "payment": PaymentsDetailedReportContainerDataInnerPayment.from_dict(obj["payment"]) if obj.get("payment") is not None else None,
            "contract": PaymentsDetailedReportContainerDataInnerContract.from_dict(obj["contract"]) if obj.get("contract") is not None else None
        })
        return _obj


