# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.list_onboarding_tracker200_response_data_inner_hris_profile import ListOnboardingTracker200ResponseDataInnerHrisProfile

class TestListOnboardingTracker200ResponseDataInnerHrisProfile(unittest.TestCase):
    """ListOnboardingTracker200ResponseDataInnerHrisProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOnboardingTracker200ResponseDataInnerHrisProfile:
        """Test ListOnboardingTracker200ResponseDataInnerHrisProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOnboardingTracker200ResponseDataInnerHrisProfile`
        """
        model = ListOnboardingTracker200ResponseDataInnerHrisProfile()
        if include_optional:
            return ListOnboardingTracker200ResponseDataInnerHrisProfile(
                oid = '150f635e-fae1-4b9d-9f86-768bbbac3698',
                work_email = '2635e57fe2a571c1aadba2a77f178e2b@test.com'
            )
        else:
            return ListOnboardingTracker200ResponseDataInnerHrisProfile(
        )
        """

    def testListOnboardingTracker200ResponseDataInnerHrisProfile(self):
        """Test ListOnboardingTracker200ResponseDataInnerHrisProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
