# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.retrieve_deel_invoices200_response_page import RetrieveDeelInvoices200ResponsePage

class TestRetrieveDeelInvoices200ResponsePage(unittest.TestCase):
    """RetrieveDeelInvoices200ResponsePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveDeelInvoices200ResponsePage:
        """Test RetrieveDeelInvoices200ResponsePage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveDeelInvoices200ResponsePage`
        """
        model = RetrieveDeelInvoices200ResponsePage()
        if include_optional:
            return RetrieveDeelInvoices200ResponsePage(
                offset = 0,
                total_rows = 0,
                items_per_page = 10
            )
        else:
            return RetrieveDeelInvoices200ResponsePage(
                offset = 0,
                total_rows = 0,
                items_per_page = 10,
        )
        """

    def testRetrieveDeelInvoices200ResponsePage(self):
        """Test RetrieveDeelInvoices200ResponsePage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
