# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.page_info_without_cursor import PageInfoWithoutCursor

class TestPageInfoWithoutCursor(unittest.TestCase):
    """PageInfoWithoutCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageInfoWithoutCursor:
        """Test PageInfoWithoutCursor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageInfoWithoutCursor`
        """
        model = PageInfoWithoutCursor()
        if include_optional:
            return PageInfoWithoutCursor(
                total_rows = 1.337
            )
        else:
            return PageInfoWithoutCursor(
                total_rows = 1.337,
        )
        """

    def testPageInfoWithoutCursor(self):
        """Test PageInfoWithoutCursor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
