# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.get_timesheets200_response import GetTimesheets200Response

class TestGetTimesheets200Response(unittest.TestCase):
    """GetTimesheets200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTimesheets200Response:
        """Test GetTimesheets200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTimesheets200Response`
        """
        model = GetTimesheets200Response()
        if include_optional:
            return GetTimesheets200Response(
                data = [
                    dima_sdk.models.get_timesheets_200_response_data_inner.getTimesheets_200_response_data_inner(
                        id = '00000000-0000-0000-0000-000000000000', 
                        type = 'work', 
                        scale = 'custom', 
                        status = 'approved', 
                        contract = dima_sdk.models.get_timesheets_200_response_data_inner_contract.getTimesheets_200_response_data_inner_contract(
                            id = 'string', 
                            type = 'ongoing_time_based', 
                            title = 'string', ), 
                        quantity = 1, 
                        worksheet = dima_sdk.models.get_timesheets_200_response_data_inner_worksheet.getTimesheets_200_response_data_inner_worksheet(
                            days = 0, 
                            hours = 1, 
                            weeks = 0, 
                            minutes = 0, ), 
                        attachment = dima_sdk.models.get_timesheets_200_response_data_inner_attachment.getTimesheets_200_response_data_inner_attachment(
                            key = 'string', 
                            filename = 'string', ), 
                        created_at = '2022-05-04T03:45:27.108Z', 
                        description = 'string', 
                        reported_by = dima_sdk.models.get_timesheets_200_response_data_inner_reported_by.getTimesheets_200_response_data_inner_reported_by(
                            id = '00000000-0000-0000-0000-000000000000', 
                            full_name = 'John Smith', ), 
                        reviewed_by = dima_sdk.models.get_timesheets_200_response_data_inner_reviewed_by.getTimesheets_200_response_data_inner_reviewed_by(
                            id = '00000000-0000-0000-0000-000000000000', 
                            remarks = 'string', 
                            full_name = 'Jane Smith', 
                            reviewed_at = '2022-05-04T03:45:27.899Z', ), 
                        custom_scale = 'string', 
                        total_amount = '200.0000', 
                        currency_code = 'GBP', 
                        payment_cycle = dima_sdk.models.get_timesheets_200_response_data_inner_payment_cycle.getTimesheets_200_response_data_inner_payment_cycle(
                            end_date = '2022-05-24T03:45:27.899Z', 
                            start_date = '2022-05-04T03:45:27.899Z', ), 
                        date_submitted = '2022-05-24T03:45:27.899Z', )
                    ],
                page = dima_sdk.models.get_timesheets_200_response_page.getTimesheets_200_response_page(
                    total_rows = 0, )
            )
        else:
            return GetTimesheets200Response(
                data = [
                    dima_sdk.models.get_timesheets_200_response_data_inner.getTimesheets_200_response_data_inner(
                        id = '00000000-0000-0000-0000-000000000000', 
                        type = 'work', 
                        scale = 'custom', 
                        status = 'approved', 
                        contract = dima_sdk.models.get_timesheets_200_response_data_inner_contract.getTimesheets_200_response_data_inner_contract(
                            id = 'string', 
                            type = 'ongoing_time_based', 
                            title = 'string', ), 
                        quantity = 1, 
                        worksheet = dima_sdk.models.get_timesheets_200_response_data_inner_worksheet.getTimesheets_200_response_data_inner_worksheet(
                            days = 0, 
                            hours = 1, 
                            weeks = 0, 
                            minutes = 0, ), 
                        attachment = dima_sdk.models.get_timesheets_200_response_data_inner_attachment.getTimesheets_200_response_data_inner_attachment(
                            key = 'string', 
                            filename = 'string', ), 
                        created_at = '2022-05-04T03:45:27.108Z', 
                        description = 'string', 
                        reported_by = dima_sdk.models.get_timesheets_200_response_data_inner_reported_by.getTimesheets_200_response_data_inner_reported_by(
                            id = '00000000-0000-0000-0000-000000000000', 
                            full_name = 'John Smith', ), 
                        reviewed_by = dima_sdk.models.get_timesheets_200_response_data_inner_reviewed_by.getTimesheets_200_response_data_inner_reviewed_by(
                            id = '00000000-0000-0000-0000-000000000000', 
                            remarks = 'string', 
                            full_name = 'Jane Smith', 
                            reviewed_at = '2022-05-04T03:45:27.899Z', ), 
                        custom_scale = 'string', 
                        total_amount = '200.0000', 
                        currency_code = 'GBP', 
                        payment_cycle = dima_sdk.models.get_timesheets_200_response_data_inner_payment_cycle.getTimesheets_200_response_data_inner_payment_cycle(
                            end_date = '2022-05-24T03:45:27.899Z', 
                            start_date = '2022-05-04T03:45:27.899Z', ), 
                        date_submitted = '2022-05-24T03:45:27.899Z', )
                    ],
                page = dima_sdk.models.get_timesheets_200_response_page.getTimesheets_200_response_page(
                    total_rows = 0, ),
        )
        """

    def testGetTimesheets200Response(self):
        """Test GetTimesheets200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
