# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.gp_employee_address_to_update_container import GPEmployeeAddressToUpdateContainer

class TestGPEmployeeAddressToUpdateContainer(unittest.TestCase):
    """GPEmployeeAddressToUpdateContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GPEmployeeAddressToUpdateContainer:
        """Test GPEmployeeAddressToUpdateContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GPEmployeeAddressToUpdateContainer`
        """
        model = GPEmployeeAddressToUpdateContainer()
        if include_optional:
            return GPEmployeeAddressToUpdateContainer(
                data = dima_sdk.models.gp_employee_address_update_data.GPEmployeeAddressUpdateData(
                    city = 'London', 
                    street = '123 Deel Street', 
                    zip = '12345', )
            )
        else:
            return GPEmployeeAddressToUpdateContainer(
                data = dima_sdk.models.gp_employee_address_update_data.GPEmployeeAddressUpdateData(
                    city = 'London', 
                    street = '123 Deel Street', 
                    zip = '12345', ),
        )
        """

    def testGPEmployeeAddressToUpdateContainer(self):
        """Test GPEmployeeAddressToUpdateContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
