# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_timesheet_request import CreateTimesheetRequest

class TestCreateTimesheetRequest(unittest.TestCase):
    """CreateTimesheetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTimesheetRequest:
        """Test CreateTimesheetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTimesheetRequest`
        """
        model = CreateTimesheetRequest()
        if include_optional:
            return CreateTimesheetRequest(
                data = dima_sdk.models.create_timesheet_request_data.createTimesheet_request_data(
                    quantity = 2, 
                    contract_id = 'string', 
                    description = '', 
                    date_submitted = 'Fri Dec 31 01:00:00 CET 1999', )
            )
        else:
            return CreateTimesheetRequest(
                data = dima_sdk.models.create_timesheet_request_data.createTimesheet_request_data(
                    quantity = 2, 
                    contract_id = 'string', 
                    description = '', 
                    date_submitted = 'Fri Dec 31 01:00:00 CET 1999', ),
        )
        """

    def testCreateTimesheetRequest(self):
        """Test CreateTimesheetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
