# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.employee_timeoffs_creation_container import EmployeeTimeoffsCreationContainer

class TestEmployeeTimeoffsCreationContainer(unittest.TestCase):
    """EmployeeTimeoffsCreationContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmployeeTimeoffsCreationContainer:
        """Test EmployeeTimeoffsCreationContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmployeeTimeoffsCreationContainer`
        """
        model = EmployeeTimeoffsCreationContainer()
        if include_optional:
            return EmployeeTimeoffsCreationContainer(
                data = dima_sdk.models.employee_timeoffs_item_response.EmployeeTimeoffsItemResponse(
                    time_off_id = 'bca1738c-194a-48e7-a26d-89fddca5bff3', 
                    time_off_type_id = 'e0a91fd6-0646-41ae-84a9-ca3d2f761793', 
                    policy_id = '85cae186-c0b2-4b92-b554-d8eb1f0fdc1d', 
                    policy_name = 'Vacation - unlimited days', 
                    policy_type_name = 'Vacation', 
                    reason = 'I need to relax.', 
                    type = 'VACATION', 
                    requested_at = '2023-08-03T22:00:00.000Z', 
                    reviewed_at = '2023-08-03T22:00:00.000Z', 
                    with_multiple_dates = False, 
                    single_date = '2023-08-03T22:00:00.000Z', 
                    created_at = '2023-08-03T22:00:00.000Z', 
                    updated_at = '2023-08-03T22:00:00.000Z', 
                    denial_reason = False, 
                    requester = dima_sdk.models.requester_time_off.RequesterTimeOff(
                        is_part_time = False, 
                        has_reached_end_date = False, 
                        id = '00000000-0000-0000-0000-000000000000', 
                        uuid = '8bf2ee9c-aa43-4d8e-9f6f-ee8b880b3607', 
                        hris_profile_id = '05ab39e5-1200-4cc1-90bf-0969e02bcf02', 
                        client_profile_id = '08462445-3a37-4d3e-8413-bf28a125dabd', 
                        organization_id = 306415, 
                        country = 'LB', 
                        worker_type = 'hris_direct_employee', 
                        end_date = '2023-08-04T09:03:31.577Z', 
                        part_time_percentage = '', 
                        created_at = '2023-08-04T09:03:31.577Z', 
                        updated_at = '2023-08-04T09:03:31.577Z', ), 
                    days_used_start_year = '0.50', 
                    days_used_end_year = '0.00', 
                    days_used = '0.50', 
                    start_date = '2024-02-23T23:00:00.000Z', 
                    end_date = '2024-02-25T23:00:00.000Z', 
                    is_start_date_half_day = False, 
                    is_end_date_half_day = True, 
                    attachments = [], 
                    change_request = '', 
                    is_updated = False, 
                    applied_changes = [], 
                    can_request_changes = False, )
            )
        else:
            return EmployeeTimeoffsCreationContainer(
                data = dima_sdk.models.employee_timeoffs_item_response.EmployeeTimeoffsItemResponse(
                    time_off_id = 'bca1738c-194a-48e7-a26d-89fddca5bff3', 
                    time_off_type_id = 'e0a91fd6-0646-41ae-84a9-ca3d2f761793', 
                    policy_id = '85cae186-c0b2-4b92-b554-d8eb1f0fdc1d', 
                    policy_name = 'Vacation - unlimited days', 
                    policy_type_name = 'Vacation', 
                    reason = 'I need to relax.', 
                    type = 'VACATION', 
                    requested_at = '2023-08-03T22:00:00.000Z', 
                    reviewed_at = '2023-08-03T22:00:00.000Z', 
                    with_multiple_dates = False, 
                    single_date = '2023-08-03T22:00:00.000Z', 
                    created_at = '2023-08-03T22:00:00.000Z', 
                    updated_at = '2023-08-03T22:00:00.000Z', 
                    denial_reason = False, 
                    requester = dima_sdk.models.requester_time_off.RequesterTimeOff(
                        is_part_time = False, 
                        has_reached_end_date = False, 
                        id = '00000000-0000-0000-0000-000000000000', 
                        uuid = '8bf2ee9c-aa43-4d8e-9f6f-ee8b880b3607', 
                        hris_profile_id = '05ab39e5-1200-4cc1-90bf-0969e02bcf02', 
                        client_profile_id = '08462445-3a37-4d3e-8413-bf28a125dabd', 
                        organization_id = 306415, 
                        country = 'LB', 
                        worker_type = 'hris_direct_employee', 
                        end_date = '2023-08-04T09:03:31.577Z', 
                        part_time_percentage = '', 
                        created_at = '2023-08-04T09:03:31.577Z', 
                        updated_at = '2023-08-04T09:03:31.577Z', ), 
                    days_used_start_year = '0.50', 
                    days_used_end_year = '0.00', 
                    days_used = '0.50', 
                    start_date = '2024-02-23T23:00:00.000Z', 
                    end_date = '2024-02-25T23:00:00.000Z', 
                    is_start_date_half_day = False, 
                    is_end_date_half_day = True, 
                    attachments = [], 
                    change_request = '', 
                    is_updated = False, 
                    applied_changes = [], 
                    can_request_changes = False, ),
        )
        """

    def testEmployeeTimeoffsCreationContainer(self):
        """Test EmployeeTimeoffsCreationContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
