# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.eor_contract_benefits_inner_provider import EORContractBenefitsInnerProvider

class TestEORContractBenefitsInnerProvider(unittest.TestCase):
    """EORContractBenefitsInnerProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EORContractBenefitsInnerProvider:
        """Test EORContractBenefitsInnerProvider
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EORContractBenefitsInnerProvider`
        """
        model = EORContractBenefitsInnerProvider()
        if include_optional:
            return EORContractBenefitsInnerProvider(
                name = 'Provider name'
            )
        else:
            return EORContractBenefitsInnerProvider(
        )
        """

    def testEORContractBenefitsInnerProvider(self):
        """Test EORContractBenefitsInnerProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
