# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.put401k_plans_definition_request_contribution_value_for_match_rate_inner import Put401kPlansDefinitionRequestContributionValueForMatchRateInner

class TestPut401kPlansDefinitionRequestContributionValueForMatchRateInner(unittest.TestCase):
    """Put401kPlansDefinitionRequestContributionValueForMatchRateInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Put401kPlansDefinitionRequestContributionValueForMatchRateInner:
        """Test Put401kPlansDefinitionRequestContributionValueForMatchRateInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Put401kPlansDefinitionRequestContributionValueForMatchRateInner`
        """
        model = Put401kPlansDefinitionRequestContributionValueForMatchRateInner()
        if include_optional:
            return Put401kPlansDefinitionRequestContributionValueForMatchRateInner(
                rate = 10,
                limit = 100
            )
        else:
            return Put401kPlansDefinitionRequestContributionValueForMatchRateInner(
                rate = 10,
                limit = 100,
        )
        """

    def testPut401kPlansDefinitionRequestContributionValueForMatchRateInner(self):
        """Test Put401kPlansDefinitionRequestContributionValueForMatchRateInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
