# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.create_worker_relation_external_id_container import CreateWorkerRelationExternalIdContainer

class TestCreateWorkerRelationExternalIdContainer(unittest.TestCase):
    """CreateWorkerRelationExternalIdContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkerRelationExternalIdContainer:
        """Test CreateWorkerRelationExternalIdContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkerRelationExternalIdContainer`
        """
        model = CreateWorkerRelationExternalIdContainer()
        if include_optional:
            return CreateWorkerRelationExternalIdContainer(
                data = dima_sdk.models.create_worker_relation_external_id_container_data.CreateWorkerRelationExternalIdContainer_data(
                    parent_external_hris_profile_id = '2612dbba-9cf0-4273-bb36-aeb7d0a54676', 
                    child_hris_profile_ids = [
                        dima_sdk.models.create_worker_relation_external_id_container_data_child_hris_profile_ids_inner.CreateWorkerRelationExternalIdContainer_data_child_hris_profile_ids_inner(
                            external_hris_profile_id = '8fbf9ec8243', 
                            relation_external_id = '8fbf9ec8243', )
                        ], 
                    hris_relationship_type_external_id = '8fbf9ec8243', )
            )
        else:
            return CreateWorkerRelationExternalIdContainer(
        )
        """

    def testCreateWorkerRelationExternalIdContainer(self):
        """Test CreateWorkerRelationExternalIdContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
