# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.update_shift_rate_request_data import UpdateShiftRateRequestData

class TestUpdateShiftRateRequestData(unittest.TestCase):
    """UpdateShiftRateRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateShiftRateRequestData:
        """Test UpdateShiftRateRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateShiftRateRequestData`
        """
        model = UpdateShiftRateRequestData()
        if include_optional:
            return UpdateShiftRateRequestData(
                name = 'dcba',
                type = 'MULTIPLIER_PERCENTAGE',
                value = 80.2
            )
        else:
            return UpdateShiftRateRequestData(
        )
        """

    def testUpdateShiftRateRequestData(self):
        """Test UpdateShiftRateRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
