# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.invoice_adjustment_review_to_create import InvoiceAdjustmentReviewToCreate

class TestInvoiceAdjustmentReviewToCreate(unittest.TestCase):
    """InvoiceAdjustmentReviewToCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceAdjustmentReviewToCreate:
        """Test InvoiceAdjustmentReviewToCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceAdjustmentReviewToCreate`
        """
        model = InvoiceAdjustmentReviewToCreate()
        if include_optional:
            return InvoiceAdjustmentReviewToCreate(
                status = 'approved',
                reason = ''
            )
        else:
            return InvoiceAdjustmentReviewToCreate(
                status = 'approved',
                reason = '',
        )
        """

    def testInvoiceAdjustmentReviewToCreate(self):
        """Test InvoiceAdjustmentReviewToCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
